### ISSUE TITLE
Migration from 0.6.0 to 0.7.0+ and flattening values 

### ISSUE THREAD

**Issue by coltfred** [tpolecat/doobie#1023]
In 0.6.0 I had a function which allowed me to flatten a value which had a write instance without explicitly writing the `?`s in the query.

```scala
  /** Flattened `a` as a VALUES argument (...). */
  def flattenValues[A](a: A)(implicit ev: Write[A]): Fragment =
    Fragment(List.fill(ev.length)("?").mkString("(", ", ", ")"), a)
```

This no longer works in 0.7.0+ because the Fragment structure has changed. How should this method be written against the new api?

**Comment by coltfred** [comment]
I started to push on this a bit, but ended up at a dead end.

`ev` for the `Write[A]` has `puts` and `toList` which would seem to be enough to construct the `Elem` list that I need, but since `toList` returns `List[Any]` and the puts is a list of `Put[_]` it feels like the type information I need to convince the compiler isn't present.

Am I missing the way to do this? Is  there some alternate way to accomplish this that is preferred in doobie 0.8.2?

**Comment by tpolecat** [comment]
This should work for "flat" products where each element has a `Put` instance.

```scala
@ def values[A, B <: HList](a: A)(
    implicit g: Generic.Aux[A, B], 
             p: Param[B]
  ): Fragment = {
    val es = p.elems(g.to(a))
    Fragment(es.as("?").mkString(","), es, None)
  }

defined function values

@ case class Person(n: String, a: Int) 
defined class Person

@ values(Person("Bob", 10)) 
res20: Fragment = Fragment("?,?")

@ values((42, true, 1.23, "hi")) 
res21: Fragment = Fragment("?,?,?,?")
```

**Comment by coltfred** [comment]
Just noting this here so if others come across it they'll understand.

This will not work if your case class you're trying to flatten has newtypes in it, only if the types that are in your case class have `Put` instances.
