### ISSUE TITLE
No implicits found for parameter f: Factory[T, C_]. Scala 2.13.1

### ISSUE THREAD

**Issue by degtevO** [tpolecat/doobie#1061]
I faced the bug with doobie 0.8.4 and scala 2.13.1. Method `Query0.to[F[_]]` produces an error in IDEA: 

> No implicits found for parameter f: Factory[T, C_]

![Безымянный](https://user-images.githubusercontent.com/34951485/68029501-6afaf080-fcc8-11e9-800f-01a889a81274.png)

However this code successfully compiles and runs.

Switching to scala 2.12 fixes this bug. But working with 2.13 becomes a kind of incomfortable.
Updating IntelliJ IDEA to the latest version(2019.2.4 for now) does not help.

**Comment by tpolecat** [comment]
Sounds like a bug in IntelliJ.

**Comment by LolHens** [comment]
I had the same problem. As a workaround I just defined the FactoryCompat implicit manually. That made the error message disappear.
```scala
private implicit def seqFactoryCompat[A]: FactoryCompat[A, Seq[A]] =
  FactoryCompat.fromFactor(Seq.iterableFactory)
```
