### ISSUE TITLE
Mappings for JSR-310 and other date types

### ISSUE THREAD

**Issue by zsambek** [tpolecat/doobie#1099]
`doobie 0.8.6` was released a few days ago. This version of doobie provides proper mappings for all JSR-310 date types. 

Before `0.8.6` doobie already had mapping for the `java.time.Instant` (which is also a JSR-310 date type), but it was not implemented the way as the JSR-310 recommends, because it was converted first to `java.sql.Timestamp`. 
That was quite delightful because even if the underlying layer did not supported `java.time.Instant` (for example PostgreSQL), the library users were still able to serialize it. 

Because the new version of doobie does not provide this custom mapping anymore, instead it uses the recommended way to serialize and deserialize all JSR-310 types, including the `java.time.Instant`, it broke the serialization and deserialization for `java.time.Instant` everywhere where it is not supported by the JDBC driver. 

This was a bad decision because the library users only realized that something has changed when they ran their code. 

@tpolecat came up with an idea that we should not provide default mappings for date types, so the library users would notice that something has changed during compile time. 
They could choose whether they want to import the new JSR-310 or the legacy way to serialize and deserialize `java.time.Instant` and every other date type. 

The question is about in which package should we put the `java.sql._` date types and the `java.time._` date types and where should we put the legacy mapping for those type which has new mappings as well (e.g. `java.time.LocalDate` and `java.time.Instant`)? 

@tpolecat and I came up with some ideas, but it would be nice if others could also share their opinions. 

`java.sql._` should go into `doobie.implicits.javasql`
`java.time._` should go into `doobie.implicits.jsr310`
The legacy serialization of `java.time.Instant` and `java.time.LocalDate` should go into `doobie.implicits.legacy.instant` and `doobie.implicits.legacy.localdate`

**Comment by jozic** [comment]
why not `doobie.implicits.javatime` instead of `doobie.implicits.jsr310`?
as a user I don't care (and may not even know) what spec request those classes came from

**Comment by tpolecat** [comment]
> `doobie.implicits.javatime`

👍

**Comment by zsambek** [comment]
@jozic I like that too.

**Comment by zsambek** [comment]
@jozic First shot: https://github.com/tpolecat/doobie/pull/1100

**Comment by tpolecat** [comment]
Fixed in 0.8.8, see https://github.com/tpolecat/doobie/releases
