### ISSUE TITLE
Mention casting on the database 

### ISSUE THREAD

**Issue by kryptt** [tpolecat/doobie#110]
showing something like: 
```
scala> sql"UPDATE core.roles SET permissions = $ps::core.permission[]".update.run.transact(xa).run 
res11: Int = 1 
scala> val q = sql"SELECT permissions FROM core.roles".query[List[Permission.Value]].unique.transact(xa).run 
q: List[msw.core.Permission.Value] = List(mswAdmin, teacher, student)
```
as a demonstration of how to handle postgres' asymetry for Out[String], In[PGObject]
having the cast inside the sql statement itself brings back the sanity of Out[String], In[String], even if it is an _unsafe_ cast.

**Comment by tpolecat** [comment]
Moving this to 0.2.2 just to get this thing out the door. I need to add a FAQs & HAQs page

**Comment by tpolecat** [comment]
See also this [SO Post](http://stackoverflow.com/questions/30946659/jdbc-insert-with-postgres-enum) from Keven Meredith.
