### ISSUE TITLE
Doobie case class column name mapping error

### ISSUE THREAD

**Issue by sumeetpri** [tpolecat/doobie#1102]
I have a case class that has 53 attributes and I am using that in the doobie to get data from the database. 
One of the column name is just name and its failing to build 
compilation with error (java.lang.StackOverflowError)

Does Dobbie has a limit on the number of columns

**name: String**

```
case class A(a:String,b:String,c:String,name:String ...... 53 attributes)
case class B(a:String,b:String,c:String,d:String ...... 20 attributes)**

val query = sql"""SELECT 53 columns from table )"""
      .stripMargin.query[(A,B)]
```

**gradle** 
implementation("org.tpolecat:doobie-core_2.12")
scala - 2.12.10

```
Task :compileScala FAILED
## Exception when compiling classes/scala/main
java.lang.StackOverflowError

```

**Comment by tpolecat** [comment]
There is no limit on the number of columns but the compiler may need more stack space. Try using `-Xss` to increase stack space for the JVM when you compile.

**Comment by sumeetpri** [comment]
Worked
