### ISSUE TITLE
No implicit found for java.time.ZonedDateTime

### ISSUE THREAD

**Issue by ostronom** [tpolecat/doobie#1107]
I am trying to summon `Writer` for `java.time.ZonedDateTime` and I am getting this:
```
import doobie.util.Write
import doobie.implicits._
import java.time.ZonedDateTime
val w = Write[java.time.ZonedDateTime]
```

```
<console>:16: error: could not find implicit value for parameter A: doobie.util.Write[java.time.ZonedDateTime]
```

Am I doing something wrong or there is a bug?

Doobie version 0.8.6-0.8.8
Scala: 2.12.{8,10} - 2.13.1

**Comment by tpolecat** [comment]
Yes, due to some conflicts we had to put those instances behind another import. If you add `import doobie.implicits.javatime._` you will get the instance you're looking for. See the release notes for more information.

**Comment by jozic** [comment]
@tpolecat in release notes the import says
`import doobie.implicits.javasql._` for `java.time`, it should be `import doobie.implicits.javatime._`, right?

**Comment by tpolecat** [comment]
Yes, you're correct. There was a typo in the release notes. If you `import doobie.implicits.javatime._` you will get the instance for `ZonedDateTime`.

**Comment by udalrich** [comment]
That import is deprecated.  If I switch to the suggested alternative (`import doobie.postgres.implicits._`), it does not find a Writer.

**Comment by jatcwang** [comment]
Consider switching to java.time.Instant. `ZonedDateTime` isn't really storable in any typical database column so it'd be incorrect to provide Read/Write instance for it.
