### ISSUE TITLE
Postgres - Array of dates

### ISSUE THREAD

**Issue by leosilvadev** [tpolecat/doobie#1111]
Hi, I am facing one issue trying to map an array of dates from postgres.
What is happening is that I have to create a property of `List[Strint]` but at runtime this comes at `sql.Date`, but when trying to create the property as `List[sql.Date]` it does not compile missing a Read instance for the type. I already tried to place the Read implementation for that (String => LocalDate, sql.Date => LocalDate and all other possibilities) but nothing worked so far.

I am using doobie postgres 0.8.6

**Comment by leosilvadev** [comment]
I tried with the version 0.8.8, the problem still happens

**Comment by leosilvadev** [comment]
When I define my class as String, when I try to use it as String I face the issue at runtime:

```java.lang.ClassCastException: java.sql.Date incompatible with java.lang.String```

**Comment by tpolecat** [comment]
You can create the instance yourself, which will work ok as long as nothing is ever null.

```scala
@ implicit val x = Meta.Advanced.array[java.sql.Date]("date", "_date") 
x: Meta[Array[java.sql.Date]] = doobie.util.meta.Meta@3af39e8f

@ sql"select ${Array(new java.sql.Date(3, 2, 1), new java.sql.Date(1, 2, 3))}".query[Array[java.sql.Date]].unique.transact(xa).unsafeRunSync 
res32: Array[java.sql.Date] = Array(1903-03-01, 1901-03-03)
```

If you want to handle nulls then you'll need something more general, as done [here](https://github.com/tpolecat/doobie/blob/master/modules/postgres/src/main/scala/doobie/postgres/Instances.scala#L82-L103). I will take a PR adding the date/time array instances if you want to add them all.

**Comment by leosilvadev** [comment]
@tpolecat sorry for the delay. Thanks, it worked!
