### ISSUE TITLE
doobie-rebind

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#112]
Add a contrib package if this makes sense, or at least an example of using https://github.com/adelbertc/rebind with doobie. It seems ideal for dealing with deadlocks.

/cc @adelbertc

**Comment by adelbertc** [comment]
Awesome possum - I think I'm getting close to a 0.2.0 where I've added a few things which may be useful (e.g. retry up to N consecutive failures of a particular error), will post once I've published.

**Comment by tpolecat** [comment]
Pushed onto backlog until it's stable.
