### ISSUE TITLE
Any plans about stable 1.0 version?

### ISSUE THREAD

**Issue by kell18** [tpolecat/doobie#1131]
Hi! Thank you for the great library!

Do you have any plans to ship a stable 1.0 version?

Thanks, Albert

**Comment by tpolecat** [comment]
I have no specific plans.

**Comment by kell18** [comment]
Thanks for the answer. 
Sorry for persistence, but why not? Do you still have some big refactoring in mind or maybe something else?
I'm asking because it _feels_ much safer to rely on stable versions in production :)

**Comment by benhutchison** [comment]
Im just a Doobie user and dont speak for @tpolecat in any way. 

I will observe there are two disruptive waves passing through the Scala & Typelevel ecosystem right now that IMO would need to pass before a 1.0 made any sense

- Cats Effect 3.x and FS2 3.x upgrade https://github.com/tpolecat/doobie/pull/1280
- Scala 3 release is months away

Also, fwiw stability judgments based on a version number are illusory. Look at the community size, codebase activity, quality of tests and docs, conduct of maintainers, tech trends, current PRs. Most of all, try it out yourself.

**Comment by jatcwang** [comment]
To add to Ben's point, Doobie is also used primarily by applications themselves (instead of by libraries, unlike cats/cats-effect) so binary compatibility (signified by 1.0) is still important but not the top priority. It's being used by many companies in production for years so a version number wouldn't really change much.

**Comment by kell18** [comment]
Why not release 1.0 now and make 2.0 with mentioned new things? Yes, it doesn't guarantee you anything but it's an important milestone for the community. And many people I worked with rightly observed that it's hard to trust a lib which cannot make it to 1.0 for years

**Comment by kell18** [comment]
After all, I respect maintainers decision about releasing or not releasing 1.0 and I don't want to argue about that. I just wanted to know the reasons, thanks!
