### ISSUE TITLE
Order in case class ( selecting few columns and not all )

### ISSUE THREAD

**Issue by sumeetpri** [tpolecat/doobie#1137]
I have a case class that has 3 columns and in the select query, I am selecting 2 columns. The rest of the column I want to be initialized to None.

```
case class A(a:String,b:Option[String]=None,c:Option[String]=None)
case class B(a1:String,b1:Option[String]=None,c1:Option[String]=None)

val query = sql"""SELECT a,b, a1,c1 from table )"""
      .stripMargin.query[(A,B)]
```

Is order important

**Comment by tpolecat** [comment]
It's entirely positional, so the order is the only thing that matters. But you can't map directly to data types with default field values like that. You'll have to do `.query[(String, Option[String], String, Option[String]).map { case (a, b, a1, b1) => (A(a, b), B(a1, b1)) }`

**Comment by jatcwang** [comment]
Seems like this is addressed. Closing (https://gitter.im/tpolecat/doobie if you have more questions)
