### ISSUE TITLE
org.postgresql.util.PSQLException: The column index is out of range

### ISSUE THREAD

**Issue by serragnoli** [tpolecat/doobie#1160]
Hi.

I've got stuck with this issue and unfortunately I can't figure it out by myself?

The following error happens only on interpolation:
```
org.postgresql.util.PSQLException: The column index is out of range: 2, number of columns: 1.
```
If the variables are removed, the query works just fine:
```scala
def fetchBy(geoPoint: GeoPoint, radius: Int): Query0[Merchant] = {
  sql"""SELECT data->>'name' AS name, data->>'address' AS address, data->>'postCode' AS postCode, st_distance(ST_GeogFromText('SRID=4326;Point(-0.233226 51.5060804)'), location) AS distance FROM merchant WHERE ST_DWithin(location, ST_GeogFromText('SRID=4326;Point(-0.233226 51.5060804)'), 1000) ORDER BY distance;"""
  .query[Merchant]
}
```
I'm trying to interpolate the Long/Lat in the query as follows :
```
[...] Point(${geoPoint.longitude} ${geoPoint.latitude}) [...]
```

**My set-up**
Postgres GIS Schema:
```sql
CREATE EXTENSION postgis;

CREATE TABLE merchant (
  id varchar NOT NULL,
  location geography,
  data jsonb
);
```

Case class to decode the query result to:
```scala
final case class Merchant(name: String, address: Option[Address] = None, postCode: String, distance: Option[String] = None)
  object Merchant {
    implicit val merchantEncoder: Encoder[Merchant]       = deriveEncoder[Merchant]
    implicit val merchantDecoder: Decoder[Merchant]       = deriveDecoder[Merchant]
    implicit val decoder: EntityDecoder[IO, Merchant]     = jsonOf[IO, Merchant]
  }
```

Thanks a lot.

**Comment by tpolecat** [comment]
You won't be able to say `'SRID=4326;Point(${geoPoint.longitude} ${geoPoint.latitude})'` because it's expanded to `'SRID=4326;Point(? ?)'` and the placeholders are inside the quote which isn't a legal position. So what you can do is something like this `ST_GeogFromText (${s"SRID=4326;Point(${geoPoint.longitude} ${geoPoint.latitude})"})` which expands to `ST_GeogFromText(?)` which is ok; i.e., pass the whole quoted string as an argument.

**Comment by serragnoli** [comment]
It works perfectly now.
Thanks a lot for your help @tpolecat .
