### ISSUE TITLE
quill version is out of date

### ISSUE THREAD

**Issue by HansBrende** [tpolecat/doobie#1170]
The current version of quill is 3.5.1.

https://search.maven.org/search?q=io.getquill

**Comment by fancellu** [comment]
Yep, it is missing the Update.returning functionality

https://github.com/getquill/quill/pull/1720/files

I had to pull in 3.5.1 by hand

Then I could do this with doobie+quill+finch

```
run{
      query[Video].filter(_.id == lift(video.id)).update(lift(video)).returning(r=>r)
    }.transact(xa).map(Ok)
```

**Comment by jatcwang** [comment]
v0.9.0 depends on 3.5.1 so I think this is addressed? https://mvnrepository.com/artifact/org.tpolecat/doobie-quill_2.13/0.9.0 

Let me know if there's a dire need for 3.5.2
