### ISSUE TITLE
Consider creating a ZIO integration for query validation

### ISSUE THREAD

**Issue by saraiva132** [tpolecat/doobie#1212]
At the moment we can validate queries using scalatest (`import doobie.scalatest._` ) integration.

I belive it might be worthwhile to consider creating a ZIO integration `doobie.zio.test`. 

Has this been considered ? I will be drafting something on my side for now but would be open to contribute with such module, if there is interest.

**Comment by saraiva132** [comment]
I have written a naive implementation but currently suffering some issues because of transactor dependency.

**Comment by tpolecat** [comment]
Not interested, but thank you.
