### ISSUE TITLE
Booleans don't appear to work

### ISSUE THREAD

**Issue by thesunnyk** [tpolecat/doobie#123]
Trying to map in a Boolean to a "bool" (or even a "bit") in H2 results in an analysis error:
```
Boolean is not coercible to BOOLEAN (BOOLEAN) according to the JDBC specification. Fix this by changing the schema type to BIT,  or the Scala type to .
```

Should this happen? I would've thought a boolean mapping by default makes sense.

**Comment by tpolecat** [comment]
That sounds like an oversight; early versions of the JDBC spec didn't have `BOOLEAN` so the reference I used may not have been updated (although `BIT` should certainly work, although H2 may never report that JDBC type in its metadata). In any case I'll look at this for 0.2.1 so if there's an easy fix you should get it in the next week or so. Thanks!

**Comment by thesunnyk** [comment]
Thanks heaps @tpolecat. The above message appears even if I use "bit" in H2, so I'm guessing H2 somehow interprets "bit" as "boolean".
