### ISSUE TITLE
Work around contravariant ConnectionIO

### ISSUE THREAD

**Issue by simao** [tpolecat/doobie#1234]
This is more a help request rather than an issue, please direct me to the right place if there is a better place to ask this.

I have

```
sealed trait T
case object A extends T
case object B extends T
```

I am trying to `flatMap` a `ConnectionIO[Int]` to transform it into a `ConnectionIO[T]`, depending on the value of the first `ConnectionIO[Int]` and the result of another `ConnectionIO`. The problem is `ConnectionIO` is not covariant, which means I cannot return instances of `A` or `B`. I want to run more queries in the same transaction, depending on the value of the first `ConnectionIO[Int]`.

Is there a way I can work around this and still perform the same IO on the same db transaction, returning an instance of T depending on the result of the first query?

Thank you.

**Comment by jatcwang** [comment]
@simao Not sure if you've solved this, but seems like explicitly annotating/ascripting the type can solve your problem?

e.g. 

```
val connIO: ConnectionIO[Int] = ???
connIO.flatMap {
  case 0 => pure(A: T)
  case 1 => pure[T](B) // another way
}
```

**Comment by simao** [comment]
@jatcwang Yes, `widen` worked! Thanks!
