### ISSUE TITLE
missing changelogs for releases > v0.8.8

### ISSUE THREAD

**Issue by captainju** [tpolecat/doobie#1268]
since version 0.8.2, changelogs are integrated into github release notes
but they're missing for all releases > v0.8.8

**Comment by jatcwang** [comment]
This is what I can gather by looking at the logs

# 0.9.0

## Interpolate `Fragment` values in fragment interpolator

You can now interpolate fragment inside `fr` intepolators as a way to combine fragments (Previously you'd need to use `++`)

For example, you can now do this
```
val num = 1
val whereCondition: Fragment = fr"WHERE age = $num"

fr"SELECT name, age FROM person ${whereCondition} ORDER BY age" 
```

[PR #1045](https://github.com/tpolecat/doobie/pull/1045)

## `Query#toMap` to construct a map

If you have a `Query0[(K, V)]`, you can now call `toMap` to construct a `Map[K, V]`

[PR #1113](https://github.com/tpolecat/doobie/pull/1113)


# 0.9.1

Borked release, do not use

# 0.9.2

## Fragment compbinator for tuple 

[PR #1255]()https://github.com/tpolecat/doobie/pull/1255)

**Comment by jatcwang** [comment]
@captainju  I've added the release notes to the github releases (Only covering new features. Not dep updates). Let me know if I missed anything :)
