### ISSUE TITLE
sql builder function

### ISSUE THREAD

**Issue by Yash0215** [tpolecat/doobie#1271]
I think it will be a good idea to integrate sql builder functions which can be used to derive sql query. for example the sql  "select id from Foo" can also be derives using builder functions like sql.from("foo").select("id")[Int] or sql.from("Foo").selectInt("id"). similarly more complex queries can be derived using more in-built functions. each function can create a 'Fragment' object which will ultimately will be used to derive 'Query0'. it could be more handy or user friendly to some users. just a suggestion...

**Comment by Daenyth** [comment]
This is way out of scope, I think.

If you want that sort of thing, Quill is going to be far better than doobie could be, and you can use the `doobie-quill` compat module to freely mix raw sql and dsl queries

**Comment by tpolecat** [comment]
My instinct here is that it would end up being not super useful because ultimately you're just doing string concatenation. But it's really about ergonomics so there's no way to tell unless you try it. It may be out of scope here but it could be an interesting add-on library if it works out.

**Comment by tpolecat** [comment]
(If you try to keep track of types you'll find that it gets out of hand very very quickly.)

**Comment by Yash0215** [comment]
i think I can see your point about usefulness of this. the thing is im not sure myself. but about the 'keeping track of types' i think i have a way around it which can be done easily.
