### ISSUE TITLE
Oracle order by and string interpolation

### ISSUE THREAD

**Issue by ghostbuster91** [tpolecat/doobie#1286]
Hi, 

First of all thank you for this great library!

Recently I have this questionable pleasure of working with oracle db. I run into some issue while trying to implement ordering and I wonder whether it is the fault of oracle and what's the correct approach.

Here is my query:
```
      (sql"SELECT name FROM threshold_billing_rule ORDER BY name DESC")
        .query[String]
        .to[List]
```

and it works, but I need to parametrize the orderBy column, unfortunately as soon as I do that:
```
(sql"SELECT name FROM threshold_billing_rule ORDER BY $name DESC")
        .query[String]
        .to[List]
```

sorting order stops being taken into account.
The only way to fix it is by passing the orderBy column name through `Fragment.const0`. 

Is this the correct solution?

**Comment by jatcwang** [comment]
I might be wrong, but I don't think you can parameterize the ORDER BY columns must like how you can't parameterize the columns for SELECT.

Alternatively, if you substitute in your column name, you'll end up with the following query:

```
SELECT name FROM threshold_billing_rule ORDER BY 'my_column' DESC
```

I'm not sure what oracle does with a string constant as the order by criteria, but that may explain why it's ignoring it.

**Comment by jatcwang** [comment]
You're in luck, I happen to have access to Oracle (shoot me now), and can confirm that it just ignores string constants as it's treating it as an expression. So that'd explain the behaviour you're seeing.

https://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqlj13658.html

**Comment by ghostbuster91** [comment]
Ok, thanks for the explanation, yeah I would expect oracle to throw an error instead of silently ignoring some part of sql statement, but I guess it's just oracle things ;)

**Comment by Daenyth** [comment]
I'll note that what you want will work if you make `name` be a `Fragment`, just be aware that it's directly sql injection - don't take unchecked user input

```scala
val orderBy = Fragment.const(name)
sql"SELECT name FROM threshold_billing_rule ORDER BY $name DESC"
```
