### ISSUE TITLE
Update doc for the correct imports for java.time.* instances for Postgres/MySQL

### ISSUE THREAD

**Issue by jatcwang** [tpolecat/doobie#1287]
This is a common question so we should add/update docs. 

* Add a FAQ section with table.
* Update https://tpolecat.github.io/doobie/docs/12-Custom-Mappings.html to point to the FAQ

relevant release notes: https://github.com/tpolecat/doobie/releases/tag/v0.8.8

**Comment by Daenyth** [comment]
Related: #1236
