### ISSUE TITLE
Book Of Doobie - Text doesn't correspond to code example

### ISSUE THREAD

**Issue by LLCampos** [tpolecat/doobie#1288]
In [here](https://tpolecat.github.io/doobie/docs/04-Selecting.html#reading-rows-into-collections), there's the following snippet of code:

```scala
sql"select name from country"
  .query[String]    // Query0[String]
  .to[List]         // ConnectionIO[List[String]]
  .transact(xa)     // IO[List[String]]
  .unsafeRunSync    // List[String]
  .take(5)          // List[String]
  .foreach(println) // Unit
// Afghanistan
// Netherlands
// Netherlands Antilles
// Albania
// Algeria
```

But the text that follows does **not** correspond to this example, e.g., it mentions `.unique`, which is not called in the snippet.

**Comment by jatcwang** [comment]
Hi thanks for reporting an issue, but I think in this case it's intentional. You can see that mention of `unique` etc follows "Similar methods are:"

Perhaps it'd be clearer if those were sublist items? Would you like to make a PR to help make it clearer? :)

**Comment by LLCampos** [comment]
Ok, checked this out and it seems that in [the markdown file](https://github.com/tpolecat/doobie/blob/f04a7a3cab5aecb50be0d1ad10fbdae6b8db5ec2/modules/docs/src/main/mdoc/docs/04-Selecting.md#reading-rows-into-collections), those are sublist items indeed!

I guess the issue then is with the docs generation (through [mdoc](https://github.com/scalameta/mdoc))?

**Comment by jatcwang** [comment]
Possibly a bug in Paradox. I'm using mdoc for my other [project documentation](https://jatcwang.github.io/doobieroll/docs/assembler) and sublists work fine there.

**Comment by LLCampos** [comment]
Yes, it's a bug in Paradox. Already raised [an issue](https://github.com/lightbend/paradox/issues/452) on its repo, so I guess this one can be closed.

**Comment by jatcwang** [comment]
Thank you @LLCampos  :)
