### ISSUE TITLE
Issue with .to[List]

### ISSUE THREAD

**Issue by SarpongAbasimi** [tpolecat/doobie#1330]
Please does anybody know what the issue is over here. I am following the `docs`  and can't seem to figure out what is wrong when running `.to[List] ` to create a `ConnectionIO[List[String]]`

<img width="613" alt="Screen Shot 2020-12-12 at 21 07 34" src="https://user-images.githubusercontent.com/37377831/101995126-c1a26e80-3cbf-11eb-86af-d1d50339f67b.png">

**Comment by tpolecat** [comment]
Does it compile with sbt? It may just be an IntelliJ issue.

**Comment by SarpongAbasimi** [comment]
@tpolecat Yes please, it does compile with sbt. What what do you think the issue it?

**Comment by tpolecat** [comment]
Sounds like a bug in IntelliJ. You might open an issue over there.
