### ISSUE TITLE
Per-database date time instances

### ISSUE THREAD

**Issue by jatcwang** [tpolecat/doobie#1352]
Here are two of the most common issues I see in gitter chat / issues when people try to work with date time in Doobie:

* Not knowing how to get the `Meta` instances for data time types OR importing the wrong types 
* Using the wrong database types (Can't blame them. `TIMESTAMP WITH TIMEZONE` is VERY misleading)

While some effort has been made in documentation to help, I think the experience leaves a lot to be desired even when you know what you should do.

The idea is to have per-database module for the more popular databases (Postgres first, maybe MySQL) so the user only need to import the implicits for their database to get the right instances. e.g. `import doobie.postgres.implicits._`. This will also allow us to leverage native support for JSR310 types from the JDBC drivers.

Some ideas (for PostgreSQL module in particular) based on https://jdbc.postgresql.org/documentation/head/8-date-time.html for reference

- Use native support for OffsetDateTime, LocalDate, LocalTime, LocalDateTime
- `Instant` instance will be based on OffsetDateTime instance
- Locking down the allowed types so that doobie typechecking will fail if the user uses 
  the wrong corresponding column type for the Java type they are using.
  - e.g. Meta instances for Instant/OffsetDateTime will be JDBC type TimestampWithTimezone, instead of Timestamp
    (See [list of JDBC types](https://github.com/tpolecat/doobie/blob/2fedd4a7873df3f2e0bfac3e8c5543ecbfe07e5e/modules/core/src/main/scala/doobie/enumerated/jdbctype.scala))

Let me know if I missed anything or if there are anything else we should address as part of this work.

**Comment by Daenyth** [comment]
> Instant instance will be based on OffsetDateTime instance

I'm curious why. (in terms of pg:) It seems like `Instant` maps to the `TIMESTAMP` column type, and `TIMESTAMP WITH TIMEZONE` maps to `OffsetDateTime`. Can you elaborate?

**Comment by jatcwang** [comment]
My understanding is that OffsetDateTime is semantically just an Instant with an Offset, which means it's a trivial conversion from Instant -> OffsetDateTime (with offset = 0). OffsetDateTime is more general which is why the jdbc driver chose it. Both should map to TIMESTAMP WITH TIMEZONE as they represent an actual instant in time. (JDBC don't support Instant directly, which is why right now we need the legacy instances based on java.sql.Timestamp when using postgres, but that has it's own problems)

**Comment by jatcwang** [comment]
Done in v0.12 https://github.com/tpolecat/doobie/releases/tag/v0.12.0
