### ISSUE TITLE
Select a list of values without a table

### ISSUE THREAD

**Issue by dmitriibundin** [tpolecat/doobie#1400]
Is there an existing functionality to select a `List` of some values without a table in order to join it with some existing table?

Example:
```
def executeQuery(ids: List[Int]) = 
   sql"select * from (values $ids) s(a) join some_tbl on a=some_tbl.id"
```

**Comment by jatcwang** [comment]
`doobie.util.fragments#in` is probably what you're looking for?
Note that in SQL `IN` requires at least one value, so you have to use NonEmptyList or any other container with a `Reducible` typeclass instance

**Comment by dmitriibundin** [comment]
@jatcwang Thanks for the prompt reply. Unfortunately `doobie.util.fragments#in` is not exactly what I'm looking for. Would it make sense to add something like the following:
 
    def values[F[_]: Reducible, A: util.Put](f: Fragment, fs: F[A]): Fragment =
      fs.toList.map(parentheses).foldSmash1(f ++ fr0"VALUES (", fr",", fr")")

?

**Comment by jatcwang** [comment]
@dmitriibundin Sorry I misread the original example. Yes I think it's a good idea - we can extend it to support tuples e.g.
`SELECT * FROM (VALUES (?,?),(?,?))`.

https://www.postgresql.org/docs/9.5/queries-values.html

Would you like to raise a PR? :)
