### ISSUE TITLE
Cats effect 3

### ISSUE THREAD

**Issue by Jacke** [tpolecat/doobie#1420]
Hello Maintainers. Where is the ce3 version of doobie? We can't wait. Probably will use different tools. Do you have a plan to release it anytime soon?

**Comment by tpolecat** [comment]
A milestone will be out soon.

**Comment by tpolecat** [comment]
1.0.0-M1 has been published and is on its way to Maven Central now.

**Comment by emanueloliveira23** [comment]
Is there any documentation about CE3 + Doobie 1.0.0?

**Comment by jatcwang** [comment]
It's not published right now afaik but it has been updated for CE3. See the branch https://github.com/tpolecat/doobie/tree/series/1.0

But I don't think there are that much difference compared to CE2 usage, so give it a go.
