### ISSUE TITLE
Behavior of conversion from postgres `Timestamp` to `Instant` changes from `0.10.0` to `0.12.0`

### ISSUE THREAD

**Issue by LLCampos** [tpolecat/doobie#1432]
## Setup

`docker-compose.yml`:

```yaml
version: "3.3"
services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
```

Run the following against DB:

```sql
create table test (
  ts timestamp
)

insert into test (ts) values (now())
```

## Relevant Depedencies:

```sbt
  "org.tpolecat" %% "doobie-core" % doobieVersion,
  "org.tpolecat" %% "doobie-hikari" % doobieVersion,
  "org.tpolecat" %% "doobie-postgres" % doobieVersion,
```

## Issue

```scala
package doobie_bug

import cats.effect.Blocker
import cats.effect.ExitCode
import cats.effect.IO
import cats.effect.IOApp
import cats.effect.Resource
import doobie._
import doobie.hikari.HikariTransactor
import doobie.implicits._
import doobie.implicits.legacy.instant._
import doobie.postgres.implicits._

import java.time.Instant
import java.time.ZonedDateTime
import scala.concurrent.ExecutionContext

object WriteToDb extends IOApp {

  implicit val cs = IO.contextShift(ExecutionContext.global)

  val transactor: Resource[IO, HikariTransactor[IO]] =
    for {
      ce <- ExecutionContexts.fixedThreadPool[IO](32)
      be <- Blocker[IO]
      xa <- HikariTransactor.newHikariTransactor[IO](
        "org.postgresql.Driver",
        "jdbc:postgresql://localhost:5432/",
        "postgres",
        "",
        ce,
        be
      )
    } yield xa

  def get(): ConnectionIO[Option[Instant]] =
    sql"select ts from test limit 1".query[Instant].option

  def run(args: List[String]): IO[ExitCode] =
    transactor.use { xa =>
      for {
        ts <- get().transact(xa)
        _ <- IO(println(ts))
      } yield ExitCode.Success
    }
}
```

When `val doobieVersion = "0.10.0"`, it prints `Some(2021-05-01T11:21:22.619203Z)`. This is the UTC time.

When `val doobieVersion = "0.12.0"`, it prints `Some(2021-05-01T12:21:22.619203Z)`. This is the local time. (Same code as above but without `import doobie.implicits.legacy.instant._`). Also happens with `0.13.1`.

Its an `Instant` so I would expect the behavior to not change.

**Comment by jatcwang** [comment]
I think you want column type `timestamptz` if you actually care about an Instant in time, instead of `timestamp` which represent more of a wallclock time (LocalDateTime).

With the former the pgjdbc driver will take care of any timezone convesion between the client (your app) and the DB.

See https://jdbc.postgresql.org/documentation/head/8-date-time.html

I tried tightening the doobie column type tests to help catch these kind of mistakes, but unfortunately JDBC driver is just too lenient on correctness for it to work.

**Comment by jatcwang** [comment]
Closing for now. Please comment if there are still issues thanks
