### ISSUE TITLE
Composite for shapeless records

### ISSUE THREAD

**Issue by kryptt** [tpolecat/doobie#144]
An implicit for shapeless records would be of great value above tuples since you get a key -> value syntax, while not needed to create a case class for it.

I have this method working in my project for that end:
```scala
  implicit def hconsComposite[K <: Symbol, H, T <: HList](implicit
    H: Composite[H],
    T: Composite[T]
  ): Composite[FieldType[K, H] :: T] =
    new Composite[FieldType[K, H] :: T] {
      import shapeless.record.field
      val set = (i: Int, l: H :: T) => H.set(i, l.head) >> T.set(i + H.length, l.tail)
      val update = (i: Int, l: H :: T) => H.update(i, l.head) >> T.update(i + H.length, l.tail)
      val get = (i: Int) => (H.get(i) |@| T.get(i + H.length))(field[K](_) :: _)
      val length = H.length + T.length
      val meta = H.meta ++ T.meta
    }
```
The main difference is wrapping the head of the HList via `field`

**Comment by tpolecat** [comment]
Cool, thanks. We can give this a try after merging #143.

**Comment by kryptt** [comment]
as an FYI this is for shapeless 2.0.0 it needs a few tweaks to work with 2.2.0

**Comment by tpolecat** [comment]
I got that code working but I think maybe we should just rewrite the derivation in the new style like [scodec does here](https://github.com/scodec/scodec/blob/38fa3a257d15a28c6b3aac86123f0ad6ac263cbe/shared/src/main/scala/scodec/Codec.scala#L528). Pushing to 0.3.0

**Comment by tpolecat** [comment]
Actually it works, so let's go ahead and add it. PR in.
