### ISSUE TITLE
Problematic update — doobie-hikari depends on slf4j-api:2.0.0-alpha1

### ISSUE THREAD

**Issue by alexandru** [tpolecat/doobie#1498]
I updated Doobie in our $work project from 0.13.2 to 0.13.4 and we now have this transitive dependency upgrade:

```
[info]   | | +-org.tpolecat:doobie-hikari_2.13:0.13.4 [S]
[info]   | |   +-com.zaxxer:HikariCP:4.0.3
[info]   | |   | +-org.slf4j:slf4j-api:2.0.0-alpha1
```

In doobie version 0.13.2 this was the dependency tree:

```
[info]   +-org.tpolecat:doobie-hikari_2.13:0.13.2 [S]
[info]     +-com.zaxxer:HikariCP:3.4.5
[info]     | +-org.slf4j:slf4j-api:1.7.25
```

`slf4j-api` version `2.0.0-alpha1` breaks compatibility with `1.7.x`, as a result we get this error in testing:

```
[info] com.ing.vesper.paymentengine.ro.LocalSimpleIntegrationTest *** ABORTED *** (40 milliseconds)
[info]   java.lang.IllegalArgumentException: Requires Logback logger for [], it was a [org.slf4j.helpers.NOPLogger]
[info]   at akka.actor.testkit.typed.internal.LogbackUtil$.getLogbackLoggerInternal(LogbackUtil.scala:35)
[info]   at akka.actor.testkit.typed.internal.LogbackUtil$.getLogbackLogger(LogbackUtil.scala:21)
[info]   at akka.actor.testkit.typed.internal.CapturingAppender$.get(CapturingAppender.scala:21)
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.$init$(LogCapturing.scala:36)
[info]   at com.ing.vesper.paymentengine.ro.SimpleIntegrationTest.<init>(SimpleIntegrationTest.scala:24)
[info]   at com.ing.vesper.paymentengine.ro.LocalSimpleIntegrationTest.<init>(LocalSimpleIntegrationTest.scala:32)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
```

I suspect this happens due to some runtime initialization issues.

Also see: https://github.com/brettwooldridge/HikariCP/issues/1746

**Comment by jatcwang** [comment]
Hmm that's a bit weird according to Maven HikariCP should depending on 1.7.30 https://mvnrepository.com/artifact/com.zaxxer/HikariCP/4.0.3

Doobie's build.sbt explicitly ignore HikariCP's slf4j-api dep and depend on 1.7.31 explicitly too. 
Can you provide a small reproduction of this issue?

**Comment by jatcwang** [comment]
Maven search says https://mvnrepository.com/artifact/org.tpolecat/doobie-hikari_3/0.13.4 is depending on 1.7.30 as well

**Comment by alexandru** [comment]
@jatcwang I won't provide a minimal example, too much work 🙂

1. see issue I linked in HikariCP's repository
2. also I don't understand what that `mvnrepository.com` is compiling, but you can see their own `pom.xml` for 4.0.3 does indeed contain 2.0.0-alpha: https://github.com/brettwooldridge/HikariCP/blob/HikariCP-4.0.3/pom.xml#L605

**Comment by alexandru** [comment]
I see they have different profiles. Maybe this is a Java 11 thing.

**Comment by yurique** [comment]
I was trying to exclude the slf4j transitive dependency, but for some reason just `exclude` didn't work for me. Like this:

```scala
      ("org.tpolecat" %% "doobie-hikari" % DependencyVersions.doobie) // "1.0.0-M5"
        .exclude("com.zaxxer", "HikariCP") // these exclusions worked
        .exclude("org.slf4j", "slf4j-api"),
      ("com.zaxxer" % "HikariCP" % DependencyVersions.hikari) // "4.0.3"
        .exclude("org.slf4j", "slf4j-api") // this one didn't
```

After getting a tip from @Daenyth in Discord, I tried to use the dependency overrides, like the following:
```scala
    dependencyOverrides ++= Seq(
      "org.slf4j" % "slf4j-api" % DependencyVersions.slf4j // "1.7.32"
    )
```

And it seems to have worked. One thing to note, is the dependency overrides need to be set at the "very bottom" of the dependency graph:

```
doobie-hikari
project-A depends on doobie-hikari
project-B depends on project-A // the override needs to be set here, having it in project-A alone doesn't do the trick
```

**Comment by marko-asplund** [comment]
Looks like this could be related to https://github.com/coursier/coursier/issues/2148

**Comment by sideeffffect** [comment]
This can be closed

**Comment by jatcwang** [comment]
Thanks

**Comment by linux-root** [comment]
Somehow I'm still facing this issue. Below is dependencies tree of the root `doobie-hikari`, `slf4j-api:2.0.0-alpha1` still exists (my project uses Java11) : 
```
* org.tpolecat:doobie-hikari_2.13:1.0.0-RC2
      |
      |------* com.zaxxer:HikariCP:4.0.3
      |------* org.scala-lang.modules:scala-collection-compat_2.13:2.6.0
      |------* org.slf4j:slf4j-api:1.7.32 (evicted by 2.0.0-alpha1)
      |------* org.slf4j:slf4j-api:2.0.0-alpha1
      |------* org.tpolecat:doobie-core_2.13:1.0.0-RC2
```
@hamnis could you please take a look?
