### ISSUE TITLE
protoquill support

### ISSUE THREAD

**Issue by dwlizlo** [tpolecat/doobie#1506]
I would like to migrate quill module to be compatible with Scala3 (protoquill)

**Comment by dwlizlo** [comment]
Hey @deusaquilus, I wonder if you have faced something similar while implementing Monix/ZIO jdbc context? Cheers!

```
    val actual   = run(stmt).transact(xa).unsafeRunSync()
                       ^^^^
Exception occurred while executing macro expansion.
java.lang.NoClassDefFoundError: java/sql/Date
	at com.twitter.chill.java.SqlDateSerializer.registrar(SqlDateSerializer.java:32)
	at com.twitter.chill.java.PackageRegistrar.all(PackageRegistrar.java:36)
	at com.twitter.chill.AllScalaRegistrar_0_9_2.apply(ScalaKryoInstantiator.scala:206)
	at com.twitter.chill.AllScalaRegistrar_0_10_0.apply(ScalaKryoInstantiator.scala:214)
	at com.twitter.chill.AllScalaRegistrar.apply(ScalaKryoInstantiator.scala:229)
	at com.twitter.chill.ScalaKryoInstantiator.newKryo(ScalaKryoInstantiator.scala:99)
	at com.twitter.chill.ScalaKryoInstantiator.newKryo(ScalaKryoInstantiator.scala:95)
	at com.twitter.chill.KryoInstantiator$6.newKryo(KryoInstantiator.java:101)
	at com.twitter.chill.KryoPool$2.newInstance(KryoPool.java:59)
	at com.twitter.chill.KryoPool$2.newInstance(KryoPool.java:57)
	at com.twitter.chill.ResourcePool.borrow(ResourcePool.java:37)
	at com.twitter.chill.KryoPool.toBytesWithClass(KryoPool.java:114)
	at io.getquill.parser.KryoAstSerializer$.serialize(KryoAstSerializer.scala:292)
	at io.getquill.parser.SerialHelper$.toSerializedJVM(Lifter.scala:18)
	at io.getquill.parser.Lifter.tryToSerialize$$anonfun$1(Lifter.scala:214)
	at scala.util.Try$.apply(Try.scala:210)
	at io.getquill.parser.Lifter.tryToSerialize(Lifter.scala:217)
	at io.getquill.parser.Lifter$$anon$20.applyOrElse(Lifter.scala:231)
	at io.getquill.parser.Lifter$$anon$20.applyOrElse(Lifter.scala:231)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:313)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:309)
	at io.getquill.parser.Lifter$NiceLiftable.apply(Lifter.scala:60)
	at io.getquill.parser.Lifter$NiceLiftable.apply$(Lifter.scala:56)
	at io.getquill.parser.Lifter$liftableAst$.apply(Lifter.scala:229)
	at io.getquill.parser.Lifter$.apply(Lifter.scala:29)
	at io.getquill.context.QuoteMacro$.apply(QuoteMacro.scala:72)

 This location contains code that was inlined from PostgresDoobieContextSuite.scala:63
 This location contains code that was inlined from GetQuill.scala:3
 This location contains code that was inlined from PostgresDoobieContextSuite.scala:62
`

**Comment by jatcwang** [comment]
I assume you're `publishLocal`ing and testing what I merged yesterday? https://github.com/tpolecat/doobie/pull/1505
Not too sure why you're getting NCDF error though..

**Comment by dwlizlo** [comment]
@jatcwang yes, currently we are not releasing quill module for scala3 anyway - this is why CI didn't fail.

I'm trying to make it possible (adjusting the code and fixing the tests first)

**Comment by deusaquilus** [comment]
@dwlizlo The Kryo module is used to capture some parts of Quill’s internal AST between query compilation phases, but none of those should contain java.util.Date. What code is `run(stmt)` in? 
(For Scala 3 these traces won’t contain the original file name. It’s usually one line in the log above the error.)

**Comment by deusaquilus** [comment]
Also, in protoquill the `execute___` methods in Context have slightly different singnatures. I’m going to try to backport these to regular-quill soon.

**Comment by dwlizlo** [comment]
@deusaquilus test is rather basic, I can open draft PR later on to share more info.
```scala
  test("executeQuery should correctly select a country") {
    inline def stmt     = quote { query[Country].filter(_.code == "GBR") }
    val actual   = run(stmt).transact(xa).unsafeRunSync()
    val expected = List(Country("GBR", "United Kingdom", 59623400))
    assertEquals(actual, expected)
  }
  ```
https://github.com/dwlizlo/doobie/blob/f21f142969bd2e714d656f30b4031693578c4e41/modules/quill/src/test/scala/doobie/quill/PostgresDoobieContextSuite.scala#L42

**Comment by deusaquilus** [comment]
Wow! There isn’t even a date field in the record class. I need to look into this.
Just curiously, what happens if you try to compile with `-Dquill.ast.serialize=false`?
(I.e add that to SBT_OPTS)

**Comment by dwlizlo** [comment]
@deusaquilus It didn't change a ton, but there is slight difference.
1. Problematic error just got longer https://gist.github.com/dwlizlo/28fe894073fbab80340283fd67a77ebc
2. Some other queries passed
```
[info] -- Info: /home/duser/src/doobie/modules/quill/src/test/scala/doobie/quill/PostgresDoobieContextSuite.scala:49:22 
[info] 49 |    val actual   = run(stmt).transact(xa).unsafeRunSync()
[info]    |                   ^^^^^^^^^
[info]    |                   Compile Time Query Is: SELECT 42
[info] -- Info: /home/duser/src/doobie/modules/quill/src/test/scala/doobie/quill/PostgresDoobieContextSuite.scala:56:28 
[info] 56 |    val actual   = dc.stream(stmt, 16).transact(xa).as(1).compile.foldMonoid.unsafeRunSync()
[info]    |                   ^^^^^^^^^^^^^^^^^^^
[info]    |Compile Time Query Is: SELECT x.code, x.name, x.population FROM Country x

```

**Comment by deusaquilus** [comment]
@dwlizlo Wait a second, I think this is a jigsaw issue. You need to add `--add-modules java.sql` starting JDK 9 and up. Have a look here:
https://stackoverflow.com/questions/51362463/java-9-modules-noclassdeffounderror-java-sql-date
Also here:
https://stackoverflow.com/questions/51362463/java-9-modules-noclassdeffounderror-java-sql-date

**Comment by dwlizlo** [comment]
@deusaquilus That worked! I switched to JDK 1.8. It unfolded new problem, this time it looks more protoquill-related. 

```
  test("executeBatchAction should correctly do multiple updates") {
    inline def stmt = quote {
      liftQuery(List("U%", "A%")).foreach { pat =>
        query[Country].filter(_.name like pat).update(_.name -> "foo")
      }
    }
    val actual   = run(stmt).transact(xa).unsafeRunSync()
    val expected = List(8L, 15L)
    assertEquals(actual, expected)
  }
```

```
[error] -- Error: /home/duser/src/doobie/modules/quill/src/test/scala/doobie/quill/PostgresDoobieContextSuite.scala:74:21 
[error] 74 |   val actual   = run(stmt).transact(xa).unsafeRunSync()
[error]    |                  ^^^^^^^^^
[error]    |Invalid liftQuery clause: List(EagerListPlanterExpr(cbf23106-7efa-4978-ae29-2ed5d4b147ea,'{ ... },'{ ... })). Must be a single EagerEntitiesPlanter
[error]    | This location contains code that was inlined from PostgresDoobieContextSuite.scala:69
[error]    | This location contains code that was inlined from Context.scala:233
```

**Comment by dwlizlo** [comment]
@deusaquilus There is one more problem which is **.returningGenerated(_.id)** is failing compilation. :thinking: 

```
// compiles just fine
run(query[QuillTest].insert(QuillTest(0, "Foo")))
```

```
// fail
run(query[QuillTest].insert(QuillTest(0, "Foo")).returningGenerated(_.id))
```

https://gist.github.com/dwlizlo/9294cd9a4cdee7a3e17bcc75b8b5ee02

**Comment by deusaquilus** [comment]
@dwlizlo The assertion error [here](https://gist.github.com/dwlizlo/9294cd9a4cdee7a3e17bcc75b8b5ee02) looks like a compiler error. I compiled with 3.0.0 not with 3.0.1 (actually I didn't even know 3.0.1 was even out yet). Can you try with 3.0.0?
The problem with `Must be a single EagerEntitiesPlanter` is an issue on my side that I need to fix. I probably made a bad assumption in ProtoQuill about how `liftQuery` is supposed to work. What's the definition of `Country`?

**Comment by dwlizlo** [comment]
@deusaquilus 3.0.0 works like a charm! I checked it with nightly build and it's also broken.

Here's country case class
```
case class Country(code: String, name: String, population: Int)
```

**Comment by deusaquilus** [comment]
@dwlizlo I'll have a look at this issue as soon as I can. Any chance you can file it as a ProtoQuill issue?
Also, before I continue development of Quill / ProtoQuill, I need to line up the signatures of the `execute__` methods of Quill with what they are in ProtoQuill so that child-contexts e.g. the Doobie ones can have the same code (i.e. source-identical) across the two (I have to make a similar task to do in ProtoQuill changing Prepare and Extract[T] to also take a session as was recently done in Quill). Realistically these things will take a several weeks. Then I'll be able to move on to other issues and bug fixes.
Otherwise, we could quickly get into a situation where Quill / ProtoQuill codebases diverge to a irreconcilable point.

**Comment by deusaquilus** [comment]
FYI, the `execute___` method changes will definitely cause the next Quill release to be incompatible with Doobie until I make a Doobie PR to fix them up (or anyone else whose spirit is moved :wink:). Probably just to ignore the extra arguments of these methods.

**Comment by nafg** [comment]
I guess this is moot too :roll_eyes:

**Comment by Daenyth** [comment]
Good catch, thanks

**Comment by deusaquilus** [comment]
@nafg @dwlizlo 
ProtoQuill 3.16.5-Beta29 has Doobie integration:
https://oss.sonatype.org/#nexus-search;gav~io.getquill~quill-doobie_3~3.16.5-Beta29~~
(Should be up on maven-central soon)
