### ISSUE TITLE
java.lang.ClassCastException: doobie.util.fragment$Fragment cannot be cast to doobie.syntax.SqlInterpolator$SingleFragment

### ISSUE THREAD

**Issue by dan-ilin** [tpolecat/doobie#1515]
I'm attempting to update my project from using doobie v0.5.4 to v0.13.4 and I'm noticing this error occurs on each of the queries:

```
[info]   java.lang.ClassCastException: doobie.util.fragment$Fragment cannot be cast to doobie.syntax.SqlInterpolator$SingleFragment
[info]   at doobie.syntax.SqlInterpolator$.$anonfun$mkFragment$2(string.scala:27)
[info]   at scala.collection.immutable.List.flatMap(List.scala:335)
[info]   at doobie.syntax.SqlInterpolator$.mkFragment$extension(string.scala:27)
[info]   at doobie.syntax.SqlInterpolator$.sql$extension(string.scala:40)
```

The queries are being built using the sql interpolator and worked previously.

**Comment by tpolecat** [comment]
Hm be sure you're not somehow pulling in doobie modules with different versions. Otherwise try a clean build?

**Comment by dan-ilin** [comment]
I checked using the sbt dependency graph plugin to verify that I am only pulling in the version 0.13.4 jars for doobie.
A clean build gives the same results.

**Comment by jatcwang** [comment]
@dan-ilin Might be worth using `show dependencyClasspath` to see the actual JAR files being used. The dependency graph plugin isn't always accurate in my experience.
If it looks like it's just one version, can you try reducing it to a minimal example?

**Comment by jtrebilcockstash** [comment]
Hello, Im working on this with @dan-ilin. I was able to reduce to this example. 

```
import doobie.implicits._

case class MyAccount(accountId: String)

def getAccountById(id: String): ConnectionIO[Option[MyAccount]] = {
      val s = sql"""
        |SELECT
        |  account_id
        |FROM
        |  accounts
        |WHERE account_id = $id
      """.stripMargin.query[MyAccount].option
}

getAccountById("id").transact(transactor).unsafeRunSync() 

```
This fails with `doobie.util.fragment$Fragment cannot be cast to doobie.syntax.SqlInterpolator$SingleFragment`

If we remove the Fragment it works fine. 

This is all the doobie jars we have loaded
```
org/tpolecat/doobie-core_2.12/0.13.4/doobie-core_2.12-0.13.4.jar
org/tpolecat/doobie-postgres_2.12/0.13.4/doobie-postgres_2.12-0.13.4.jar
org/tpolecat/doobie-hikari_2.12/0.13.4/doobie-hikari_2.12-0.13.4.jar
org/tpolecat/doobie-free_2.12/0.13.4/doobie-free_2.12-0.13.4.jar
```

**Comment by jatcwang** [comment]
@jtrebilcockstash 

I tried it myself and I'm not seeing the error. Can you please post a sbt project that shows this issue?

**Comment by jtrebilcockstash** [comment]
@jatcwang @tpolecat figured out the issue. We were running an older version of scala (2.12.4). After upgrading to (2.12.11) this issue went away.

**Comment by jatcwang** [comment]
Thanks for reporting back @jtrebilcockstash. I'll close this now.
