### ISSUE TITLE
Add a way to insert literal values directly into a query to the sql interpolator.

### ISSUE THREAD

**Issue by cannedprimates** [tpolecat/doobie#156]
I'd like to be able to substitute literals into a query to e.g. select the table dynamically.

Example:
https://gist.github.com/cannedprimates/97714b76cf2fb718f443

Slick handles this by providing a special operator, #$, which is described here:
http://slick.typesafe.com/doc/2.1.0/sql.html#string-interpolation

**Comment by tpolecat** [comment]
Thanks for this suggestion, we do need something like this. I added a comment to your gist that shows how to express your query at the moment. Slightly awkward.

**Comment by jesinity** [comment]
is it something that is going to be addressed?

**Comment by wedens** [comment]
@jesinity it's already possible with [fragments](http://tpolecat.github.io/doobie-scalaz-0.4.0/08-Fragments.html)
