### ISSUE TITLE
Concurrent Kleisli interpreter

### ISSUE THREAD

**Issue by rossabaker** [tpolecat/doobie#1561]
Would it be possible and/or advisable to replace the `WeakAsync` interpreter for `Kleisli` with `Concurrent`?  We could get around the limitations of the fs2 `Compiler.Target[Sync]` under discussion in https://github.com/typelevel/fs2/pull/2650, and probably drop the `WeakAsync` typeclass altogether.

I got most of the way there, but hit the recursive operations.  `.start` is the one I'm most worried about being able to implement, but I think I can play Type Tetris with the rest.

**Comment by tpolecat** [comment]
Hm, JDBC is pretty fundamentally sequential so I don't quite understand how this would work. What would it mean to run `ConnectionIO` programs concurrently?

**Comment by rossabaker** [comment]
Fair question that I will think about on my jog right now, but what does it mean to run a `ConnectionIO` weakly asynchronously?  Is that fundamentally JDBC, or is it a hack so that we can build a transactor without resorting to an `unsafeRunSync` or `Await.result`?  

Right now, it's not safe to pass a concurrently-created stream to `lostreaming`.  I watched one team get eaten alive and now another team is headed straight for its maw.

**Comment by tpolecat** [comment]
Ouch, ok. Really the only reason for the async instance is so you can lift callback-based APIs into ConnectionIO. JDBC is all synchronous.

**Comment by rossabaker** [comment]
`F ~> G: WeakAsync` is generally fine.  Translating a `Stream[F, A]` to `Stream[G, A]` is not fine.  The linked fs2 change calls out where Doobie is handing people a grenade, but I don't know what to do about `lostreaming` without making that `F ~> G` difficult, upgrading to `Concurrent`, or fixing fs2.

**Comment by mpilquist** [comment]
Note that stream translation is perfectly safe in fs2 3.x -- it's only 2.x where translating breaks interruptibility (unless you call `translateInterruptible`).

**Comment by rossabaker** [comment]
Translation itself is safe, but it introduces many Streams that are unsafe to compile with `Sync`.  We have to follow the provenance of the stream for any embedded `InterruptWhen`.  If the compilation effect has no `Concurrent` and there was no translation, only a really dumb, greppable `interruptWhen` triggers the error:

```scala
import cats.effect._
import fs2._
import Predef.println

object Oops extends App {
  Stream
    .empty
    // All other interrupts capture a `Concurrent[F]`.  Without such,
    // we can't construct an interesting halt condition.
    .interruptWhen[SyncIO](SyncIO(Right(())))
    .compile
    .toList
    .flatMap(xs => SyncIO(println(xs)))
    .unsafeRunSync()
}
```

`WeakAsync` is a marginally more dangerous: we could construct a halt signal from `ConnectionIO.fromFuture` to smuggle in actual concurrency, but that's a stretch.

But as soon as we translate from something concurrent, we're in real trouble:

```scala
import cats.effect._
import cats.effect.unsafe.implicits.global
import doobie._, doobie.implicits._
import fs2._
import Predef.???

object Oops extends App {
  def concStream[F[_]: Concurrent, A]: Stream[F, A] = {
    Stream.never[F]
  }

  def transactor: Transactor[IO] = ???

  WeakAsync.liftK[IO, ConnectionIO].use { tx =>
    concStream[IO, String]
      // Did concStream call any of dozens of methods, most
      // of which aren't called interruptWhen?
      .translate(tx)
      .compile
      .toList
      .transact(transactor)
  }.unsafeRunSync()
}
```

**Comment by rossabaker** [comment]
Conclusions:
1. My `Concurrent[ConnectionIO]` idea is bad and I feel bad
2. `WeakAsync.liftK` and probably `fromFuture` should not be public in current FS2
3. @mpilquist's idea of making a synchronous interrupt a no-op is an intriguing alternative

I'm closing this, but coming back with access modifiers if that third idea fizzles.
