### ISSUE TITLE
Remove Quill Integration Documentation from Doc site

### ISSUE THREAD

**Issue by ASRagab** [tpolecat/doobie#1591]
https://tpolecat.github.io/doobie/docs/17-Quill.html

While I don't necessarily support your actions, I do support your right to do it - it's your effort and project and yours is the only conscience with which you need make peace.  Perhaps worth removing in the near future, in case it might have slipped your mind.

**Comment by tpolecat** [comment]
Thanks, I need to push a new version of the website.

**Comment by ches** [comment]
I guess that the Quill integration is being dropped, is there a notice about this someplace? Or will upcoming release notes be the place for it?

**Comment by jatcwang** [comment]
Yep @ches I have added this to the release notes for the next 1.x RC release

**Comment by tpolecat** [comment]
done
