### ISSUE TITLE
specs2 check fails inappropriately under JOIN circumstances

### ISSUE THREAD

**Issue by kryptt** [tpolecat/doobie#164]
```
[info] Query0[User.ViewUserRoles] defined at user-queries.scala:87
[info]   SELECT r.id, r.code
[info]   FROM core.users u LEFT JOIN core.resource_roles(?) ur ON true
[info]   LEFT JOIN core.roles r ON ur.role_id = r.id
[info]   WHERE u.id = ?
[error]    x Non-nullable column ID is unnecessarily mapped to an Option type. (user-queries.scala:87)
[info] 
[info] x C09 code       VARCHAR   (varchar)    NOT NULL  →  Option[String]
[error]    x Non-nullable column CODE is unnecessarily mapped to an Option type. (user-queries.scala:87)
```

It happens that these columns can show up as null even though they are non-null at the table level since they come from a LEFT JOIN.

**Comment by tpolecat** [comment]
Interesting. I think I need to add a way to acknowledge and ignore warnings because the metadata mechanism isn't very accurate.

**Comment by refried** [comment]
Found this gem in the docs for `java.sql.DatabaseMetaData`.  Is that the API that doobie uses?

```
static short	attributeNoNulls   Indicates that NULL values might not be allowed.
static short	attributeNullable  Indicates that NULL values are definitely allowed.
```

"no nulls" means "maybe no nulls"

**Comment by tpolecat** [comment]
Ok, good catch. I'll update the checker to deal with this less aggressively.

**Comment by refried** [comment]
Would it be feasible to detect that it’s in a nullable position in the query?  I could believe that it isn’t.
