### ISSUE TITLE
Connections are held out of the pool unnecessarily when using fs2.Stream

### ISSUE THREAD

**Issue by AlexITC** [tpolecat/doobie#1645]
Let's take this piece of code:

```
      def f(a: fs2.Stream[cats.effect.IO, String], b: fs2.Stream[cats.effect.IO, String]): Unit =
        (a ++ b).map(println).compile.drain.unsafeRunSync()
```

Where `a` is a stream coming from the database, the connection required to get such a stream isn't released until `b` is consumed, producing a connection leak when `b` lasts for a very long time.

Then, if we add dummy finalizer, the connection is released as soon as `a` is consumed:

```
    def f(a: fs2.Stream[cats.effect.IO, String], b: fs2.Stream[cats.effect.IO, String]): Unit =
        (a.onFinalize(cats.effect.IO.unit) ++ b).map(println).compile.drain.unsafeRunSync()
```

I have prepared a [demo](https://github.com/AlexITC/doobie-fs2-connection-leak-demo) that demonstrates the behavior.

I do not know if this is the intended behavior but it is definitely a weird one.

Thanks.

**Comment by AlexITC** [comment]
Apparently, the doobie version being tested brings an old fs2 version which causes the issue ([context](https://discord.com/channels/632277896739946517/632310980449402880/937812553038442527).

Forcing `fs2 3.2.4` seems to solve the issue.

**Comment by jatcwang** [comment]
Thanks for the follow up @AlexITC :) I'll close this then.

**Comment by AlexITC** [comment]
For the record, the related fs2 issue is https://github.com/typelevel/fs2/pull/2614
