### ISSUE TITLE
Going from a PreparedStatementIO to an Analysis or Query0

### ISSUE THREAD

**Issue by kryptt** [tpolecat/doobie#167]
In order to test dynamically generated query strings, we need a better way to from: `(sql: String, ps: PreparedStatementIO[B])` to `Update0[B]`

**Comment by tpolecat** [comment]
Can you remind me why you need an `Update0`? You can get a `ConnectionIO` by saying `HC.prepareStatement(sql)(ps)` ... just trying to decide what's needed.

**Comment by tpolecat** [comment]
I think `Update` and `Query` will probably get reworked a bit in 0.3.0 so I'm going to push this off for now.

**Comment by kryptt** [comment]
Basically, I'm trying to get to something I can analyze (for unit testing against the DB structure)

**Comment by tpolecat** [comment]
You can now do this via `Fragment.const`.
