### ISSUE TITLE
Need an example of connection/thread pooling parity

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#168]
You generally want to run stuff on a thread pool with the same size as your connection pool, which is trivial using `Transactor[Task]` but there is no example given. It might be nice to roll this idea into `Transactor` itself.

**Comment by jatcwang** [comment]
As of [1.0.0-RC3](https://github.com/tpolecat/doobie/releases/tag/v1.0.0-RC3) we help create a connect EC which is the same size as the pool
