### ISSUE TITLE
postgres session variables

### ISSUE THREAD

**Issue by ohuu** [tpolecat/doobie#1696]
I'm using doobie with postgres and I'm trying to set a session variable like this:

```scala
def as(id: Int): ConnectionIO[Int] = sql"select set_config('auth.id', '${id}', false)".query[Int].unique
```

But it fails. If I catch the exception using `handleError` I get this message

```
The column index is out of range: 1, number of columns: 0.
```

running the query in psql works fine so I'm not sure what's happening here

**Comment by jatcwang** [comment]
@ohuu 
Haven't used set_config myself but I think I might know what's wrong:

I see that you're trying to convert an int into a string, but what you want to do is treat every interpolated variable as `?` (that's what doobie really does under the hood)

So what you currently are sending to postgres is `select set_config('auth.id', '?', false)`. Instead, you want to do this:

`sql"select set_config('auth.id', ${id} :: text, false)".query[Int].unique` which translates to the actual SQL `select set_config('auth.id', ? :: text, false)`. I think this is why you got an error from Postgres as it didn't detect any placeholder in your SQL query.

I'm also not sure what set_config returns, you might need to change from `.query[Int]` to `.query[String]` as the doc seems to suggest that all config values are strings.

**Comment by ohuu** [comment]
thanks @jatcwang I actually changed the `userId` parameter to a `String` and return a `Unit` and it's now working.

```scala
def as(userId: String): ConnectionIO[Unit] =
    sql"select set_config('auth.id', $userId, false)".query[Unit].unique
```
