### ISSUE TITLE
Is there a way to return `select` as a circe json object?

### ISSUE THREAD

**Issue by lanyusan** [tpolecat/doobie#1699]
I have worked with both Clojure and Scala. While Scala's type system is powerful but when it comes to working with database and in my particular case a startup project where data structure and even business model are constantly changing, we often change sql query, it is painful to redefine data structure every time a slight change when using scala, especially we use postgres and jsonb a lot. Jsonb fields are fluid too. While with Clojure, `select` would return a map object, and jsonb objects would have been parsed correctly too. With clojure, we use [next.jdbc](https://github.com/seancorfield/next-jdbc) which is a joy to use.

I am wonderring if it is possible to just return `select` as a generic circe json object with json / jsonb fields automatically parsed.

I understand it is not ideal and could have broken the advantage of type safe sql query but in some cases it is really a production boost.

I have tried to use doobie and Scala on this new project for a couple of weeks. I found everything smooth except the point I mentioned above.

Just a thought. Thanks in advance.+

**Comment by satorg** [comment]
Not sure if it is what you're looking for, but...

if you build your select query up such that it will be converting the data you're interested in into JSON/JSONB (see [link1](https://www.postgresql.org/docs/14/functions-json.html)) or aggregating into JSON/JSONB (see [link2](https://www.postgresql.org/docs/14/functions-aggregate.html)), then yes – you can get the results out of the query in a form of Circe's `Json` type (via the `postgres-circe` module).

For example, consider the following table (with some data inserted):
```sql
CREATE TABLE IF NOT EXISTS public.foobar
(
    id bigint PRIMARY KEY,
    foo text NOT NULL,
    bar integer NULL
);

INSERT INTO foobar(id, foo, bar)
VALUES (1, 'AAA', 123),
       (2, 'BBB', null),
       (3, 'CCC', 456);
```
So now you can query this data in the following way:
```scala
sql"SELECT row_to_json(foobar) FROM foobar"
  .query[Json]
  .to[List]
  ... // and so on
```
Therefore in this way you can get all the data from your table as a collection of `Json` objects.

**Comment by lanyusan** [comment]
Yes. I have tried it and it works. that is what I wanted. thanks

A further question. Postgres allows `update ... return a,b,c` in update / delete query. Doobie use `withGeneratedKeys` to return rows/row on update / delete.

Is there a way to return Json as well using `withGeneratedKeys` as I don't see a way to use `row_to_josn` with `withGeneratedKeys`.

Thanks again.

**Comment by satorg** [comment]
Let me show here a complete example with generated keys involved:
```scala
import io.circe.Json
import doobie._
import doobie.implicits._
import doobie.postgres.circe.json.implicits._

val transactor: Transactor[IO] = ??? // whatever...

val createTableSql =
  sql"""|CREATE TEMP TABLE foobar
        |(
        |    id bigint PRIMARY KEY,
        |    foo text NOT NULL,
        |    bar integer NULL
        |)
        |""".stripMargin

val insertValuesSql =
  sql"""|INSERT INTO foobar(id, foo, bar)
        |VALUES (1, 'AAA', 123),
        |       (2, 'BBB', null),
        |       (3, 'CCC', 456)
        |RETURNING row_to_json(foobar) AS inserted_data;
        |""".stripMargin

val updateValueSql =
  sql"""|UPDATE foobar
        |SET bar = 789
        |WHERE foo = 'BBB'
        |RETURNING row_to_json(foobar) AS updated_data;
        |""".stripMargin

val selectValuesSql =
  sql"SELECT row_to_json(foobar) FROM foobar"

val (insertedData, updatedData, selectedData) =
  (for {
    _ <- createTableSql.update.run
    insertedData <- insertValuesSql.update.withGeneratedKeys[Json]("inserted_data").compile.toList
    updatedData <- updateValueSql.update.withUniqueGeneratedKeys[Json]("updated_data")
    selectedData <- selectValuesSql.query[Json].to[List]
  } yield (insertedData, updatedData, selectedData))
    .transact(transactor)
    .unsafeRunSync() // just for the sake of the demo!

println(s"inserted: ${Json.fromValues(insertedData).noSpaces}")
println(s"updated : ${updatedData.noSpaces}")
println(s"selected: ${Json.fromValues(selectedData).noSpaces}")
```
This one should print something like the following:
```
inserted: [{"id":1,"foo":"AAA","bar":123},{"id":2,"foo":"BBB","bar":null},{"id":3,"foo":"CCC","bar":456}]
updated : {"id":2,"foo":"BBB","bar":789}
selected: [{"id":1,"foo":"AAA","bar":123},{"id":3,"foo":"CCC","bar":456},{"id":2,"foo":"BBB","bar":789}]
```
---
Note that basically you can use `to_json` or `to_jsonb` instead of `row_to_json` (see the difference in the PostgreSQL docs). Working with `JSONB` instead of `JSON` you may like to import
```
import doobie.postgres.circe.jsonb.implicits._
```
instead of
```
import doobie.postgres.circe.json.implicits._
```
Although the latter should work in any case too.

**Comment by lanyusan** [comment]
I see. thanks. Though it  requires some level of sql skills but it works.

**Comment by jatcwang** [comment]
I guess this is resolved :+1:
