### ISSUE TITLE
Is there a way to provide catalog, schema to the connection string?

### ISSUE THREAD

**Issue by wpoosanguansit** [tpolecat/doobie#170]
Hi,

I am trying to use doobie with Trafodion database which requires me to pass in catalog and schema string to its connection.  Right now, I am getting:

org.trafodion.jdbc.t4.HPT4Exception: *** ERROR[4082] Object TRAFODION.SEABASE.T_TABLE does not exist or is inaccessible. [2015-06-02 13:43:13]
  at org.trafodion.jdbc.t4.HPT4Messages.throwSQLException(HPT4Messages.java:206)
  at org.trafodion.jdbc.t4.InterfaceStatement.prepare(InterfaceStatement.java:1115)
  at org.trafodion.jdbc.t4.TrafT4PreparedStatement.prepare(TrafT4PreparedStatement.java:2234)

While a simple JDBC would connect and execute fine.  And the only differences I found are the two values which I still do not know how to provide with doobie.  Thanks for your help.

**Comment by tpolecat** [comment]
Shouldn't be a problem. How would you do this in JDBC, and what are you trying in doobie?

**Comment by wpoosanguansit** [comment]
Thanks for your help.  In a normal JDBC set, we have to provide something like this as the connection string:

trafodion {
  catalog   = "namespace"
  schema    = "s"
  url       = "jdbc:t4jdbc://localhost/:"
  user      = "user"
  password  = ""
  driver    = "org.trafodion.jdbc.t4.T4Driver"
}

The only thing that I see that I am not passing in are the catalog and schema.  So I am guessing the two are the things that different between the two.  Appreciate your help.

**Comment by tpolecat** [comment]
Hm that's not a typical connection string. Who consumes it?

**Comment by wpoosanguansit** [comment]
I believe it is trafodion.  The connection string is from the example I got from their sample tutorial which works for the simple create and delete I tested.

**Comment by tpolecat** [comment]
Ok it looks like you need to use `getConnection(String url, Properties info)` passing a `java.util.Properties` containing the key/value pairs as is done [here](https://github.com/trafodion/core/blob/master/conn/jdbc_type4/samples/common/sampleUtils.java#L109). Right now `DriverManagerTransctor` doesn't support this, but you can write your own transactor that does. Something like:

```scala
import doobie.imports._
import scalaz._,Scalaz._
import java.util.Properties
import java.sql.Connection

object PropsTransactor {
  import doobie.free.drivermanager.{ delay, getConnection }
  def apply[M[_]: Monad: Catchable: Capture](driver: String, url: String, props: Properties): Transactor[M] =
    new Transactor[M] {
      val connect: M[Connection] =
        (delay(Class.forName(driver)) *> getConnection(url, props)).trans[M]      
    }
  }
```

Which you would then call as

```scala

import scalaz.concurrent.Task

val props = new java.util.Properties

props.put("catalog", "namespace")
props.put("schema", "s")
props.put("user", "user")
props.put("password", "")

val xa = PropsTransactor[Task]("org.trafodion.jdbc.t4.T4Driver", "jdbc:t4jdbc://localhost/:", props)
```

Give this a try.

**Comment by tpolecat** [comment]
Note to self: add these constructors to `DriverManagerTransactor`.

**Comment by wpoosanguansit** [comment]
I will try that.  Thank you for your help!

**Comment by tpolecat** [comment]
I'd like to keep this open so I can remember to add new constructors to `DriverManagerTransactor`.
