### ISSUE TITLE
withGeneratedKeys generates corrupting double quotes in query

### ISSUE THREAD

**Issue by SebastianNieke** [tpolecat/doobie#1734]
In a postgres database I try to update a table based on information of another table and want to return a value from all updated rows. So I use the `UPDATE ... FROM ... RETURNING ...` syntax.
The way to go with doobie to get those values from the query is `.withGeneratedKeys`:

```
sql"""| UPDATE products p
      | SET productnumber = map.productnumber
      | FROM migration_mapping map
      | WHERE map.productnumber_old = p.productnumber
      |   AND p.category = $productCategory
      |""".stripMargin
  .update
  .withGeneratedKeys[ProductNumber]("p.productnumber")
  .compile
  .toList
```

This `.withGeneratedKeys` generates double quotes around the given columns:

```
UPDATE products p
SET productnumber = map.productnumber
FROM migration_mapping map
WHERE map.productnumber_old = p.productnumber
  AND p.category = 'books'
RETURNING "p.productnumber";

-- column »p.productnumber« does not exist
```

In most cases this should be ok, at least with postgres. But in cases like this where the table name (or alias) is included it breaks the query.
For postgres double quotes around the column is fine, as well as around the table or around the table and around the column. But not around both.
These double quotes are wrong in any case on other databases (at least those I tried: mysql, h2):

```
-- postgres:
SELECT l."productnumber" FROM list l; -- works
SELECT "l".productnumber FROM list l; -- works
SELECT "l"."productnumber" FROM list l; -- works
SELECT "l.productnumber" FROM list l; -- "l.productnumber" interpreted as column name (not table + column)

-- mysql:
SELECT l."productnumber" FROM list l; -- syntax failure
SELECT "l".productnumber FROM list l; -- syntax failure
SELECT "l"."productnumber" FROM list l; -- syntax failure
SELECT "l.productnumber" FROM list l; -- "l.productnumber" interpreted as string literal

-- h2:
SELECT l."productnumber" FROM list l; -- Column "L.productnumber" not found
SELECT "l".productnumber FROM list l; -- Column "l.PRODUCTNUMBER" not found
SELECT "l"."productnumber" FROM list l; -- Column "l.productnumber" not found
SELECT "l.productnumber" FROM list l; -- Column "l.productnumber" not found
```

I don't suppose the queries for other databases are all broken when this feature is used, so this seems to be a postgres-related issue.

**Comment by jatcwang** [comment]
Alternatively I think you can do `fr"INSERT INTO .... RETURNING some_id".query[UUID]`.
