### ISSUE TITLE
Can't derive Meta instances generically.

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#178]
The `TypeTag` requirement for `Meta` means you can't usefully derive generic instances implicitly; in the case below `taggedIdMeta` doesn't work implicitly and must be invoked for each concrete type. So maybe come up with a better way to do this.

/cc @refried 

``` scala
import scalaz.{@@, Tag}, doobie.imports._
import scala.reflect.runtime.universe.TypeTag
import shapeless._

type Id = Int

def taggedIdMeta[T](implicit tt: TypeTag[Id @@ T]): Meta[Id @@ T] =
  Meta[Int].xmap(Tag.apply[Id,T], Tag.unwrap[Id,T])

trait Attachment

implicit val AttachmentIdMeta = 
  taggedIdMeta[Attachment]

Composite[Id @@ Attachment]
Composite[(Id @@ Attachment) :: HNil]
```

**Comment by refried** [comment]
This probably sounds silly, but would adding Typetag in more places help? Or strictly make things worse? :)

**Comment by tpolecat** [comment]
Nah I'm definitely not doing that ;-)

**Comment by refried** [comment]
Or maybe have two versions of xmap and save an Option[TypeTag] for diagnostics when practical?

**Comment by tpolecat** [comment]
This is going away with the tsql API so I'm closing this.
