### ISSUE TITLE
Deriving Read/Write with a list for a multi-element case class fails

### ISSUE THREAD

**Issue by draescherl** [tpolecat/doobie#1790]
I have the following case classes:

```scala
case class Actor(
    id: UUID,
    firstName: String,
    lastName: String)

case class Movie(
    id: UUID,
    title: String,
    actors: List[Actor])
```

I have `import doobie.implicits._`, `import doobie.postgres._` and `import doobie.postgres.implicits._` imported so I would expect it to work.

Instead I get a compilation error: 

```
Cannot find or construct a Read instance for type:

  models.movie.Movie
```

I have tried the following:
- :heavy_check_mark:  `Read[Actor]` 
- :x: `Read[List[Actor]]` 
- :x: `Get[List[Actor]]` 

Is this intended behaviour or am I doing something wrong?

**Comment by jatcwang** [comment]
@draescherl  What does your DB column data look like? how do you plan to get a `List[Actor]` from each column value?

**Comment by draescherl** [comment]
The database schema:

```sql
CREATE TABLE actors (
     actor_id uuid PRIMARY KEY,
     first_name VARCHAR NOT NULL,
     last_name VARCHAR NOT NULL
 );
 
 CREATE TABLE movies (
     movie_id uuid PRIMARY KEY,
     title VARCHAR NOT NULL
 );
 
 CREATE TABLE actors_movies (
     actor_id uuid CONSTRAINT fk_actors_movies_actor_id REFERENCES actors (actor_id),
     movie_id uuid CONSTRAINT fk_actors_movies_movie_id REFERENCES movies (movie_id),
     PRIMARY KEY (actor_id, movie_id)
 );
```

The query:

```sql
SELECT m.movie_id,
        m.title,
        array_agg(a.*) AS actors
 FROM movies AS m
          JOIN actors_movies am ON m.movie_id = am.movie_id
          JOIN actors a ON am.actor_id = a.actor_id
 GROUP BY m.movie_id, m.title;
```

**Comment by draescherl** [comment]
No problem. Is that something you plan on supporting in the future?

**Comment by jatcwang** [comment]
Given that in Postgres array elements must all have the same type, I feel like the use cases are quite narrow so probably not worth it.
Perhaps you can convert into a JSON array and parse from that instead?

Something like this:

```
SELECT m.movie_id,
        m.title,
        json_agg(to_json(a.*)) AS actors
 FROM movies AS m
          JOIN actors_movies am ON m.movie_id = am.movie_id
          JOIN actors a ON am.actor_id = a.actor_id
 GROUP BY m.movie_id, m.title;
```

Doobie integrates with Circe via the [doobie-postgres-circe](https://mvnrepository.com/artifact/org.tpolecat/doobie-postgres-circe) module, so once you have a `Decoder[List[Actor]]` instance you can call `implicit actorGet: Get[Actor] = doobie.postgres.circe.json.implicits.pgDecoderGet[Actor]`
