### ISSUE TITLE
doobie-specs2 for Scala 3

### ISSUE THREAD

**Issue by george-wilson-rea** [tpolecat/doobie#1797]
Hi Doobie, I'm using 1.0.0-RC2 in a project, and I would love to upgrade to Scala 3. At this stage, the only dependency I have that's holding me back is `doobie-specs2`, which doesn't have a release for Scala 3.
Could you please publish doobie-specs2 1.0.0-RC2 for Scala 3, or otherwise please do so in 1.0.0-RC3?

Is there a plan for cross-scala-version specs2 support for doobie going forward? It looks like Erik intends to keep the `4.x` series going for this purpose. (https://github.com/etorreborre/specs2/issues/1117) so we could potentially just follow those releases in doobie.

**Comment by armanbilge** [comment]
This issue is already addressed, you can use the snapshots of this artifact.

https://s01.oss.sonatype.org/content/repositories/snapshots/org/tpolecat/doobie-specs2_3/

All that's needed is for a published v1.0.0-RC3 (or final :)

**Comment by george-wilson-rea** [comment]
HI @armanbilge is v1.0.0-RC3 going to happen any time soon? Or even just a build of doobie-specs2 RC2 for Scala 3 would be really helpful. I am hesitant to depend on snapshots.

**Comment by jatcwang** [comment]
RC3 will be released soon so closing
