### ISSUE TITLE
Merge outstanding Scala Steward PRs

### ISSUE THREAD

**Issue by george-wilson-rea** [tpolecat/doobie#1798]
There are a few PRs open on doobie right now. Some of them clearly require careful review, but is there anything stopping us from merging some of the open Scala Steward PRs? They look pretty harmless to me.

**Comment by jatcwang** [comment]
Let me try to update the mergify config (#1799) to see if we can get auto-merging to work again

**Comment by jatcwang** [comment]
Ok the mergify matching rules are a bit tricky so I've created https://github.com/tpolecat/doobie/issues/1801 (Hopefully easy to switch over)

**Comment by george-wilson-rea** [comment]
Thank you!

**Comment by jatcwang** [comment]
Mergify setup is done in #1810

**Comment by george-wilson-rea** [comment]
Fantastic! It's so satisfying to see all the recently merged PRs :)
