### ISSUE TITLE
Generic derivation failing for simple case class

### ISSUE THREAD

**Issue by noelwelsh** [tpolecat/doobie#1829]
The following simplified example of generic derivation of `Read` instances is failing with `null` in my project.

```scala
import doobie.Read
import org.scalatest.funsuite.AnyFunSuite

final case class Wrapped(value: Int)
object Wrapped {
  implicit val wrappedRead: Read[Wrapped] = Read[Wrapped]
}

class NPESpec extends AnyFunSuite {
  test("value read") {
    assert(Wrapped.wrappedRead != null, "Wrapped is null")
  }
}
```

This seems to be relatively new to Doobie. I'm working on updating an old project, where generic derivation worked, to Doobie 1.0-RC2 (Scala 2.13.10) and encountered the above.

**Comment by jatcwang** [comment]
Seems like `Read[Wrapped]` is resolving to itself (wrappedRead) which is why it's null?
Using `Read.fromGet` works for me (or Read.generic for multi-column case classes).

Can you tell me which Scala version & doobie version you were upgrading from?

Scala-cli:
```
//> using scala "2.13.10"
//> using lib "org.tpolecat::doobie-core:1.0.0-RC2"

import doobie.Read

final case class Wrapped(value: Int)
object Wrapped {
  implicit val wrappedRead: Read[Wrapped] = Read.fromGet[Wrapped]
}

object Main {
  def main(args: Array[String]) = {
    println("hi")
    println(Wrapped.wrappedRead == null)
  }
}

```

**Comment by jatcwang** [comment]
Let me know if there are other examples which isn't explained by my example.
