### ISSUE TITLE
How to define isolation level for a specific transaction ?

### ISSUE THREAD

**Issue by mantovani** [tpolecat/doobie#1837]
How to specify the isolation level for a specific transaction ?

I would like to change the default isolation level just for the following transaction:

```scala
val transaction = for { 
_ <- sql"...".query[_].unique
t <- sql"...".query[_].unique
} yield (t)
transaction.transact(xa).unsafeRunSync()
```

**Comment by satorg** [comment]
You can adjust `Transactor` instance for your needs as described in the docs:
https://tpolecat.github.io/doobie/docs/14-Managing-Connections.html#customizing-transactors

So in your case you may come up with something like that:
```scala
val xa1 =
  Transactor.before.modify(
    xa,
    _ *> HC.setTransactionIsolation(TransactionIsolation.TransactionSerializable)
  )
```
then use the `xa1` instance instead of `xa` in your query.
It won't affect other queries that keep using the original `xa` instance.

Disclaimer: I've never tried to do exactly this manipulation, so I'm not sure that it is the best way to achieve that.
But I did try to manipulate transactions some other ways, so I think it might work for your case.

**Comment by mantovani** [comment]
> You can adjust `Transactor` instance for your needs as described in the docs: https://tpolecat.github.io/doobie/docs/14-Managing-Connections.html#customizing-transactors
> 
> So in your case you may come up with something like that:
> 
> ```scala
> val xa1 =
>   Transactor.before.modify(
>     xa,
>     _ *> HC.setTransactionIsolation(TransactionIsolation.TransactionSerializable)
>   )
> ```
> 
> then use the `xa1` instance instead of `xa` in your query. It won't affect other queries that keep using the original `xa` instance.
> 
> Disclaimer: I've never tried to do exactly this manipulation, so I'm not sure that it is the best way to achieve that. But I did manipulate transactions some other ways, so I think it might work in your case.

Today I'm just doing: 

```sql
start transaction isolation level serializable ;
```

I was wondering if Doobie provided an idiomatic way to do it.

**Comment by optician** [comment]
This works for me:
```scala
HC.setTransactionIsolation(TransactionIsolation.TransactionRepeatableRead) *>
myRequests <*
sql"""SHOW TRANSACTION ISOLATION LEVEL;""" .query[String].unique.map(trx => println(s"transaction isolation level $trx"))
```
prints "transaction isolation level repeatable read"

With this it's possible to write a test that checks level.

**Comment by jatcwang** [comment]
You can also use the lower level API (which maps 1:1 to JDBC API) if you need to set the isolation level using an int: 

```
import doobie.FC
val transaction: ConnectionIO[Something] = for { 
  _ <- sql"...".query[_].unique
  t <- sql"...".query[_].unique
} yield (t)

(FC.setTransactionIsolation(4) *> transaction).transact(transactor)
```
