### ISSUE TITLE
writing mapping instances to/from a Scala 3opaque type results in infinite loop in function body

### ISSUE THREAD

**Issue by imgulyas** [tpolecat/doobie#1854]
At the moment I'm using Scala 3.3.0 and Doobie version 1.0.0-RC2.

To reproduce the issue:
```
opaque type Alias = Int

object Alias {
  def apply(id: Int): Alias = id

  extension (a: Alias) {
    def toInt: Int = a
  }

  given doobie.util.meta.Meta[Alias] = doobie.util.meta.Meta[Int].imap(Alias(_))(_.toInt)
}
```

Error:
```
Infinite loop in function body
doobie.util.meta.Meta.apply[Int](
  cz.invia.importer.service.giata.Alias.given_Meta_Alias).imap[
  cz.invia.importer.service.giata.Alias](
  {
    def $anonfun(_$3: cz.invia.importer.service.giata.GiataId$package.Alias):
      cz.invia.importer.service.giata.Alias =
      cz.invia.importer.service.giata.Alias.apply²(_$3)
    closure($anonfun)
  }
)(
  {
    def $anonfun²(_$4: cz.invia.importer.service.giata.Alias):
      cz.invia.importer.service.giata.GiataId$package.Alias =
      cz.invia.importer.service.giata.Alias.toInt(_$4)
    closure($anonfun²)
  }
)

where:    $anonfun  is a method in the initializer of given instance given_Meta_Alias
          $anonfun² is a method in the initializer of given instance given_Meta_Alias
          apply     is a method in object Meta
          apply²    is a method in object Alias

  given doobie.util.meta.Meta[Alias] = doobie.util.meta.Meta[Int].imap(Alias(_))(_.toInt)

```

**Comment by jatcwang** [comment]
Feel like this may be more of an opaque type / given issue than doobie issue? 

* What happens when you move the given instance out of the companion object?
* Another possibility is something to do with the name `toInt` (which a method on `Int` as well). What happens if you name it something else?

**Comment by jatcwang** [comment]
@imgulyas Thinking about it more I think this might be the typical "implicit def resolved to itself".
It's not very obvious, but I think when you try to summon `Meta[Int]` it might've been resolving to itself (the `given Meta[Alias]` because within the companion object Alias =:= Int.

If you use `Meta.IntMeta.imap(..)` do you still get the same issue?

**Comment by imgulyas** [comment]
Actually calling it with IntMeta solved it, thank you.  
But it kept bugging me, because does that mean if the implicit/given instance doesn't have a name, you are out of luck? In Scala 3 you don't have to give a name to the given value and I for example usually don't name them. 

>  "implicit def resolved to itself"  

It seems like that was the case. Now I get it why you wanted me to move the given instance out of the companion object! 

>   in the companion object Alias =:= Int  

Actually, because the type definition was a top level in that source file, so it turned out Alias =:= Int was true in the whole file, not just in the companion object and moving the given definition to another file makes it work with a normal summon of Meta[Int].  

Unfortunately, that approach means the given instance is not found automatically by the compiler without an import.

**Comment by matil019** [comment]
I've experienced a similar issue several times, and found this workaround (or perhaps _the_ solution?) satisfactory:

```scala
given (using underlying: doobie.util.meta.Meta[Int]): doobie.util.meta.Meta[Alias] = underlying.imap(Alias(_))(_.toInt)
```

or, more simply:

```scala
given (using underlying: doobie.util.meta.Meta[Int]): doobie.util.meta.Meta[Alias] = underlying
```

This is helpful if the desired given instance doesn't have a name (such as `Meta.IntMeta`).

**Comment by jatcwang** [comment]
Thanks for the tip matil019. Yeah I think this is really an issue with the design of opaque types leading to these kind of foot guns :/
