### ISSUE TITLE
Consideration for FS2 Version Upgrade & New Doobie Release

### ISSUE THREAD

**Issue by cosmir17** [tpolecat/doobie#1855]
I hope this message finds you well. I am reaching out to kindly bring to your attention that the current Cats Effect 3.5.0 in the master branch appears to necessitate FS2 Version 3.7.0, as indicated in the release notes.

I've observed that the FS2 version in Doobie's master branch is presently at 3.6.1.

I completely understand and greatly appreciate the enormous effort and time you all dedicate to maintaining this open-source project voluntarily. If it aligns with your plans and capacity, would you kindly consider updating FS2 to version 3.7.0 and possibly releasing a new version of Doobie? It's been around 1 year and 5 months since the last update, and many users would undoubtedly benefit from these enhancements.

Once again, thank you for all the wonderful work you've been doing. We truly value your commitment to this project.

**Comment by jatcwang** [comment]
@cosmir17 Thanks for bringing this to my attention. We still have work that I think needs to be done for RC3 (https://github.com/tpolecat/doobie/milestone/11). The main issue is that if we release as is from `main` branch it'll cause a few issues to users trying to migrate. I'm trying to chip away at it any chance I get & with help from many others. Please bear with me :)

**Comment by cosmir17** [comment]
Hello @jatcwang,

Thank you for your swift response and for shedding light on the tasks ahead for RC3. I certainly understand the challenges in maintaining a project of such magnitude and greatly appreciate your efforts.

I've checked the milestone link you provided and observed a multitude of issues and pull requests being actively managed. However, I couldn't locate an issue or PR specifically pertaining to the FS2 version upgrade to 3.7.0.

Given that you already have Cats Effect 3.5.0 PR merged on the milestone list (`closed`), requires this FS2 version according to [the release note](https://github.com/typelevel/cats-effect/releases/tag/v3.5.0), it would be great if this upgrade could be considered in your roadmap. This would greatly facilitate users who are migrating and aiming for compatibility with Cats Effect 3.5.0.

Once again, thank you for your time and dedication. We truly appreciate your effort in maintaining this project.

**Comment by jatcwang** [comment]
Hi @cosmir17 I've raised #1856. Sorry I thought scala-steward would already have raised a PR for it and I missed that you pointing it out that current fs2 version is at 3.6.1.

**Comment by jatcwang** [comment]
@cosmir17 fs2 upgraded in https://github.com/tpolecat/doobie/pull/1858/files
