### ISSUE TITLE
Is this library still actively being developed?

### ISSUE THREAD

**Issue by aaronmarshallrea** [tpolecat/doobie#1871]
Yeah g'day!

Long time user of doobie - I use it a lot day-to-day, and think that it offers a lot in terms of features and safety.

Having said that, I (I'm sure like many others) have been on a spiritual journey as of late to upgrade a lot of codebases I work on to Scala 3. One blocker to this has been an absence of a Scala 3 full release of Doobie (and doobie-specs2 doesn't support scala 3 yet that I'm aware of).

Doobie has been on Release Candidate (RC) 2 for more than a year, there are infrequent meaningful changes being integrated into the primary branch, and most of the recent changes have been scala steward updates.

I'm curious if there is an intention to continue developing doobie, or if this is no longer a priority?

**Comment by jatcwang** [comment]
Hi @aaronmarshallrea we're aiming for a RC3 release this week :) Sorry for the wait because life's been busy. It's a slow push to 1.0 for sure and help would be appreciated if it interests you. https://github.com/tpolecat/doobie/issues/1728

**Comment by aaronmarshallrea** [comment]
Thank you for the clarification! Much appreciated. Any ideas on when a non-RC release might be on the way? 🙏 

Also - nothing to apologise for mate. I'm thankful for the work that has been put in!

**Comment by jatcwang** [comment]
Snapshots are of the form `1.0-2550ebb-SNAPSHOT` and you might need to add `resolvers ++= Opts.resolver.sonatypeOssSnapshots` for SBT
