### ISSUE TITLE
Cats-Effect 3.5.0?

### ISSUE THREAD

**Issue by alexandru** [tpolecat/doobie#1873]
Hi all,

It's not clear to me if the latest released RC is compatible with Cats-Effect 3.5.0.

Any experiences with the upgrade? Anything to do for a new release?

Thanks,

**Comment by jatcwang** [comment]
Hi @alexandru you can check out https://github.com/tpolecat/doobie/pull/1851
We have updated to fs2 3.7.0 too.

**Comment by alexandru** [comment]
Great. Can we have a release?

**Comment by jatcwang** [comment]
Some final touches are being worked on but for now you can use snapshots to test it out on your codebase https://github.com/tpolecat/doobie/issues/1871#issuecomment-1592657657
