### ISSUE TITLE
LogHandler does not capture streaming queries or bulk updates

### ISSUE THREAD

**Issue by soujiro32167** [tpolecat/doobie#1888]
Scala: 2.13.11
Doobie: 1.0.0-RC4
Postgres: 14.3

Repro: 

```scala
import cats.effect.{ExitCode, IO, IOApp}
import doobie.implicits.*

object Repro extends IOApp{
  val xa = Transactor.fromDriverManager[IO](
    driver = "org.postgresql.Driver",
    url = "jdbc:postgresql:postgres",
    user = "postgres",
    password = "postgres",
    logHandler = Some(LogHandler.jdkLogHandler)
  )

  def run(args: List[String]): IO[ExitCode] = for {
    _ <- sql"SELECT 1".query[Int].unique.transact(xa) // this gets logged
    _ <- sql"SELECT 1".query[Int].stream.compile.lastOrError.transact(xa) // this doesn't
    _ <- Update[Int]("SELECT ?").updateMany(List(1)).transact(xa) // this doesn't
  } yield ExitCode.Success
}
```

**Comment by satorg** [comment]
I think it is related to (or maybe duplicates) #772.

**Comment by soujiro32167** [comment]
😱

**Comment by soujiro32167** [comment]
from https://github.com/tpolecat/doobie/issues/772#issuecomment-420791244
> It may be worthwhile to go ahead and add a Log constructor to each Free algebra so we can plumb this in from the bottom

It looks like RC3 did exactly that - there is now a `PerformLogging` in every algebra, so it seems. Anything I can help with?

**Comment by jatcwang** [comment]
For `stream` it shouldn't be too hard to plumb the SQL, args and label through. For updateMany it's a bit weirder but if we log only the first set of `args` then it'll work too (though imperfect)

**Comment by jatcwang** [comment]
From #533, seems like `withGeneratedKeys` has the same problems

**Comment by jatcwang** [comment]
Please give 1.0-RC6 a try when it's released which should fix this issue
