### ISSUE TITLE
Transactor constructors in 2 effects

### ISSUE THREAD

**Issue by lgmyrek** [tpolecat/doobie#1902]
With the introduction of LogHandler[M] initializing Transactor[M] and then transforming it into Transactor[M0] in some contextual M0 is no longer as feasible as we want LogHandler to be in M0.

so it would be nice to have sth like:

```scala
  def fromHikariConfig2K[
    M[_]: Sync,
    M0[_]: Async
  ](
    hikariConfig: HikariConfig,
    logHandler: Option[LogHandler[M0]] = None
  ): Resource[M, HikariTransactor[M0]] =
  for {
    _ <- Sync[M].delay(hikariConfig.validate()).toResource
    
    ...
```

**Comment by jatcwang** [comment]
I mostly use concrete effect types so it didn't cross my mind but happy to review a PR with this change :)

**Comment by satorg** [comment]
Hi @lgmyrek , I wonder if the `mapK` method in `Transactor` could help you with that:
```scala
HikariTransactor.fromHikariConfig[M](...).map(_.mapK(liftMtoM0))
```
..if I'm not missing something from your question..

**Comment by lgmyrek** [comment]
@jatcwang sure, any naming preferences? 😄 

@satorg it did help me when there was no LogHandler, let's say M0 has request-id, spans, and other contextual things, the only way I can make use of those in LogHandler is when LogHandler is impelemnted being aware of those.

I could initialize the transactor in M0 and mapK the resource to M, but that would mean I need to provide some `fake context` and that is quite hacky

**Comment by satorg** [comment]
@lgmyrek , thank you for the explanation. I think I got your case. I feel you could still make use of `mapK`, even though in a slightly different way:
1. construct you `Transactor` in `M` as usual without any `LogHandler` attached:
    ```transM <- fromHikariConfig[M](..., logHandler = None)```
2. at the point where you have your `M0` ready (along with your `LogHandler[M0]`),
   - lift your `Transactor[M]` into `M0`:
     ```
      val transM0 = transM.mapK(liftMtoM0)
      ```
   - then inject your `LogHandler[M0]` into `transM0`:
       ```
       val logHandler: LogHandler[M0] = ???
       val transM0final: Transactor[M0] = transM0.copy(interpret0 = KleisliInterpreter[M0](logHandler).ConnectionInterpreter)
       ```
Yeah, I know – looks a bit hairy :)

But perhaps it would be way easier if we would have a method in `Transactor` like
```
def setLogHandler(logHandler: LogHandler[M]): Transactor.Aux[M, A]
```

**Comment by lgmyrek** [comment]
@satorg yes, alongside several other ways to achieve it.
But when you would have to do it 20+ times in several projects it hardly seems reasonable, I would like to avoid other people,  e included creating some internal libs which only purpose is utility methods to initialize doobie which surely can happen in big enough systems

**Comment by satorg** [comment]
Well, in a real code, when everything is up and handy, the transition could look as simple as
```
transM.mapK(liftToM0).setLogHandler(logHandler)
```

I just feel that a single method like `setLogHandler` could cover more various use-cases.
For example, when someone does not need switching between M and M0 in their transactor, but rather wants to setup different LogHandlers in different parts of their code. Currently the only way to differentiate services from each other is to pass an appropriate `label`. Which is cool, but not always enough. Therefore having such a method looks a bit more generic approach to me.

But of course, it won't harm to have even both approaches incorporated eventually. I believe they could nicely complement each other after all.
