### ISSUE TITLE
Issues with compatibility with Monix

### ISSUE THREAD

**Issue by joesan** [tpolecat/doobie#1911]
I'm having a project where I have Monix 3.x as a dependency. I'm building the database layer for my application and would like to try out doobie and I added them as dependencies, like below:

```
      "org.tpolecat" %% "doobie-core"     % DoobieVersion, // 1.0.0-RC4
      "org.tpolecat" %% "doobie-postgres" % DoobieVersion,
      "org.tpolecat" %% "doobie-h2" % DoobieVersion,
      "org.tpolecat" %% "doobie-hikari"   % DoobieVersion,

      // Threading & Streaming libraries (https://monix.io/docs/current/intro/usage.html)
      "io.monix" %% "monix-reactive" % "3.4.0",
```

When I compile my app, I run into an error that gets my confusing:

```
Symbol 'type cats.effect.Effect' is missing from the classpath.
[error] This symbol is required by 'class monix.eval.instances.CatsEffectForTask'.
[error] Make sure that type Effect is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'CatsEffectForTask.class' was compiled against an incompatible version of cats.effect.
```

It complains this exactly at the place where I'm instantiating a service by using Task from Monix. How do I fix this? I suspect it is some cats compatibility issue. Any help might be appreciated.

**Comment by jatcwang** [comment]
Unfortunately Monix is currently still on cats-effect 2 so it won't work with doobie.

(Highly recommend using Cats-effect 3 instead of Monix, as the latter isn't very actively developed these days)
