### ISSUE TITLE
Getting error in repl.

### ISSUE THREAD

**Issue by wpoosanguansit** [tpolecat/doobie#192]
I am not sure if the steps I took were correct:

scala> import doobie.imports._, scalaz._, Scalaz._, scalaz.concurrent.Task
scala> import doobie.util.yolo._

sql"""
         SELECT *
         FROM Test
         WHERE id = ${testId};
       """.query[TestTable].process.map { est: TestTable => Test(est.id, est.data, est.desc) }

And I do get:
<console>:60: error: Cannot prove that scalaz.Free[[x]scalaz.Coyoneda[doobie.free.connection.ConnectionOp,x],Option[com.test.Test]] =:= scalaz.Free.Trampoline[Option[com.test.Test]].
              result.runLast.run

Is there something that I need to import to resolve the issue?  Thanks for your help.

**Comment by tpolecat** [comment]
`runLast` gives you a `ConnectionIO` that you must enlist in a transaction before you can execute it; the `run` method on that type is the one from `scalaz.Free` which isn't what you want. Observe the return types here:

```scala
scala> import scalaz.concurrent.Task
import scalaz.concurrent.Task

scala> import doobie.imports._
import doobie.imports._

scala> val xa: Transactor[Task] = DriverManagerTransactor[Task]("org.postgresql.Driver", "jdbc:postgresql:world", "postgres", "")
xa: doobie.imports.Transactor[scalaz.concurrent.Task] = doobie.util.transactor$DriverManagerTransactor$$anon$2@2675fff2

scala> sql"select name, code from country".query[(String, String)].process.runLast
res0: doobie.imports.ConnectionIO[Option[(String, String)]] = Gosub()

scala> sql"select name, code from country".query[(String, String)].process.runLast.transact(xa)
res1: scalaz.concurrent.Task[Option[(String, String)]] = scalaz.concurrent.Task@29cd85cb

scala> sql"select name, code from country".query[(String, String)].process.runLast.transact(xa).run
res2: Option[(String, String)] = Some((United States Minor Outlying Islands,UMI))
```

In the REPL you can abbreviate this by using the `yolo` module associated with your transactor:

```scala
scala> import xa.yolo._
import xa.yolo._

scala> sql"select name, code from country".query[(String, String)].process.runLast.quick.run
  Some((United States Minor Outlying Islands,UMI))
```

**Comment by wpoosanguansit** [comment]
I see.  Thank you.
