### ISSUE TITLE
doobie with weaver, which package?

### ISSUE THREAD

**Issue by gilcu2** [tpolecat/doobie#1927]
Hello, I want to test my doobie project with weaver-cats. I have:

"org.tpolecat" %% "doobie-h2" % doobieVersion,
 "org.tpolecat" %% "doobie-hikari" % doobieVersion,
 "de.lhns" %% "doobie-flyway" % "0.4.0",
"com.disneystreaming" %% "weaver-cats" % "0.8.3" % Test

in my sbt but scala says:

object weaver is not a member of package doobie
import doobie.weaver._

Which package I need? I try to find doobie-weaver in Maven following the documentation but I don't find it.
Thanks
Reynaldo

**Comment by jatcwang** [comment]
Hi it's here:
https://mvnrepository.com/artifact/org.tpolecat/doobie-weaver_3/1.0.0-RC4

docs: https://tpolecat.github.io/doobie/docs/13-Unit-Testing.html#the-weaver-package
