### ISSUE TITLE
Is there a standard or a recommended way to do upsert?

### ISSUE THREAD

**Issue by wpoosanguansit** [tpolecat/doobie#193]
I looked around the doc and I did not see if there is a way to do update or insert if not present.  Right now, I do query and check the result and do the update or insert and the another query to pull the latest value after the upsert.  I am asking just in case there is already an abstraction for this usual case.  Thanks for your help.

**Comment by tpolecat** [comment]
There is no direct support for upsert because most database don't support it natively (although PostgreSQL is getting it soon I believe). Query-first will only work at a high isolation level that's probably not your default, so instead I would probably try the insert first, and if you get a key collision then perform the update. There is an example of something like this in the chapter on error handling.

**Comment by wpoosanguansit** [comment]
Got it.  Thanks.

**Comment by wpoosanguansit** [comment]
I have tried the example for safeInsert.  However it seems to be specific to Postgresql with unique constraint capture code.  Is there a general way to do it with other db like mysql as well?  I have also tried attemptSql but I am still getting the type error.  I am still not sure how to match for the result:

<console>:55: error: constructor cannot be instantiated to expected type;
 found   : scalaz.-\/[A]
 required: scalaz.Free[[x]scalaz.Coyoneda[doobie.free.connection.ConnectionOp,x],scalaz.\/[java.sql.SQLException,Int]]

Thank you for any help.

**Comment by tpolecat** [comment]
You just need to replace `UNIQUE_VIOLATION` in that example with whatever the value indicates unique violation in MySql. So just experiment, catch the exception, and print out its `.getSQLState()` string. That's what you need to match on.

**Comment by wpoosanguansit** [comment]
I think I am still missing something:

  case class Person(id: Int, name: String)

  def insert(p: Person): ConnectionIO[Int] = {
    sql"insert into person (id, name) values (${p.id}, ${p.name})".update.run
  }

  import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException

  def safeInsert(p: Person): ConnectionIO[String \/ Int] =
    insert(p).attemptSomeSqlState {
      case e => "MySQLIntegrityConstraintViolationException"
    }

attemptSomeSqlState is not recognized.

**Comment by tpolecat** [comment]
If you have a specific exception type, use `.attemptSome/.exceptSome` ... be sure you have `import doobie.imports._` to get that syntax.

```scala
// Compute a String on failure
def safeInsert(p: Person): ConnectionIO[String \/ Int] =
  insert(p).attemptSome {
    case e: MySQLIntegrityConstraintViolationException => "Something bad happened"
  }

// Run another action on failure
def safeInsert(p: Person): ConnectionIO[Int] =
  insert(p).exceptSome {
    case e: MySQLIntegrityConstraintViolationException => update(p) // another ConnectionIO[Int]
  }

```

**Comment by wpoosanguansit** [comment]
Thanks.  Let me try that.

**Comment by wpoosanguansit** [comment]
That works nicely.  Thanks.

**Comment by wedens** [comment]
@letalvoj In postgres "upsert" is just an insert query with `on conflict` clause .  You can write this query in doobie like any other query. What exactly do you mean by "native support"?
