### ISSUE TITLE
"incompatible type in overriding" when overriding ConnectionInterpreter

### ISSUE THREAD

**Issue by felix-hedenstrom** [tpolecat/doobie#1938]
Attempted to implement tracing using trace4cats for a doobie 1.0.0-RC4 transactor but encountered an error. 

```
incompatible type in overriding
def getTypeMap: cats.data.Kleisli[F,java.sql.Connection,java.util.Map[String,Class[_]]] (defined in trait Visitor)
  with override def getTypeMap: cats.data.Kleisli[F,java.sql.Connection,java.util.Map[String,Class[_ <: Object]]] (defined in trait ConnectionInterpreter);
 found   : cats.data.Kleisli[F,java.sql.Connection,java.util.Map[String,Class[_ <: Object]]]
 required: cats.data.Kleisli[F,java.sql.Connection,java.util.Map[String,Class[_]]]
        new ConnectionInterpreter {
```

a similar implementation worked on version 1.0.0-RC2.

Here is a minimal example that compiles with small trivial modifications in 1.0.0-RC2 but that fails with the above error in 1.0.0-RC4
```
object CustomConnectionInterpreter {

  implicit val weakAsync: WeakAsync[IO] =
    WeakAsync.doobieWeakAsyncForAsync(Async[IO])

  (new KleisliInterpreter[IO](LogHandler.noop[IO]) {

    override lazy val ConnectionInterpreter: ConnectionInterpreter =
      new ConnectionInterpreter {}

  }).ConnectionInterpreter

}
```

**Comment by jatcwang** [comment]
Hi @felix-hedenstrom, I've recently added the explicit return types in #1929, can you try 1.0-ed18814-SNAPSHOT and let me know if it works for you?
You'll need to add `  resolvers ++= Resolver.sonatypeOssRepos("snapshots"),` to resolve snapshot versions.

**Comment by felix-hedenstrom** [comment]
Using the latest snapshot it does compile! Do you know when the next release will be?

**Comment by jatcwang** [comment]
I'll see whether there are any cleanups needed but otherwise there's nothing stopping me from making a release
