### ISSUE TITLE
publish snapshots to sonatype and releases to maven central

### ISSUE THREAD

**Issue by fommil** [tpolecat/doobie#194]
blocked on https://github.com/scalaz/scalaz-stream/issues/258

and I'm happy to help.

http://central.sonatype.org/pages/ossrh-guide.html

For now, just create an account and raise a ticket asking for permission to publish to the entire `org.tpolecat` organisation. You'll probably want to have some way of validating that you own `tpolecat.org` or that you're the only `tpolecat` worth their consideration.

**Comment by fommil** [comment]
btw, you don't need to learn maven or anything, it's still just `sbt publish` for snapshots and `sbt publishSigned` for releases (or whatever release plugin you use).

**Comment by tpolecat** [comment]
Ok, opened an issue. We'll see what happens. Further instructions [here](http://www.scala-sbt.org/release/docs/Using-Sonatype.html).

**Comment by fommil** [comment]
I've always found that the SBT docs confound the issue rather than help. If get stuck, look at my dotfiles and the ensime-sbt build.sbt for examples.

**Comment by tpolecat** [comment]
Ok I finally registered **tpolecat.org** and sonatype is [set up](https://issues.sonatype.org/browse/OSSRH-16626) now.

**Comment by tpolecat** [comment]
Attempted a snapshot publish. We'll see if it shows up.

**Comment by tpolecat** [comment]
Ok @fommil I published a snapshot and it worked. Does this mean I'm good? `publishSigned` on a non-snapshot version will do the same thing but show up in central after a while?

**Comment by tpolecat** [comment]
:-1: add `sbt-release` and `sbt-sonatype` because why stop now?

**Comment by fommil** [comment]
heh, there is a weird manual step you have to do on your first promotion, just be aware of that. I've never used either of these two plugins.

Snapshot publishes are very easy... we automate them on pull request merges.
