### ISSUE TITLE
Joda Time or Java 8 LocalDateTime Composite?

### ISSUE THREAD

**Issue by wpoosanguansit** [tpolecat/doobie#199]
I am sorry if this is a duplicate of the question I posted on gitter.  I am just not sure if the gitter post was working.  I am getting:

Could not find or construct Composite[shapeless.::[Long,shapeless.::[java.time.LocalDateTime,shapeless.::[java.time.LocalDateTime,shapeless.....

I wonder if there is already a conversion done for date time type already somewhere.  Thanks for your help.

**Comment by wpoosanguansit** [comment]
gitter thing was working.  And I got a suggestion from kryptt:

implicit val DateTimeMeta: Meta[DateTime] =
    Meta[java.sql.Timestamp].nxmap(
      ts => DateTime(ts.getTime()),
      dt => new java.sql.Timestamp(dt.clicks)
    )

Thanks.

**Comment by kevinmeredith** [comment]
@wpoosanguansit - `doobie.util.meta.MetaInstances` contains `Meta[java.time.LocalDate]` and `Meta[java.time.Instant]`.

https://github.com/tpolecat/doobie/blob/52edb5a361e7b5d43332becfccc03e0d827bb468/modules/core/src/main/scala/doobie/util/meta.scala#L545
