### ISSUE TITLE
[question] - Meta[Optional[MyType]] not being used

### ISSUE THREAD

**Issue by kcris** [tpolecat/doobie#1996]
Hi,
Without going into too many details, I'd like to ask a question.

I have a string column in the database, stored as `text not null`.
It's part of a composite PK, it cannot be null.

On the application side, the table gets data from 2 sources, source A which has the string, source B which has no string.
So I decided to represent the column in scala as `Option[MyType]`, where my optional is built like this
* it has Some(MyType(abc = "...")) when built from source A
* it is None when built from source B

Now, to map the `Option[MyType]` to the db, I decided to use a fixed (but non-empty) string to represent my `None`.
Remember that I cannot have nulls in my db column.

So I created a `Meta[Option[MyType]]`, something along these lines:

```scala
val myOptMeta: Meta[Option[MyType]] = Meta[String].timap[Option[MyType]] {
    case "not-present" =>  None 
    case dbStr =>  Some(MyType(abc = dbStr)) //get
}(opt => 
   opt.fold("not-present")(_.abc) //put
)

//note that I also have:
val myNonOptMeta: Meta[MyType] = Meta[String].timap[MyType] //also have not-optional use cases
...
```

The point being: I get a nice scala type representing my model (`Option[MyType]`), and always get a non-null string in the db.

For data coming from source B, I expect to see "not-present" in my db column.

However, when inserting new records with `myType=None`, what I get in the query is a `null` (and thus a failure due to the PK constraint).

I debugged and doobie is not picking up my `myOptMeta: Meta[Option[MyType]]` instance

but is using the other `myNonOptMeta: Meta[MyType]` instance.

I guess I am missing something here, but I have no idea what that is or how to circumvent it.

Thanks for any hints that might help.

**Comment by jatcwang** [comment]
Hi @kcris, Meta (Get + Put) are for not-nullable types as mentioned in https://tpolecat.github.io/doobie/docs/12-Custom-Mappings.html#single-column-type-mappings

If you want to override the Option handling of your column, you can manually define an implicit `Read[Option[MyType]]`. Similarly on the write side you need to define a custom `Read[Option[MyType]]`.

**Comment by kcris** [comment]
thanks a lot!
