### ISSUE TITLE
Derive Composite[Option[A]] given Composite[A]?

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#200]
Can we generalize deriving of `Option[A]` here, for helping with outer joins where you'll have a column vector that is all null or all non-null? 

``` scala
import scalaz._, Scalaz._
import doobie.imports._

case class Company(name: String, address: String)

// Map a Company to a pair of Option[String] columns
implicit val CompositeOptionCompany = 
  Composite[(Option[String], Option[String])].xmap[Option[Company]](
  { case (a, b) => (a |@| b)(Company.apply) }, _.foldMap(c => (some(c.name), some(c.address))))
```

A problem with this is, if you had `Company(name: Option[String], address: Option[String])` then you can't distinguish `Some(`Company(None, None))`from`None` because they have the same column representation in the join.

/cc @ramnivas

**Comment by ramnivas** [comment]
Looks like the problem you mentioned can come up easily. I tried to use this workaround in a real project which have ids defined as `Option[Long]`. So mapping this to `Company`:
```
case class Company(name: String, address: String, id: Option[Long])
```

When I update the mapping as follows:
```
  implicit val CompositeOptionCompany =
    Composite[(Option[String], Option[String], Option[Option[Long]])].xmap[Option[Company]](
    { case (a, b, id) => (a |@| b |@| id)(Company.apply) },
    _.foldMap(c => (some(c.name), some(c.address), some(c.id))))
```

I start to get the error back:
```
Error:(14, 14) Could not find or construct Composite[(Option[String], Option[String], Option[Option[Long]])].
    Composite[(Option[String], Option[String], Option[Option[Long]])].xmap[Option[Company]](
             ^
```

**Comment by tpolecat** [comment]
Yep, ok. This is an ancient problem going back to the origin of SQL ... there is an infinite tower of `NULL` and there is no way to tell them apart. So my earlier suggestion of selecting the primitive column types and then using `.map` might end up being what you need to do, using a non-nullable field like `name` to decide whether the join failed or not (or by adding an explicit discriminant column).

**Comment by ramnivas** [comment]
Yes. I am going with the `.map` approach for now. 

Separately, I am considering making `id`s simple `Long` (or other primitive types such as `String` as appropriate). Once I do that in many cases, the implicit `Composite` mapper approach will become useful (manually added or when you implement it, automatically derived).

**Comment by ramnivas** [comment]
@tpolecat This is just to remind that you mentioned during Scala By the Bay that there may be an easier way to deal with such situations.

**Comment by tpolecat** [comment]
@ramnivas I'm adding an FAQ section to the doc and will have a discussion of this topic with some suggested approaches.

**Comment by jto** [comment]
@tpolecat are you still looking for a way to derive this ?
I came up with a piece of code doing it, should I open a PR ?

**Comment by tpolecat** [comment]
@jto yeah go ahead, we can talk about it. I don't think it can be done generically but maybe for some cases you can do it.

**Comment by jto** [comment]
Do you have a particular example for which it would not be possible in mind ?

**Comment by tpolecat** [comment]
This is done. forgot to close.
