### ISSUE TITLE
Doobie is not reusing connections, and the documentation doesn't have a single example of how to do it

### ISSUE THREAD

**Issue by mantovani** [tpolecat/doobie#2012]
Doobie is awesome; I think you folks did everything right. The only problem is that I can't get Doobie to reuse a connection, and the documentation isn't helpful. I've never used Cats, but I'm familiar with functional programming.

According to the documentation, this is how to create a connection pool using Hikari:

```scala
  val transactor: Resource[IO, HikariTransactor[IO]] =
    for {
      hikariConfig <- Resource.pure {
        // For the full list of hikari configurations see https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby
        val config = new HikariConfig()
        config.setMaximumPoolSize(10)
        config.setDriverClassName(YeeduPostgresDriver)
        config.setJdbcUrl(s"jdbc:postgresql://${YeeduPostgresHostname}:${YeeduPostgresPort}/${YeeduPostgresDB}?currentSchema=yeedu")
        config.setUsername(YeeduPostgresUser)
        config.setPassword(YeeduPostgresPass)
        config
      }
      xa <- HikariTransactor.fromHikariConfig[IO](hikariConfig)
    } yield xa
```

I have an object called "DB" where I have all my queries:

```scala

object DB {

  private implicit def runTransaction[T](transaction: doobie.ConnectionIO[T]): Either[Throwable, T] =
    runWithRetryTransaction(transaction)

  private def runWithRetryTransaction[T](transaction: doobie.ConnectionIO[T], retryNum: Int = 1): Either[Throwable, T] =
    Try {
      system.log.info("Transaction retry: {}, maxRetry: {}", retryNum, maxRetry)
      transactor.use {xa =>
        transaction.transact(xa)
      }.timeout(1.minute).unsafeRunSync()
    } match {
      case Failure(sqlExp: PSQLException) =>
        system.log.error(sqlExp, "PSQLException: Couldn't complete transaction retry: {}, sqlState: {}, sqlErrorCode: {}",
          retryNum, sqlExp.getSQLState, sqlExp.getErrorCode)
        if (shouldRetry(sqlExp) && maxRetry > retryNum) {
          runWithRetryTransaction(transaction, retryNum + 1)
        } else {
          Left(sqlExp)
        }
      case Failure(exception) =>
        system.log.error(exception, "Exception: Couldn't complete transaction retry: {}", retryNum)
        Left(exception)
      case Success(data) => Right(data)
    }

// all queries...
  def insertWorkflowInstanceError(workFlowJobId: Long, error: String): Either[Throwable, Int] =
    sql"INSERT INTO WORKFLOW_JOB_INSTANCE_ERROR (workflow_instance_id,error) VALUES ($workFlowJobId, $error)"
      .update.run
}
```

I've  received help from the Discord channel, but the solution isn't working either:

```scala

  val (xa,cleanUp):(HikariTransactor[IO], IO[Unit]) = {
    println("foo test")
    transactor.allocated.unsafeRunSync() //this never returns
  }

```

**Comment by yevtyushkin** [comment]
According to the [docs](https://typelevel.org/cats-effect/api/3.x/cats/effect/kernel/Resource.html#use[B](f:A=%3EF[B])(implicitF:cats.effect.kernel.MonadCancel[F,Throwable]):F[B]), `use`:

> Allocates a resource and supplies it to the given function. The resource is released as soon as the resulting F[B] is completed, whether normally or as a raised error.

This means, the following code:
```
transactor.use {xa =>
    transaction.transact(xa)
}.timeout(1.minute).unsafeRunSync()
```
allocates a new transactor, calls `transact` on it, and releases it afterwards without reusing any connections every time you call `runWithRetryTransaction`.


To make your app to reuse connections, you may want to, for example:
1. Refactor `Db` to accept an instance of `transactor`, rather than allocate it every time `runWithRetryTransaction` is called:
```
class Db(transactor: HikariTransactor[IO]) {
  ...
}
```

2. Allocate transactor once, at startup, e.g., in `Main`:
```
object Main extends ResourceApp.Forever {
  def run(args: List[String]): Resource[IO, Unit] =
    for {
      transactor <- createTransactor()
      db = new Db(transactor)
      ... // do stuff with Db
    } yield ()
}
```

**Comment by jatcwang** [comment]
I have expanded on the Hikari example. Hope it helps demonstrate how to use cats.effect.Resource as well as how a typical application using doobie is setup.

https://github.com/tpolecat/doobie/pull/2013/files

Note that at no point do I need to call unsafeRunSync since my main object is extending `cats.effect.IOApp.Simple`

**Comment by mantovani** [comment]
This doesn't make sense. I use the DB object throughout my application. I can't perform all my tasks inside the for loop.

How can I instantiate my DB class so that I can use it anywhere? transactor: HikariTransactor[IO]

This is the key question, so far the only to do it would be doing

```scala
  val (xa,cleanUp):(HikariTransactor[IO], IO[Unit]) = {
    println("foo test")
    transactor.allocated.unsafeRunSync() //this never returns
  }```

But apparently there's a bug.

**Comment by mantovani** [comment]
A person named "amumurst" found the problem.

"I can reproduce, and there is some different ways of fixing it. 

The issue is kinda contrived and I don't know exactly the details, but it has something to do with something called "delayed init" which the  App trait of scala 2 uses (fixed in scala 3 it seems). My best hunch is that the code in the App object is run before the implicit IORuntime has started correctly (or some other initialization order issue), leading to a deadlock.

You can circumvent it by moving the allocation to a lazy val (so other things get to initialize first)

So `lazy val (xa, cleanUp): (HikariTransactor[IO], IO[Unit])`"

This is my final solution:

```scala
case class DBx(transactor: HikariTransactor[IO])

  val transactor: Resource[IO, HikariTransactor[IO]] =
    for {
      hikariConfig <- Resource.pure {
        // For the full list of hikari configurations see https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby
        val config = new HikariConfig()
        config.setMaximumPoolSize(10)
        config.setDriverClassName(PostgresDriver)
        config.setJdbcUrl(s"jdbc:postgresql://${PostgresHostname}:${PostgresPort}/${PostgresDB}?currentSchema=yeedu")
        config.setUsername(PostgresUser)
        config.setPassword(PostgresPass)
        config.setConnectionTimeout(1000)
        config
      }
      xa <- HikariTransactor.fromHikariConfig[IO](hikariConfig)
    } yield xa

  lazy val (xa: HikariTransactor[IO],cleanUp: IO[Unit]) =  transactor.allocated.unsafeRunSync()

  val db = DB(xa)

```

Thank you so much

**Comment by jatcwang** [comment]
I still recommend structuring your code following the examples to avoid unsafeRunSync. How your code is laid out right now (which forces you to call unsafeRunSync) isn't idiomatic nor ideal and will present problems in the future.
(For example, who calls `cleanUp` on your connection pool and when?)
