### ISSUE TITLE
How do i set Snapshot isolation level for transaction?

### ISSUE THREAD

**Issue by DenisNovac** [tpolecat/doobie#2020]
Hello. I've noticed there is no snapshot isolation level in doobie enum:

https://github.com/tpolecat/doobie/blob/main/modules/core/src/main/scala/doobie/enumerated/transactionisolation.scala

```scala
object TransactionIsolation {

  /** @group Values */ case object TransactionNone            extends TransactionIsolation(TRANSACTION_NONE)
  /** @group Values */ case object TransactionReadUncommitted extends TransactionIsolation(TRANSACTION_READ_UNCOMMITTED)
  /** @group Values */ case object TransactionReadCommitted   extends TransactionIsolation(TRANSACTION_READ_COMMITTED)
  /** @group Values */ case object TransactionRepeatableRead  extends TransactionIsolation(TRANSACTION_REPEATABLE_READ)
  /** @group Values */ case object TransactionSerializable    extends TransactionIsolation(TRANSACTION_SERIALIZABLE)

...}
```

I am using this solution to set levels: https://github.com/tpolecat/doobie/issues/1837#issuecomment-1476745441

Is there any workaround for that?

**Comment by jatcwang** [comment]
I've added a comment in https://github.com/tpolecat/doobie/issues/1837#issuecomment-2060973978 which allow you to set the isolation level using an int. Hope it helps!

**Comment by jatcwang** [comment]
I'm curious though. Which database you're using that you're trying to set a "snapshot" isolation level?

**Comment by DenisNovac** [comment]
Microsoft SQL

**Comment by jatcwang** [comment]
Your JDBC driver ultimately handles the intepretation of the `int` you passed to setTransactionIsolationLevel. It's best to follow the documentation of your specific JDBC driver. 

https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L4904
https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L4593

Seems like what you want to pass in is `SQLServerConnection.TRANSACTION_SNAPSHOT`

**Comment by DenisNovac** [comment]
I see, thanks!
