### ISSUE TITLE
Where is With ZIO Integration?

### ISSUE THREAD

**Issue by dejvid** [tpolecat/doobie#2022]
Hello, I am kinda confused. So I read on internet that there is ZIO integration then when I check the project I dont see ZIO wrappers, but I do find cats. Can someone explain to me what is happening? Was it moved somewhere else, I really need some simple stuff from this library but I have it hard time interfacing with ZIO. I
Best regards
David

**Comment by jatcwang** [comment]
Hi @dejvid, Doobie are built on cats-effect typeclasses, where ZIO provides integrations with (See https://github.com/zio/interop-cats)
If you are running into issues getting ZIO to work with cats-effect/Doobie, I think you can ask on [ZIO discord](https://discord.com/invite/2ccFBr4) and they should be able to help you out. I don't use ZIO day-to-day so I'm not too familiar with it, sorry.
