### ISSUE TITLE
Transaction Isolation Levels

### ISSUE THREAD

**Issue by decoursin** [tpolecat/doobie#2035]
I'm trying to set the isolation level for a transaction, which I believe can be done using [this function](https://github.com/tpolecat/doobie/blob/main/modules/free/src/main/scala/doobie/free/connection.scala#L135). However, it would be nice if instead of `int` it took an ADT or something, so that the user knew exactly what integer corresponds to what transaction isolation level. I would guess it follows the "ANSI levels" as shown here? https://docs.oracle.com/javadb/10.8.3.0/devguide/cdevconcepts15366.html

**Comment by jatcwang** [comment]
Hi @decoursin, does https://github.com/tpolecat/doobie/issues/1837 help answer your question?

**Comment by decoursin** [comment]
Yes, it does, thank you so much! I just have to use this:
```scala
HC.setTransactionIsolation(TransactionIsolation.TransactionRepeatableRead).flatMap(...)
```
which I see HC is the high-level component, and FC the lower level one.
