### ISSUE TITLE
build.sbt in introduction broken for Scala 3

### ISSUE THREAD

**Issue by apple-corps** [tpolecat/doobie#2043]
For the examples in doobie, what is the proper scala version to use scala 3 for build.sbt . I tried scalaVersion := "3.3.3", scalaVersion := "3.3.1", scalaVersion := "3.3" and all could not resolve doobie. When setting scalaVersion to 3 then it there was an issue resolving the scala-library dependency.

https://tpolecat.github.io/doobie/docs/01-Introduction.html
Introduction · doobie
docs

[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-library:3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala-library/3/scala-library-3.pom
scalaVersion := "3" // Scala $scalaVersion$

lazy val doobieVersion = "1.0.0-RC5"

libraryDependencies ++= Seq(
  "org.tpolecat" %% "doobie-core"     % doobieVersion,
  "org.tpolecat" %% "doobie-postgres" % doobieVersion,
  "org.tpolecat" %% "doobie-specs2"   % doobieVersion
)

**Comment by jatcwang** [comment]
With this example project https://github.com/jatcwang/doobie_quick_start and scala 3.3.3 + doobie 1.0.0-RC5 I have no problem resolving the artifacts :thinking: Are you behind a proxy or something? What's the error message when you use Scala 3.3.3?

**Comment by apple-corps** [comment]
Resolved via discord. The system default sbt was ancient and did not seem to resolve the scala version properly. The solution was to set the scala version in `project/build.properties` to the latest sbt release.
