### ISSUE TITLE
Add a note in the documentation about setAutoCommit and transaction boundaries

### ISSUE THREAD

**Issue by kryptt** [tpolecat/doobie#205]
Sometimes you will need to run a statements (like DDL) outside of a transaction (Please be aware that this is not recomended, unsafe and will not compose). If ABSOLUTELY necessary you can write something like:

``` scala
  def addXtraToX: ConnectionIO[Unit] =
    setAutoCommit(true) *> 
    sql"ALTER TYPE x ADD VALUE 'xtra'".update.run *>
    setAutoCommit(false)
```

**Comment by tpolecat** [comment]
Yeah I'm working on replacing `Transactor` with something more general that coincidentally lets you interpret a `ConnectionIO` without wrapping it in a transaction. Adds a `.connect` method that's like `.transact` but without the extra logic.

**Comment by kryptt** [comment]
Even better :+1:

**Comment by tpolecat** [comment]
See also #364
