### ISSUE TITLE
postgis-stubs provides postgresql classes, and confuses assembly

### ISSUE THREAD

**Issue by ajknoll** [tpolecat/doobie#216]
Found this fun error when running `sbt assembly` (https://github.com/sbt/sbt-assembly):

```
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] /home/aknoll/.ivy2/cache/org.postgresql/postgresql/jars/postgresql-9.4-1201-jdbc41.jar:org/postgresql/PGConnection.class
[error] /home/aknoll/.ivy2/cache/org.postgis/postgis-stubs/jars/postgis-stubs-1.3.3.jar:org/postgresql/PGConnection.class
```

We've already applied the `exclude("postgres", "postgres")` fix to `doobie-contrib-postgresql`.

It looks like `postgis-stubs` is providing the `postgresql` classes in the wrong scope; perhaps the exclude on `"org.postgis" % "postgis-jdbc"` should be `exclude("org.postgis", "postgis-stubs")` instead.

**Comment by tpolecat** [comment]
@ajknoll can you please test against `0.2.3-SNAPSHOT` (on sonatype) and see if that change fixed your problem?

**Comment by tpolecat** [comment]
Verified. This works now.
