### ISSUE TITLE
Unexpected Test failure with custom enum types after upgrading pogresql jdbc version

### ISSUE THREAD

**Issue by kryptt** [tpolecat/doobie#221]
After upgrading the postgresql jdbc driver to 9.4-1202-jdbc42 query analysis with custom fields start to fail unexpectedly. For example:

```
[info] Update0 defined at user-queries.scala:277
[info]   
[info]   UPDATE
[info]   core.users
[info]   SET
[info]   state = ?::core.resource_state
[info]   WHERE
[info]   id = ?
[info]   
[info]   + SQL Compiles and Typechecks
[error]   x P01 ResourceState  →  OTHER  ("core"."resource_state")
[error]    x ResourceState is not coercible to OTHER ("core"."resource_state") according to
[error]      the JDBC specification. Fix this by changing the schema type to VARCHAR, or the
[error]      Scala type to . (user-queries.scala:277)
```

I wrote a quick     `Meta.other[PGobject]("\"core\".\"resource_state\"").nxmap[A](` and that worked. So this should probably now be a documentation note, stating enums are properly support with version 9.4-1202-jdbc42 of the driver.

**Comment by kryptt** [comment]
I have since found out version 9.4-1202-jdbc42 will arbitrarily report an enum field as either a `VARCHAR` or `OTHER ("enumtype")`. 

This driver version now makes my tests unpredictably fail...

**Comment by davecramer** [comment]
I have a fix coming out for this. I can provide a snapshot if you want to test ?

**Comment by kryptt** [comment]
Sure, I can test against your snapshot.

**Comment by davecramer** [comment]
the 2103 snapshots here
https://oss.sonatype.org/content/repositories/snapshots/org/postgresql/postgresql/

Dave Cramer

**Comment by kryptt** [comment]
@davecramer Ok, I'm using that snapshot and it is still happening. Do you need help setting up a test?

**Comment by davecramer** [comment]
Yes, please

Dave Cramer

**Comment by kryptt** [comment]
does an sbt project work for you ? any database / connection settings I should pick?

**Comment by tpolecat** [comment]
I recommend doing the test in raw Java JDBC just to ensure that doobie isn't a factor.

Thanks for chasing this down, by the way. Ping me if you need help on the doobie end.

**Comment by tpolecat** [comment]
Since `doobie-contrib-postgresql` uses 1201 (this problem manifests only if you explicitly upgrade to 1202) I'm going to move it out of the 0.2.3 milestone. We can do another release once the driver issue is resolved.

**Comment by kryptt** [comment]
I wrote the following test : 
https://github.com/kryptt/pgjdbc/commit/5a38cfe0220beb340977ad60cfcb83a18ae41775
for the driver code, expecting it to possibly fail, or to start narrowing down the issue. But I get things reported correctly and decided to write something from the doobie side as well to start narrowing down what my problem is. So, I wrote this: 
https://github.com/kryptt/doobie/commit/f44dc37deae3ea61069ff53a2c77ae429c2e1524
and get an unexpected NPE
```
error] ! Analysis of myenum
[error]  null (TypeInfoCache.java:188)
[error] org.postgresql.jdbc2.TypeInfoCache.getSQLType(TypeInfoCache.java:188)
[error] org.postgresql.jdbc2.TypeInfoCache.getSQLType(TypeInfoCache.java:183)
[error] org.postgresql.jdbc2.TypeInfoCache.requiresQuoting(TypeInfoCache.java:816)
[error] org.postgresql.jdbc2.AbstractJdbc2DatabaseMetaData.getTypeInfo(AbstractJdbc2DatabaseMetaData.java:3998)
[error] doobie.free.databasemetadata$DatabaseMetaDataOp$GetTypeInfo$$anonfun$defaultTransK$93.apply(databasemetadata.scala:378)
[error] doobie.free.databasemetadata$DatabaseMetaDataOp$GetTypeInfo$$anonfun$defaultTransK$93.apply(databasemetadata.scala:378)
[error] doobie.free.databasemetadata$DatabaseMetaDataOp$$anonfun$primitive$1$$anonfun$apply$1.apply(databasemetadata.scala:77)
[error] doobie.contrib.postgresql.pgtypesspec$$anonfun$1$$anonfun$apply$21.apply(pgtypes.scala:116)
[error] doobie.contrib.postgresql.pgtypesspec$$anonfun$1$$anonfun$apply$21.apply(pgtypes.scala:116)
[error] doobie.contrib.postgresql.pgtypesspec$$anonfun$1.apply(pgtypes.scala:116)
[error] doobie.contrib.postgresql.pgtypesspec$$anonfun$1.apply(pgtypes.scala:116)
```

If I'm not mistaken, this highlights that doobie gets the information differently than my pgjdbc test. Any ideas?

**Comment by davecramer** [comment]
Seems to me your java test uses resultsetmetadata and doobie uses
databasemetadata



Dave Cramer

**Comment by kryptt** [comment]
@tpolecat How does doobie handle both sources ? (I couldn't find it in the source)

**Comment by tpolecat** [comment]
I use database metadata (from the `Connection`) to get the JDBC ↔︎ native type mappings, parameter metadata (from the `PreparedStatement`) to get parameters types, and column metadata (from the `ResultSet`) for output columns. All three work well with 1201.

**Comment by tpolecat** [comment]
We're up to 1211 at this point so I'm closing this.
