### ISSUE TITLE
add sqlite-contrib

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#223]
Driver https://github.com/xerial/sqlite-jdbc

**Comment by xeno-by** [comment]
Hi @tpolecat! Has there been any progress with implementing an SQLite connector for Doobie, or this ticket is out of scope for now?

**Comment by tpolecat** [comment]
Does SQLite's driver offer anything beyond standard JDBC? IIRC I closed this because the driver doesn't offer anything beyond standard JDBC that would benefit from an add-on package (same with MySQL). Is there something you're trying to do that's awkward with doobie out of the box?

**Comment by xeno-by** [comment]
Not to the best of my knowledge (which is admittedly pretty rudimentary at this point).

I was just shopping for a data access library for our SemanticDB efforts (https://github.com/scalameta/scalameta/pull/1174, https://github.com/scalameta/language-server/pull/94) and was wondering whether Doobie supports SQLite. 

Am I right in thinking that anything that supports JDBC is automatically supported in Doobie, and additional modules like `doobie-h2` or `doobie-postgres` are only needed to make use of additional functionality that goes beyond JDBC?

**Comment by tpolecat** [comment]
Yes, exactly: doobie-core supports any JDBC driver. The add-on modules provide support for vendor-specific features and nonstandard types. So it should work fine with the SQLite JDBC driver.

I encourage you to try the 0.5.x milestone, which is tracking the cats milestones and should be released later this month. Let me know if you have any questions.
