### ISSUE TITLE
Error when calling attemptSql on returned value from traverseU

### ISSUE THREAD

**Issue by jhzab** [tpolecat/doobie#227]
The following code will not compile:

```
List(1,2,3).traverseU(_.point[ConnectionIO]).attemptSql
```

And scalac will give the following error:

```
value attemptSql is not a member of scalaz.Free[[X_kp1]scalaz.Coyoneda[doobie.free.connection.ConnectionOp,X_kp1],List[Int]]
```

But this works fine when the return type is explicitly specified:

```
(List(1,2,3).traverseU(_.point[ConnectionIO]): ConnectionIO[List[Int]]).attemptSql
```

(Of course, this also happens when the List is comprised of interpolated sql strings, i.e.: `(List(
      sql""""""
    ).traverseU(_.update.run): ConnectionIO[List[Int]]).attemptSql.transact(xa).run`)

**Comment by tpolecat** [comment]
Thanks!

Probably need an unapply for the ops class, which will require some refactoring. Might not make it in 0.2.3 since there's a workaround but I'll take a look.
