### ISSUE TITLE
CallableStatement Example???

### ISSUE THREAD

**Issue by charlesa101** [tpolecat/doobie#273]
I am trying to implement a callable stored proc with out param return resultset???

Not sure the current version can support it

**Comment by tpolecat** [comment]
You can do this but you need to use a lower-level API. Which database are you using?

**Comment by charlesa101** [comment]
IBM AS400 :(


=================
Notice:
This e-mail including any attachments is confidential and may be legally
privileged. If you have received it in error please advise the sender
immediately by return email and then delete it from your system. Any
unauthorized use, distribution, copying or alteration of this email is
strictly forbidden.

**Comment by tpolecat** [comment]
So, like, Oracle? or DB2?

**Comment by charlesa101** [comment]
DB2


=================
Notice:
This e-mail including any attachments is confidential and may be legally
privileged. If you have received it in error please advise the sender
immediately by return email and then delete it from your system. Any
unauthorized use, distribution, copying or alteration of this email is
strictly forbidden.

**Comment by tpolecat** [comment]
I did this with Postgres but it be similar with DB2. Assume we have a function with an `OUT` cursor:

```sql
CREATE OR REPLACE FUNCTION foo(n integer, OUT c refcursor) AS '
BEGIN
    OPEN c FOR SELECT name FROM country LIMIT n;
END;
' LANGUAGE plpgsql;
```

We can then write a program to call it and return the results. To do this you need to use the `free` API for the `CallableStatement` stuff, which is basically at the same level of abstraction as JDBC. The connection and result handling use the `hi` API which is higher level and safer.

```scala
package doobie.example

import doobie.free.{ callablestatement => FCS }
import doobie.imports._
import doobie.enum.jdbctype.Other
import scalaz._, Scalaz._, scalaz.effect._

object callable extends SafeApp {

  def names(limit: Int): ConnectionIO[List[String]] =
    HC.prepareCall("{ call foo(?, ?) }") {
      for {
        _  <- FCS.setInt(1, limit)
        _  <- FCS.registerOutParameter(2, Other.toInt)
        _  <- FCS.execute
        rs <- FCS.getObject(2).map(_.asInstanceOf[java.sql.ResultSet])
        ns <- FCS.liftResultSet(rs, HRS.list[String] ensuring FRS.close)
      } yield ns
    }

  val xa: Transactor[IO] = 
    DriverManagerTransactor[IO]("org.postgresql.Driver", "jdbc:postgresql:world", "postgres", "")

  override def runc: IO[Unit] =
    for {
      ns <- names(10).transact(xa)
      _  <- ns.traverse(IO.putStrLn)
    } yield ()

}
```

It is likely that this isn't quite what you need, but it should give you an idea of whether you want to pursue it or not. Let me know if you have more questions, I'm happy to help.

**Comment by charlesa101** [comment]
Cool! @tpolecat, thanks a lot!!! this close to what i want..! very compact and succinct,

Now let me try it on db2 and i will let you know how it goes!

Thank you

**Comment by chenjianjx** [comment]
Possible to rewrite the sample code without scalaz?  People may not have used Scalaz before. 

i.e.  How to rewrite `FCS.liftResultSet(rs, HRS.list[String] ensuring FRS.close)`  without scalaz ?
