### ISSUE TITLE
Mapping of postgres composite types

### ISSUE THREAD

**Issue by wennergr** [tpolecat/doobie#278]
Is it be possible to map a [postgres composite types](http://www.postgresql.org/docs/9.0/static/rowtypes.html) to a case class?

Example SQL that returns a composite type
```sql
drop schema if exists composite cascade;
create schema composite;
set schema 'composite';

create type title as enum (
  'mr', 'mrs', 'miss', 'mx'
);

create type person_summary as (
  id integer,
  title title,
  last text
);

create type org_summary as (
  name text,
  people person_summary[]
);


select ('Acme Inc', Array [
  (1234, 'mr', 'Eriksson') :: person_summary,
  (1235, 'miss', 'Svensson') :: person_summary]) :: org_summary;
```

**Comment by tpolecat** [comment]
So, the best the driver can do is hand you a `PGObject` that contains a string version of the value that you have to parse out. It can be done but the escaping is somewhat complex ... the tokenizer provided by the driver doesn't quite understand everything that's coming back. In the case you provide it looks like 

    ("Acme Inc","{""(1234,mr,Eriksson)"",""(1235,miss,Svensson)""}")

But adding some embedded quotes ad spaces and commas via `Erik"sson` and `Sven,sson` makes it a bit uglier:

    ("Acme Inc","{""(1234,mr,\\""Erik\\""\\""sson\\"")"",""(1235,miss,\\""Sven,sson\\"")""}")

So it's certainly *possible* to parse these out but it would take some work. Let me know what you think ... it would be an interesting project to define encoders for this format but I do have a lot of other things on my plate right now.

A better option might be to return structured results like this as JSON, which is well-supported by Postgres and works well with on the Scala side.

**Comment by wennergr** [comment]
Yeah, I will probably go with JSON instead. E.g use the `to_json` function on the composite type.

Long term, I do think that such parsers would be a useful thing to have (and fun to write). Would you be interested in a PR?

**Comment by tpolecat** [comment]
If you want to give it a try feel free. It will end up having the same structure as Argonaut or Circe I think, and will need to lean on the driver internals for parsing types out. In principle it seems easy but I think the details will end up being hard.
