### ISSUE TITLE
Consistent all-in-one import clauses among contrib subprojects

### ISSUE THREAD

**Issue by guersam** [tpolecat/doobie#279]
Currently we need `import doobie.contrib.postgresql.pgtypes._` for some postgres-specific typeclasses such as array support, which is inconsistent with `import doobie.imports._` and easy to forget.

Incomplete IDE support makes it worse by dropping the import clause during optimizing import or move refactoring due to a false implicit resolution (it's not responsibility of doobie but it sometimes makes my life harder.)

I'd suggest making all-in-one imports consistent as `import doobie.contrib.*.imports._` for newcomers and victims of today's IDEs.

**Comment by tpolecat** [comment]
:+1: thanks for pointing this out. Will fix for 0.2.4
