### ISSUE TITLE
Support fs2.Task (but as generically as reasonably possible)

### ISSUE THREAD

**Issue by fiadliel** [tpolecat/doobie#311]
Currently, the FS2/cats port of doobie supports only `IOLite`, which is probably not a useful effect type in the larger ecosystem outside of doobie.

The port should support other "IO" types, the obvious questions are which ones, and how.

1. `fs2.Task` isn't very difficult to support explicitly, it includes enough functionality to implement both `Catchable` and `Capture`. Calling `Task` functionality directly is probably also more performant than more generic alternatives.

2. We could support every effect type that FS2 supports, which would involve using `fs2.util.Effect` to implement the appropriate typeclasses (and the functionality is sufficient, I think, though the `attempt` call has to be folded into an `Xor` result). It does mean that people who want to interoperate with doobie have to implement this FS2 typeclass instead of something in cats.

3. We could support every effect type that cats supports. Because of the various levels of indirection to support this, probably the least performant. But it would allow (for example) Monix Task support OOTB. How to implement `Catchable` seems obvious (use `MonadError`); the question is whether there is a reasonable implementation of `Capture` that we can reuse. I thought wrapping the value in `Eval.Always` might be sufficient, but perhaps not (I hadn't given it detailed thought). If cats doesn't have the appropriate abstraction, it _might_ be worth adding.

Soo... ticket is about implementing one or more of these, because we will need more than `IOLite` support.

**Comment by fiadliel** [comment]
Oh, fourth option: doobie uses FS2 typeclasses instead of its internal versions. I doubt this will fly, but it is an option.

**Comment by fiadliel** [comment]
... and having caught up on your discussion on gitter. I see what you mean, that I have no guarantees about what `Applicative` will do with the value afterwards.

In fact, perhaps we can't currently implement requirements in terms of cats typeclasses, _because_ it doesn't internally implement an IO type.

**Comment by tpolecat** [comment]
@fiadliel fs2 `Effect` implies doobie `Capture` so we can certainly do that, and I didn't notice cats `MonadError` which subsumes doobie `Catchable`. So those changes would make at least fs2 `Task` work out of the box, in a more general way than just providing instances.

For Monix it's just a matter of providing the instances, which isn't a big deal.

**Comment by fiadliel** [comment]
`Effect` also extends `fs2.util.Catchable`, so it's enough to add support `fs2.Task`, without considering cats typeclasses at all. I can make a PR doing this.

**Comment by guersam** [comment]
I'd suggest that we start with option 1 which seems the easiest for now, and then consider the others in relation to #310. WDYT?
