### ISSUE TITLE
OutOfMemoryError when fetching data from large tables

### ISSUE THREAD

**Issue by artempyanykh** [tpolecat/doobie#316]
Doobie: v0.3.0, 0.2.4
Scala: 2.11.7
System: Mac OS El Capitan
DB: PostgreSQL v9.4.4

Considering a table with 10M records, processing of q1 and q2 behaves differently:
```
val q1 = sql"SELECT * FROM tbl LIMIT 1000".query[Blah]
val q2 = sql"SELECT * FROM tbl LIMIT 10000000".query[Blah]

q1.process.take(5).quick.run // r1
q2.process.take(5).quick.run // r2
```

`r1` usually works fine, while `r2` fails with OutOfMemory (it's trying to fetch the whole 10M records beforehand).

**Comment by tpolecat** [comment]
When I try the following with the `world` database using only JDBC there is a 14-second pause and a memory spike before the first row arrives. So I think this is the driver. Can you try this with your query and see if you experience the same thing?

```scala
import java.sql.DriverManager

object big {

  def now = System.currentTimeMillis

  def main(args: Array[String]): Unit = {
    Class.forName("org.postgresql.Driver")
    val co = DriverManager.getConnection("jdbc:postgresql:world", "postgres", "")
    try {
      val ps = co.prepareStatement("select a.name, b.name from city a, city b") // 16m rows
      try {
        val start = now
        val rs = ps.executeQuery
        try {
          rs.next
          println("first row received; time = " + (now - start))
        } finally rs.close()
      } finally ps.close()
    } finally co.close()
  }

}
```

```
first row received; time = 14880
```

![image](https://cloud.githubusercontent.com/assets/1200131/17412422/4fc86652-5a42-11e6-92c2-733c81f42187.png)

**Comment by tpolecat** [comment]
But when I continue reading with a stream I'm seeing usage continue to grow. Huh.

**Comment by andrusha** [comment]
Shouldn't chunking help in that case? As at every point in time only a subset of records will be retrieve. https://github.com/tpolecat/doobie/pull/314

**Comment by tpolecat** [comment]
I'm still looking at this but haven't pinpointed where the issue is. There is some subtlety in the way the streams are constructed that seems to be causing cells to be retained. Chunking is an orthogonal concern.

**Comment by artempyanykh** [comment]
@tpolecat I tried the code above with my query and it looks like (pic below) with 33s delay before the first row is received.
<img width="526" alt="screenshot 2016-08-11 10 47 58" src="https://cloud.githubusercontent.com/assets/2338443/17581884/8d155502-5fb9-11e6-883a-2b98d60b1b8f.png">

**Comment by guersam** [comment]
Could this be relavant? https://jdbc.postgresql.org/documentation/91/query.html#query-with-cursor

**Comment by tpolecat** [comment]
@artempyanykh and others, the fix is in the 0.3.1-SNAPSHOT build if you want to try it out.

**Comment by artempyanykh** [comment]
Ah, sounds amazing! Thanks @tpolecat @guersam !

**Comment by andrusha** [comment]
@tpolecat when do you plan to release `0.3.1`?

**Comment by tpolecat** [comment]
@andrusha in the next few weeks I hope. Just need to find a few hours to work on it.
