### ISSUE TITLE
parameterize sql interpolation

### ISSUE THREAD

**Issue by Centaur** [tpolecat/doobie#324]
What I am implementing is a trait that contains some common queries, like this: 

```scala
trait CommonDao {
  val tableName: String
  def findAll[T: Composite]() = sql"select * from $tableName".query[T].list
}
```

Obviously the above code does not compile because in sql interpolation `$tableName` will be interpreted as sql statement parameter.  So is there some way to introduce such parameters to sql interpolation ?

**Comment by tpolecat** [comment]
This approach is kind of fragile because it will break if you change your table definition (i.e., what you get when you `SELECT *`) but you can implement it by constructing a `Query` directly.

```
import doobie.imports._
import shapeless.HNil

def all[A: Composite](table: String): ConnectionIO[List[A]] =
  Query[HNil,A](s"select * from $table").toQuery0(HNil).list
```

**Comment by Centaur** [comment]
Thank you for mentioning the caveat, I have planned a code generation task to keep the code up to date. I should have finished reading the book first.
