### ISSUE TITLE
Allow constant interpolation in sql macro

### ISSUE THREAD

**Issue by fanf** [tpolecat/doobie#334]
It would be nice to be able to have constant interpolation in the sql macro as an alias system, to save keystrokes and facilitate refactoring. The two main use cases identified today are: 
1.  a long table name, that you have to repeat tens of time in different variation of requests - ie, just an alias, defined statically at one place: `sql"select foo, bar, baz from #$user where ...`, where in fact `user` is ``myBusinessUserThatHaveThatKingOfPropertyAndOhWellTheTableNameIsSoLong`
2. a way to bundle together the list of column of a table and the case class definition for that table with a lot of columns, and the list of these colums. Most of the time, I can't use (and don't want to use) `select *` because it is not stable given table evolution (typically when columns are added/removed/reordered along the live of the application, especially for on premise app with versions).  So I would be able to define something like `val allcolumns = "foo, bar, baz, ....` along with the case class for that table, and just refers to it: `"sql"select $#allcolumns from $#user where ...`

With some naming convention, I believe we can quiclky converge to some completelly unsurpising model, and easy to evolve: just modifiy the case class and the corresponding `allcolumns` to have most of the request updated.

**Comment by tpolecat** [comment]
This can be done, but you lose compile-time checking of queries (which is something I'm hoping to add for 0.4). So I'm looking at maybe picking up @Jacoby6000's [scoobie](https://github.com/Jacoby6000/scoobie) AST for cases where you want to construct SQL piecewise. The existing scoobie DSL isn't quite what I want but I think it may not be too far off. In any case it would be nice to have a "dynamic sql" story for 0.4 if possible.

**Comment by fanf** [comment]
Being able to build queries by piece would be much, much better (even if
doesn't obliviate the aliasing need, it could supersede it). I don't really
need a dsl, I'm happy writing SQL, but perhaps it's needed to actually
separate the piece.

**Comment by Jacoby6000** [comment]
@tpolecat the scoobie AST is completely independent of the DSL, so you should be able to do what you want with the AST. That said, if there are any changes to any piece of Scoobie you'd like to see, I'm willing to make them.

**Comment by tpolecat** [comment]
This is addressed by fragments.

**Comment by fanf** [comment]
Yes it is, in a very nice way!
