### ISSUE TITLE
Example of delete request with DriverManagerTransactor

### ISSUE THREAD

**Issue by mycaule** [tpolecat/doobie#355]
From the doobie tutorial I understood how to do `select` request. How do I `perform` delete request and properly connect the transaction to the drivermanager like in the code sample below?

```
val xa = DriverManagerTransactor[Task]("org.postgresql.Driver", "jdbc:postgresql:dbname", "user", "password")
```

```
case class Toto(id: Long, name: String)

def getAll = {
    sql"select id, name from toto"
          .query[Toto]
          .process
          .transact(xa)
          .runLog
          .unsafePerformSync
}
```

```
def delete(id: Long) = {
    sql"delete from toto where id=$id"
        . // What to do from here ?
}
```

**Comment by brianpendleton** [comment]
Hey @mycaule , take a look at the book of doobie chapter on Inserting/Updating:  https://tpolecat.github.io/doobie-0.3.0/07-Updating.html  ... there is an example of dropping a table via the `update` method at the end of the `sql` interpolator.

**Comment by fanf** [comment]
Just for the record, you can do: 
```
sql"delete blabla".update.run.attempt.transact(xa).unsafePerformSync
```

**Comment by tpolecat** [comment]
Yeah `.run` gets you to `ConnnectionIO[Int]` and it's all the same from there. I'll try to make the doc clearer. YOLO mode is useful but maybe not what I should use for the examples.
