### ISSUE TITLE
CI doesn't seem to be building tut doc

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#362]
Hey @guersam could you take a look at this? Here is a [recent build](https://travis-ci.org/tpolecat/doobie/jobs/165525653) that claims to be building docs, but there's nothing in the transcript to indicate that this is happening. The log message appears but everything after the `&&` [here](https://github.com/tpolecat/doobie/blob/series/0.3.x/project/travis-build.sh#L16-L19) looks like it's ignored.

**Comment by tpolecat** [comment]
Yeah I just checked and tut fails on the `series/0.3.x` tip.

**Comment by guersam** [comment]
yeah it's weird... I'll look into this.
