### ISSUE TITLE
Document how to exec "vacuum" or other special command out of transaction

### ISSUE THREAD

**Issue by fanf** [tpolecat/doobie#364]
In some cases, we want to disable transaction management, for example to execute "vaccuum" on postgresql. 

It can be done with the following command: 

```
(FC.setAutoCommit(true) *> sql"vacuum".update.run <* FC.setAutoCommit(false)).transact(xa).unsafePerformIO
```

This is not a  problem for other transaction, the semantic being (as eplained by @tpolecat): 

> Rob Norris @tpolecat 17:11
> When you setAutoCommit(true) any prior operations will be committed; then when you turn it back 
> off anything following will be committed by the final commit that is introduced by the transactor. So 
> in effect you're splitting your computation into three segments (a non-transactional block with a 
> transaction on either side).
> That's why the operation is on FC rather than HC; it's a low-level operation so you need to be 
> careful about how you compose things that use it.
> But no, it's isolated like anything else. Independent transactions are unaffected, up to the isolation 
> level.

That information should be documented in the Book of Doobie, most likely in the FAQ.

**Comment by tpolecat** [comment]
👍
