### ISSUE TITLE
Doobie stickers do not compile with other typelevel stickers

### ISSUE THREAD

**Issue by zainab-ali** [tpolecat/doobie#367]
All other stickers of type `Hex` are such that the operation `hex1.tessellate(hex2)` is still lawful.

This is the most urgent issue currently blocking doobie from being a commercial library. Please fix.

**Comment by tpolecat** [comment]
Corners are a free parameter. Everyone else failed to abstract.

![image](https://cloud.githubusercontent.com/assets/1200131/19410606/2848abdc-92a5-11e6-8772-334d06b86586.png)
