### ISSUE TITLE
Getting Gosub() while using doobie with an existing interpreter.

### ISSUE THREAD

**Issue by iniyanp** [tpolecat/doobie#374]
[Third.scala.txt](https://github.com/tpolecat/doobie/files/556308/Third.scala.txt)

**Edit:** I inlined this for you. - r

``` scala
/**
  * Created by paramin on 10/25/16.
  */



import scalaz.{Catchable, Coyoneda, EitherT, Free, Functor, Monad, \/, ~>, _}
import doobie.imports._

import scalaz.concurrent.Task
import scalaz.stream.{Process, process1}

sealed trait DB[A]

object DB {

  type Free[A] = scalaz.Free.FreeC[DB, A]

  final case class Eval[Task[A],A](fa: Task[A]) extends DB[A]
  def eval[Task[A], A](fa: Task[A]): Free[A] =
    Free.liftFC[DB, A](Eval(fa)) // TODO find a way to restrict this to only interpreters

  final case class Fail[A](t: Throwable) extends DB[A]
  def fail[A](t: Throwable): Free[A] = Free.liftFC(Fail(t))

  final case class SelectData[A]() extends DB[Process[DB.Free, A]]
  def selectData[A](): DB.Free[Process[DB.Free,A]] = Free.liftFC[DB, Process[DB.Free, A]](SelectData())

  implicit def dbCatchable: Catchable[DB.Free] = new Catchable[DB.Free] {

    def attempt[A](action: DB.Free[A]): DB.Free[Throwable \/ A] = {
      val et = action.foldMap[EitherT[DB.Free, Throwable, ?]](
        new (Coyoneda[DB, ?] ~> EitherT[DB.Free, Throwable, ?]) {
          def apply[B](cy: Coyoneda[DB, B]) = cy.fi match {
            case DB.Fail(t) => EitherT.left( Monad[DB.Free].point(t))
            case db =>
              EitherT.right[DB.Free, Throwable, B](Free.liftFC(db) map cy.k)
          }
        })(Functor[Coyoneda[DB, ?]], EitherT.eitherTMonad[Free, Throwable]( Monad[DB.Free]))

      et.run
    }

    def fail[A](t: Throwable): Free[A] = DB.fail(t)
  }

}

object Third {

  def main(args: Array[String]): Unit = {
    getResults();
  }

  def selectQ[T: Composite](lit: String, query: String) =
    HC.process[T](query, HPS.set(lit)).transact(xa)

  val xa = DriverManagerTransactor[Task](
    "com.mysql.jdbc.Driver",
    "jdbc:mysql://localhost:3306/orion",
    "root",
    "root"
  )
  import xa.yolo._

  val wrap: Task ~> DB.Free = new (Task ~> DB.Free) {
    def apply[A](t: Task[A]): DB.Free[A] = DB.eval(t)
  }

  val interpreter: DB ~> Task = new (DB ~> Task) {
    def apply[A](term: DB[A]): Task[A] = term match {

      case DB.SelectData() => {
        val (rendered, params) = ("data = ?", "device:q1")
        val stmt = s"SELECT topic FROM subscription WHERE $rendered"
        val result = selectQ[Option[String]](params, stmt)
        val p = result.translate(wrap)
//        val p = Process("This is me!!!!")
        val k = Task now p
        k
      }

      case DB.Eval(t) =>
        Task fail (new RuntimeException("Run time exception!!!! "))

      case DB.Fail(t) => Task fail t
    }
  }

  def getTask[A](k : DB ~> Task, p:DB.Free[A]):Task[A] = {
    Free.runFC[DB,Task,A](p)(k)
  }

  def getResults():Unit = {

    val p = DB.selectData()
    val task = Free.runFC(p)(interpreter)
    println(task.run.runLast)

  }

}
```

**Comment by tpolecat** [comment]
This is very confusing because you're introducing a type alias called `Free` that shadows `scalaz.Free`, and introducing a type parameter `Task` that shadows `scalaz.concurrent.Task`. I suggest strongly that you not do this.

`DB.selectData()` has type `DB.Free[Process[DB.Free,A]]` and when you run it you get a  `Task[Process[DB.Free,A]]` which you `.run`, giving you a `Process[DB.Free,A]` and `runLast` gives you a `DB.Free[Option[A]]` which is what you're printing out.

I think you probably don't really want to be doing any of these things. If you can describe what you're trying to do I may be able to offer a suggestion.

**Comment by iniyanp** [comment]
What I am trying to do is,  I am getting Process[Task,Option[String]] from val result = selectQ[Option[String]](stmt). 

I would like to convert this to my own Algebra which is Process[DB.Free, Option[String]]. There was a method in 

 private val wrap: Task ~> Free = new (Task ~> Free) {
    def apply[A](t: Task[A]): Free[A] = eval(t, TaskCoincidence)
  }
which does that. But when I run that through http4s, am getting 

11/01 17:58:02.589 ERROR[pool-1-thread-3] o.h.b.p.Stage - Error running route: Request(method=GET, uri=/status, headers=Headers(Host: 127.0.0.1:9000, Connection: keep-alive, Cache-Control: max-age=0, Upgrade-Insecure-Requests: 1, User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36, Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8, Accept-Encoding: gzip, deflate, sdch, Accept-Language: en-US,en;q=0.8, Cookie: _ga=GA1.1.2007576718.1476673410)
scalaz.stream.Cause$Terminated: End

so If you can suggest some other way to convert to my own algebra (DB) that would be great. Thank you so much for your help.

Thanks,
Iniyan P

**Comment by tpolecat** [comment]
I think we figured this out on another thread.

**Comment by iniyanp** [comment]
Yes. Thanks for your help. :)
