### ISSUE TITLE
Safer, more typed queries - with table description ?

### ISSUE THREAD

**Issue by fanf** [tpolecat/doobie#375]
I'm opening the ticket to track ideas and advancement about how to make queries more typesafe. 

The general feedback on Doobie is "it's awesome, but I would love to get some sureness about the type of columns or argument I'm giving". 

We don't exactly know what could be done. 

The first level of ideas is to have a way to check at compile time that the number of row returned matches the number of types given in .query, so that simple refactoring / changes in the column is checked. 

The second level of ideas is to be able to add some type annotation on columns  in the select / update to be able to check both the number of returned columns and the correctness of the types, something like:

```
sql"select id${t[Long]}, name${t[String]} from .users ...".query.list
```

The third level of ideas is to have some (simple) way to describe tables in Scala and use that in query. Contrary to Slick, the description can be simple, because we are only interest on the name of the colum and the table, the idea is only to somehow centralise these name and the mapping between the name and it's type to get more sureness at compile time: 

```
object users extends Table("users") { 
  object id extends Column[Long]("id") 
  object name extends Column[String] // or even without param if the val name is the same 
  val all = columns[users] //something like ca.mrvisser.sealerate.values[]
}

import users.{id, name}
sql"""select $id, $name from $users where ...".query.list
```

Or (idea 4) with a full blown DSL: 

```
select (users.id, users.name) from (users) where ..
```

All these ideas are simple ideas taken from people, some not even using Doobie. I don't know what is possible (my personnal wish is that something like level 3 is possible).

**Comment by tpolecat** [comment]
What I'm working on is something like what we have now, but all checked at compile-time. I'll see if I can make it public this weekend so you can see it.

**Comment by tpolecat** [comment]
Here is the [wip repo](https://github.com/tpolecat/doobie-tsql) … I will add more examples and stuff today. I have a long flight.

**Comment by coniurare** [comment]
Nice, wondered recently why doobie didn't have something like that after seeing the tsql macro in Slicks documentation.

**Comment by fanf** [comment]
I have one major wondering with that proposition: does it means that *anytime* we want to compile code with tsql, we need to have the correct DB set-up and running? Or will it be possible to somehow give a fake/mock schema in place of the real one, or somehow disable the check (not sure how it would works if db infered types are used in the inference)? 

The reason for this question is that we are using Postgres, with all the fancy and specific operations one can imagine, so it is impossible for us to use an other database for compile purpose (I mean, it is never a really good idea, but here it is just impossible). 
So now, to compile our nice compile-time-cheched code with tsql, we impose to our contributors / customers who whish to build our code base a new constraint, which is: you need to have postgres set-up and running to build Rudder (even if you don't care about the persistance layer).
Even for us, that would mean quite dramatic changes in our CI pipelines and release process (db tests are longer, and since they need a dedicated set-up with postgres (yes, obviously ;), they are runs on specific boxes and not for all package builds). 
(these certainly are common arguments raised when talking about compile time dependency to a db, I don't know what is the canonical answers)

**Comment by KadekM** [comment]
Also to add to @fanf point (just noting for completnes, I haven't formed opinion yet), they would need to run database migrations on the database the compiler is hitting.

**Comment by tpolecat** [comment]
Yeah I was thinking it could write a cache file that you commit to source control, then it would use that as a fallback if the database isn't available.

**Comment by tpolecat** [comment]
But I should note that your schema and migrations should be committed as source as well, and setting up Postgres on Travis at least is trivial. 

Migrations just need to run before compilation, which is easy to arrange.

**Comment by KadekM** [comment]
Yep I dont see it as a big deal. I would most likely push for this in our
infrastructure...benefits are too big : )

**Comment by fanf** [comment]
The cache (committed in source control) would be perfect.

And of course the schema is in source control, but I want to make
potentially interest people the simplest possible built experience. An
opt-in solution, where people dealing with DB stuff and our
CI-with-long-tests can have fully validated queries but where other groups
don't even know that the thing exists would be the best of both world.

Oh, and I'm pretty sure there is examples where you just want to
demo/compile some stuff on a clean machine (even a windows/Mac one!)
without db or even network access, and need a way to do it successfully :).
I know, horror stories ;)

Le 1 nov. 2016 7:37 PM, "Marek Kadek" <notifications@github.com> a écrit :
>
> Yep I dont see it as a big deal. I would most likely push for this in our
> infrastructure...benefits are too big : )
>
> On Wed, Nov 2, 2016, 06:59 Rob Norris <notifications@github.com> wrote:
>
> > But I should note that your schema and migrations should be committed as
> > source as well, and setting up Postgres on Travis at least is trivial.
> >
> > Migrations just need to run before compilation, which is easy to
arrange.

**Comment by tpolecat** [comment]
If you want to try this out the project is [doobie-tsql](https://github.com/tpolecat/doobie-tsql) and there is 0.1-SNAPSHOT that works with 0.3.0 for 2.11 (only).

**Comment by tpolecat** [comment]
I just updated doobie-tsql for 0.4.2-SNAPSHOT if you want to try it. I'm going to open an issue over there about offline use and close this one.
