### ISSUE TITLE
IOLite has no Applicative instance for Cats

### ISSUE THREAD

**Issue by gatorcse** [tpolecat/doobie#378]
As discussed on the Gitter channel, it appears that IOLite has no applicative right now.

**Comment by tpolecat** [comment]
(for cats … it needs a `Monad` instance.)

**Comment by guersam** [comment]
As `IOLite` has instances for `fs2.util.{ Catchable, Suspendable }` which are fs2 monads, cats monad can be derived via [`import fs2.interop.cats._`](https://github.com/functional-streams-for-scala/fs2-cats).

**Comment by guersam** [comment]
The actual problem is #369. For example:
```scala
  import fs2.interop.cats._
  import cats.implicits._
  import cats._
  import doobie.util.iolite.IOLite

  Applicative[IOLite].replicateA(3, IOLite.pure(1)) // works
  IOLite.pure(1).replicateA(3) // not works
```

**Comment by guersam** [comment]
Oops, cats doesn't provide `replicateA` syntax at all. `fs2-cats` just works in this case.

```scala
1.pure[IOLite]
```

**Comment by tpolecat** [comment]
Ok I think this isn't a bug.
