### ISSUE TITLE
Termination End Exception

### ISSUE THREAD

**Issue by iniyanp** [tpolecat/doobie#381]
Basically, From doobie I am getting a result of Type Process[Task, String] , then am converting into my monad. which is DB and then lifting it into Task. so the resultant type from my interpreter is 

Task[Process[DB.Free, String]]

and in my DSL, I am calling that interpreter. and trying to do runLast on Process[DB.Free, String]. 

That time I am facing Termination END exception.

whereas If I replace doobie result with 

val result = Process eval (Task now "This is me...")

works perfectly fine. 

[DoobieProgram.zip](https://github.com/tpolecat/doobie/files/579190/DoobieProgram.zip)

P.S I am using a small mysql table 'topic' 

create table topic(name varchar(1000), state varbinary(1000) , primary key (name));
insert into topic values('topic4',HEX('a'));

and the connection parameter I have mentioned in First.scala file.  It has only 2 files.

1. First.Scala ( This is the main program )
2. DB.Scala (This my Algorithm)

**Comment by tpolecat** [comment]
Can you minimize this at all? It's a lot of stuff to wade through.

**Comment by iniyanp** [comment]
Sure. Let me try

**Comment by iniyanp** [comment]
I have removed most of the classes that doesn't need to be here. PFA

[DoobieProgram.zip](https://github.com/tpolecat/doobie/files/579223/DoobieProgram.zip)

**Comment by iniyanp** [comment]
Could you please provide some workaround. I have successfully moved all the other parts of the project into Doobie. Thank you very much for your help.

Thanks,
Iniyan P

**Comment by tpolecat** [comment]
This code is extremely confusing.

**Comment by iniyanp** [comment]
@tpolecat DB is My monad, I am converting the results that are coming from Doobie (Type is Process[Task,String] ) into Process[DB.Free, String] since my interpreter methods returns of that type.

In Engine.scala, I am trying to do runLast on Process[DB.Free, String]. That time I am getting Terminated End exception. whereeas If I replace doobie result with 
val result = Process eval (Task now "This is me...") and follow the same procedure, it 
works perfectly fine.

**Comment by tpolecat** [comment]
The problem is that you are not implementing `Catchable[DBIO]` correctly. You need to delegate `.attempt` to the wrapped `Task` inside `Eval`, but you have forgotten that you have a `Task` and have no way of doing this. If you specialize `Eval` to `Task` you can do it, otherwise you need to carry along evidence that it's a `Functor` and `Catchable`. The `Coincidence` thing didn't make sense to me so I deleted it.

This works.

```scala
package pubsub

import scalaz.stream.Process
import scalaz.{Catchable, Coyoneda, EitherT, Free, Functor, Monad, \/, ~>}
import scalaz.concurrent.Task

sealed trait DB[A]

object DB {
  type Free[A] = scalaz.Free.FreeC[DB, A]


  // TODO generalize the following to HList
  final case class Select[A]()
    extends DB[Process[DB.Free, A]]
  def select[A](): DB.Free[Process[DB.Free, A]] =
    Free.liftFC[DB, Process[DB.Free, A]](Select())

  final case class Eval[A](fa: Task[A]) extends DB[A]
  def eval[A](fa: Task[A]): DB.Free[A] =
    Free.liftFC[DB, A](Eval(fa)) // TODO find a way to restrict this to only interpreters

  final case class Fail[A](t: Throwable) extends DB[A]
  def fail[A](t: Throwable): DB.Free[A] = Free.liftFC(Fail(t))

  implicit def freeMonad: Monad[Free] = Free.freeMonad[Coyoneda[DB, ?]]

  // TODO make this code more generic so it can be shared with dbcast
  implicit def dbCatchable: Catchable[DB.Free] = new Catchable[DB.Free] {

    def attempt[A](action: DB.Free[A]): DB.Free[Throwable \/ A] = {
      val et = action.foldMap[EitherT[DB.Free, Throwable, ?]](
        new (Coyoneda[DB, ?] ~> EitherT[DB.Free, Throwable, ?]) {
          def apply[B](cy: Coyoneda[DB, B]) = cy.fi match {
            case DB.Fail(t) => EitherT.left(freeMonad.point(t))
            case Eval(t)    => EitherT(eval(t.map(cy.k).attempt))
            case db =>
              EitherT.right[DB.Free, Throwable, B](Free.liftFC(db) map cy.k)
          }
        })(Functor[Coyoneda[DB, ?]], EitherT.eitherTMonad[DB.Free, Throwable])

      et.run
    }

    def fail[A](t: Throwable): Free[A] = DB.fail(t)
  }

}
```

and

```scala
package pubsub

import doobie.free.preparedstatement.PreparedStatementOp
import doobie.imports._
import doobie.util.transactor.DriverManagerTransactor

import scalaz._
import scalaz.concurrent.Task

/**
  * Created by paramin on 11/8/16.
  */


class RDS  (xa: Transactor[Task]) {

  import DB._
  def selectQ[T: Composite](
                             query: String,
                             builtParam: scalaz.Free[
                               ({ type λ[β] = Coyoneda[PreparedStatementOp, β] })#λ,
                               Unit]) = {
    HC.process[T](query, builtParam).transact(xa)
  }

  val interpreter: DB ~> Task = new (DB ~> Task) {
    def apply[A](term: DB[A]): Task[A] = term match {

      case Select() =>
        val stmt =
          s"SELECT name FROM topic WHERE name = ?"

        val builtParam = HPS.set(1, "topic4")
        val result = selectQ[String](stmt, builtParam)
        //        val result = Process eval (Task now "This is me...")
        val p1 = Task.delay(result.translate(wrap))
        //        val p2 = Task.delay(p1)
        p1

      case DB.Eval(t) => t

      case DB.Fail(t) => Task fail t
    }
  }

  private val wrap: Task ~> DB.Free = new (Task ~> DB.Free) {
    def apply[A](t: Task[A]): DB.Free[A] = DB.eval(t)
  }

}

object First {
  import DB._

  private def bootStrapRDS() = {

    val xa = DriverManagerTransactor[Task](
      "com.mysql.jdbc.Driver",
      "jdbc:mysql://localhost:3306/orion",
      "root",
      "root"
    )
    new RDS(xa)
  }

  def state(name:String): DB.Free[Option[String]] =
    for {
      rs <- select[String]()
      optState <- {
        val k = rs.runLast(DB.freeMonad, DB.dbCatchable)
        k
      }
    } yield optState

  def main(args: Array[String]): Unit = {
    val db = bootStrapRDS()
    val k = state("ignored") foldMap (Coyoneda liftTF db.interpreter)
    println(s"Message is ${k.run.get}")
  }

}
```

What you are doing here is very roundabout and I assume there is some higher purpose. But it's very difficult to follow.

**Comment by iniyanp** [comment]
@tpolecat Nice. It works fine. Yes. Instead of generalizing Eval  will have specific to Task. This was an existing code base and I was trying to replace DB operations using Doobie. Since It was working fine for normal Process eval Task.now("Hello") and existing DB operations, I thought Doobie might be causing some issues. Thank you very much for your help.

Thanks,
Iniyan P
