### ISSUE TITLE
Giving thanks for Doobie!

### ISSUE THREAD

**Issue by coltfred** [tpolecat/doobie#386]
I know I'm a day late, but I just wanted to let @tpolecat know how thankful I am for Doobie! This library is awesome, your help is awesome and you're awesome! Thanks for all you do Rob!

**Comment by leifwickland** [comment]
Thanks for all you do, @tpolecat! You're a freakin' one man army of awesome making the world a purer place.

**Comment by KadekM** [comment]
Thank you @tpolecat , doobie is awesome, and your attitude towards newcomers (to FP) is unmatched 👍

**Comment by chrisphelps** [comment]
I have not used doobie, but I've heard you speak on it a couple times. So, thanks for making something that helped me to learn stuff!

**Comment by tpolecat** [comment]
Thanks everyone! I and the doobie contributors really appreciate your encouragement. Great things on the way!

**Comment by xavier-fernandez** [comment]
Thank you for Doobie!

:)
