### ISSUE TITLE
improve performance of finding out the caller of an sql interpolator 

### ISSUE THREAD

**Issue by dwunsch** [tpolecat/doobie#390]
https://github.com/tpolecat/doobie/blob/f94736c15bd1764f324ea74e85967562f609ed8d/yax/core/src/main/scala/doobie/syntax/string.scala#L19

seems to waste about 15% of my cpu cycles in a massive-insert scenario.

making it lazy could help, but using a source location macro would be more elegant and event faster.

**Comment by dwunsch** [comment]
something like this should work:
https://github.com/ritschwumm/scutil/blob/25211a212519d8d07e1dc3b86ab2620c7f4a9528/sub/base/src/main/scala/scutil/lang/SourceLocation.scala

**Comment by tpolecat** [comment]
Cool I'll give that a try. Thanks!
