### ISSUE TITLE
more memleak woes

### ISSUE THREAD

**Issue by dwunsch** [tpolecat/doobie#394]
i'm trying to stream inserts into a postgres db, and quickly running out of memory.

what i am doing:
i have one task writing into a ```scalaz.stream.async.boundedQueue```, ```queue.dequeue``` is mapped to ```Update0``` values for an INSERT, chunked by 10000 and fed into postgres like this:
```
dequeue
 .map(makeInsert) // it => sql"""something""".update
.chunk(10000)
.evalMap(
   _.traverse(_.run).transact(transactor)
)
.run
.unsafePerformSync
```

in a heap dump i see millions of ```meta$Meta$$anon$1``` instances and the same amount of
```meta$Meta$$anonfun$1```, ```meta$BasicMeta$$anonfun$2```, 
```meta$Meta$$anon$1$$anonfun$xmap$1```, ```meta$Meta$$anon$1$$anonfun$xmap$2```, ```meta$Meta$$anon$1$$anonfun$xmap$3```, ```meta$LowerPriorityImplicits$$anonfun$unaryProductMetaNonNullable$1``` and ```meta$LowerPriorityImplicits$$anonfun$unaryProductMetaNonNullable$2```

i checked some of these instances, and the nearest GC root is a ```ClassLoader``` referencing the ```meta$Meta$``` ```MODULE``` referencing a ```HashSet``` "instances" (```HashTrieSet```) referencing said ```meta$Meta$$anon$1```. 

interestingly almost (!) the same code seems to have been working with doobie 0.3, with doobie 0.3.1-SNAPSHOT it does not. i went back a few commits and tried which that, no change.

**Comment by dwunsch** [comment]
hah, got it: ```sql""``` contained ```${foo}``` for some ```case class Foo(x:String)``` _without_ a custom ```Meta```. somehow doobie conjured a Meta for this and called ```Meta#reg``` with it a lot of times. it seems this ```Meta``` instance does not have a useful ```equals``` method so https://github.com/tpolecat/doobie/blob/series/0.3.x/yax/core/src/main/scala/doobie/util/meta.scala#L179 filled the ```instances``` field with millions of ```Meta``` instances for the same case class.

manually defining a ```Meta``` for ```Foo``` made the problem go away.

**Comment by tpolecat** [comment]
Aha, ok that makes sense. I need to fix that. That's the only side-effect in all of doobie and I knew it would end up being a problem at some point. Thanks so much for tracking it down.

**Comment by tpolecat** [comment]
This is due to an temporary hack from cats integration that never got implemented correctly. https://github.com/tpolecat/doobie/commit/6c7a6eb22c99ecef8d66858d8577d88ee8be19f3#diff-cac5ac4d03df16e8fa1722d0ce7f748cL155
