### ISSUE TITLE
Query check fail for Oracle

### ISSUE THREAD

**Issue by kantefier** [tpolecat/doobie#401]
Every query check for Oracle results in such failure. I suspect that ordinal 104 is RowID according to [this (see Table 3-2 "External Data Types and Codes")](https://docs.oracle.com/cd/E11882_01/appdev.112/e10646/oci03typ.htm#LNOCI16271)

> scala> sql"select 42 from dual".query[Int].check.unsafePerformSync
> 
>   select 42 from dual
> 
>   ✕ SQL Compiles and Typechecks
>     - doobie.enum.jdbctype$JdbcType: invalid ordinal: -104

**Comment by ChristopherDavenport** [comment]
Can confirm this bug. Any typechecked query results in an error.

**Comment by tpolecat** [comment]
It's because Oracle is returning type constants that are outside the specification. I guess I could just have an `Unknown` constructor to handle those cases
