### ISSUE TITLE
NoSuchMethodError using ScalaTest module

### ISSUE THREAD

**Issue by cranst0n** [tpolecat/doobie#407]
Using 0.3.1-M3 `doobie-core-cats`, and `doobie-scalatest` for my unit tests:
```
[info]   java.lang.NoSuchMethodError: doobie.util.query$Query0.outputAnalysis()Lscalaz/Free;
[info]   at doobie.scalatest.QueryChecker$class.checkOutput(QueryChecker.scala:50)
...
```

**Comment by tpolecat** [comment]
Oh, try it with `doobie-scalatest-cats`.

**Comment by cranst0n** [comment]
Doh! Guess I yaxxed that one up pretty good.

**Comment by tpolecat** [comment]
Well I set up a test project to see if I could reproduce it so I didn't notice either ;-)
