### ISSUE TITLE
HikariTransactor

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#41]

**Comment by prange** [comment]
Any quick workaround for using HickaryCP?

**Comment by tpolecat** [comment]
Hi @prange, I want to build an algebra and free monad so you can do all the configuration, etc., in an API that fits with the rest of doobie, but yeah for now just hack something up based on that example.

FYI at this point we're really close to v0.2 so your best bet is to build and publish-local and use the snapshot.

**Comment by prange** [comment]
Yes, i have cloned the 0.2-SNAPSHOT and will use that for the moment...
