### ISSUE TITLE
doobie artefacts contain doobie-core

### ISSUE THREAD

**Issue by eikek** [tpolecat/doobie#410]
Hello,
I use the following dependencies:
```scala
val `doobie-core` = "org.tpolecat" %% "doobie-core-cats" % "0.3.1-M3"
val `doobie-h2` = "org.tpolecat" %% "doobie-h2-cats" % "0.3.1-M3"
val `doobie-hikari` = "org.tpolecat" %% "doobie-hikari-cats" % "0.3.1-M3"
```
and these are fetched from maven central and all three are more than 4M
```
HEAD http://repo1.maven.org/maven2/org/tpolecat/doobie-hikari-cats_2.12/0.3.1-M3/doobie-hikari-cats_2.12-0.3.1-M3.jar
HTTP/1.1 200 OK
Content-Length: 4421870

HEAD http://repo1.maven.org/maven2/org/tpolecat/doobie-core-cats_2.12/0.3.1-M3/doobie-core-cats_2.12-0.3.1-M3.jar
HTTP/1.1 200 OK
Content-Length: 4415040

HEAD http://repo1.maven.org/maven2/org/tpolecat/doobie-h2-cats_2.12/0.3.1-M3/doobie-h2-cats_2.12-0.3.1-M3.jar
HTTP/1.1 200 OK
Content-Length: 4446548
```
I looked into the jar files and all seem to contain doobie-core. Is this intended or should I maybe use different library imports?

Thanks a lot for doobie!! 
Regards,
Eike

**Comment by tpolecat** [comment]
Thanks for reporting this. I'll investigate.

**Comment by tpolecat** [comment]
Confirmed, no idea why this is happening.

**Comment by fiadliel** [comment]
The JAR files seem to have the correct contents with `sbt package`, but not after running `sbt publishLocal`. Also, `sbt publishLocal` has the correct contents if the OSGI plugin is removed. Definitely time for something over one's head :)

**Comment by tpolecat** [comment]
Aha, that's a very good clue. Thanks for figuring that out!
