### ISSUE TITLE
How can I set postgres schema search path for a connection?

### ISSUE THREAD

**Issue by Daenyth** [tpolecat/doobie#411]
I'm trying to run a postgres query with a modified search_path. I'd like it to be set once on my transactor and then apply to all queries in a connection. Barring that, if I can do something with minimal boilerplate like `sql"""foo""".query[A].withSchema("abc")` that would be reasonable

**Comment by Daenyth** [comment]
> https://gitter.im/tpolecat/doobie?at=585033457a58ca605549fc85

> @Daenyth you can probably set this as an option for your connect URL. If not you say `val setSchema = sql"set SEARCH_PATH = myschema".update.run` and then instead of `stuff.transact(xa)` you can say `(setSchema *> stuff).transact(xa)`. As a last resort you can implement a custom transactor that does this in the "before" step.

**Comment by tpolecat** [comment]
On 0.4.2 you can now peel off a new `Transactor` with a modified `before` action.

```scala
val setSchema = sql"set SEARCH_PATH = myschema".update.run.void
val xa2 = Transactor.before.modify(xa, _ *> setSchema)
```
