### ISSUE TITLE
Doobie 0.3.0 build for Scala 2.12.0 or Scala.12.1

### ISSUE THREAD

**Issue by zarthross** [tpolecat/doobie#412]
Can we get a official build out for Scala 2.12?  I've only located artifacts for 2.12.0-M3 out on maven.  I know Doobie 0.3.1 already has M3 builds out, but I would rather wait until its ready to start using it for my projects and doobie is my only dependency holding me back on 2.11.

**Comment by tpolecat** [comment]
Just release 0.3.0a for 2.12 … give it a try. May take a short while to appear.

**Comment by zarthross** [comment]
Works great!  Thank you!
