### ISSUE TITLE
Allow fragments.whereAndOpt to compose with non-optional filters too

### ISSUE THREAD

**Issue by Daenyth** [tpolecat/doobie#414]
I have a query like this:
```scala
val a: String
val b: Option[String]
val q = fr"SELECT foo FROM bar WHERE a = $a" ++ whereAndOpt(bOpt.map(b => fr"b = $b"))
```

This generates an invalid query with `WHERE a = ? WHERE b = ?`

It seems like my two options are to do:
```scala
val q = fr"SELECT foo FROM bar" ++ whereAndOpt(Some(fr"a = $a"), bOpt.map(b => fr"b = $b"))
// or
val q = fr"SELECT foo FROM bar WHERE a = $a" ++ bOpt.map(b => fr"$b = $b").getOrElse(fr"")
```

Is there a better way? What about this?

```scala
// in Fragment
def ++(other: Option[Fragment]): Fragment = other.map(this ++ _).getOrElse(this)
```

**Comment by tpolecat** [comment]
I think I would do it this way. `Fragment` is a monoid so you can use `foldMap` here.

```scala
fr"SELECT foo FROM bar WHERE a = $a" ++ bOpt.foldMap(b => fr"AND b = $b")
```

**Comment by tpolecat** [comment]
Closing, feel free to re-open if this didn't answer your question.

**Comment by Daenyth** [comment]
Your approach is reasonable. Adding a combinator just for this wouldn't be
any more readable than that
