### ISSUE TITLE
Sources jars for 0.3.1-M3 are empty

### ISSUE THREAD

**Issue by japgolly** [tpolecat/doobie#418]
See http://repo1.maven.org/maven2/org/tpolecat/doobie-core_2.11/0.3.1-M3/

**Comment by japgolly** [comment]
Same for M1 and M2.

**Comment by tpolecat** [comment]
Thanks, this is probably because all the source ends up in `src_managed` and it doesn't get picked up by default. I'll see if I can fix it.
