### ISSUE TITLE
Add option to disable auto-transactions

### ISSUE THREAD

**Issue by japgolly** [tpolecat/doobie#421]
Hi. Doobie is pretty cool but something I find frustrating about it is that the transactors wrap entire `ConnectionIO`s in transactions. Personally I'd much prefer an option to disable this usage assumption and then manage transactions directly on ConnectionIO instances.

For example, using this:
```scala
  implicit class ConnectionIOExt[A](private val self: ConnectionIO[A]) extends AnyVal {

    def inTransaction: ConnectionIO[A] =
      getAutoCommit.flatMap(ac =>
        if (ac) runInTransaction else self)

    private def runInTransaction: ConnectionIO[A] =
      for {
        _      <- setAutoCommit(false)
        result <- self
        _      <- commit
        _      <- setAutoCommit(true)
      } yield result
  }
```

I find it more expressive for my needs to write:
```scala
(doStuff *> doMoreStuff).inTransaction

(doStuff *> doMoreStuff).inTransaction *> lookImInADifferentTransaction
```

In order to workaround the library not supporting this, I added this:
```scala
package doobie.japgolly

import doobie.imports._
import doobie.util.transactor.Transactor
import java.sql.Connection
import scalaz.{Catchable, Free, Monad}

object DoobieHack {

  def disableAutoTransactions[M[_]: Catchable : Capture : Monad](orig: Transactor[M]): Transactor[M] =
    new Transactor[M] {
      override val before: ConnectionIO[Unit] = Free.pure(())
      override val after: ConnectionIO[Unit] = before
      override val oops: ConnectionIO[Unit] = before
      override val connect: M[Connection] = orig.connect
    }
}
```

Notice that I had to change the package to start with `doobie` do that I could access `connect`.

**Comment by japgolly** [comment]
Also, I tried to override trans like this:

```scala
  def disableAutoTransactions[M[_]: Catchable : Capture : Monad](orig: Transactor[M]): Transactor[M] =
    new Transactor[M] {
      override val before: ConnectionIO[Unit] = Free.pure(())
      override val after: ConnectionIO[Unit] = before
      override val connect: M[Connection] = orig.connect

      override object trans extends (ConnectionIO ~> M) {
        private def safe[A](ma: ConnectionIO[A]): ConnectionIO[A] =
          ma onException oops ensuring always
        def apply[A](ma: ConnectionIO[A]): M[A] =
          connect.flatMap(c => safe(ma).transK[M].run(c))
      }
    }
```
for increased efficiency but Scala doesn't allow overriding inner objects. If you could open this up a bit that would be awesome. Or actually I can submit a PR if you like?

**Comment by tpolecat** [comment]
So, yeah `Transactor` is kind of a bogus abstraction, but the whole point is to add transaction semantics. If that's not what you want then you might want to create your own thing like `trait Connector[M[_]]` with none of the transaction stuff and pimp `.connect(c)` onto `ConnectionIO` and `Process[ConnectionIO`.

**Comment by tpolecat** [comment]
Just an update, in 0.4.2 you can do this by peeling off a new transactor with the `before` action set to a no-op.

`val newXa = Transactor.before.set(xa, FC.unit)`

**Comment by japgolly** [comment]
Cool. Doobie's just happily purring along in the background, I haven't touched it in a while. Next time I do I'll check out this new way

**Comment by tpolecat** [comment]
> Doobie's just happily purring along in the background, I haven't touched it in a while.

That's great to hear, man. 👍

**Comment by adelbertc** [comment]
Best kind of code is code you don't think about ;)
