### ISSUE TITLE
Nullability via Maybe (or other?)

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#43]

**Comment by prange** [comment]
Would this also mean that unique would yield an Option? If not, what would the idiomatic way to get 0 or 1 rows from a table?

**Comment by tpolecat** [comment]
This issue is just to support `scalaz.Maybe` for nullable values (they're all mapped as `Option` right now).

Right now there is not a `.option` method on `Query`, which is what you're asking for. A workaround for now is to say `.list.headOption`, which will not fail if there is more than one row returned (`.option` will, but it's not there yet).

**Comment by prange** [comment]
Yes, after some more code reading and a bit trying i figured out that its two totally different things. I am all for using Maybe though. (You depend on Scalaz anyway, go all the way i say)
