### ISSUE TITLE
Don't force IOLite usage in scalatest bindings

### ISSUE THREAD

**Issue by Daenyth** [tpolecat/doobie#448]
Because `QueryChecker` wants a `override def transactor: Transactor[IOLite]`, people not using IOLite in their main code base are forced to change their code to use things like `def dbTransactor[M[_]: Monad: Catchable: Capture]: Transactor[M] = ???` in their configuration object, just so that it's usable in both real code and test, whereas I'd rather `def dbTransactor: Transactor[Task]`. This is especially impactful for users not as familiar with scala.

It should suffice to change `trait QueryChecker { def transactor: Transactor[IOLite] }` to be `trait QueryChecker[M[_]: Monad: Catchable: Capture] { def transactor[M]: Transactor[M] }`

**Comment by tpolecat** [comment]
Will also need to provide `M[A] => A` since it needs to side-effect to perform actual work.

**Comment by Daenyth** [comment]
If there's `M ~> Future` then we could use scalatest 3's new async stuff
