### ISSUE TITLE
Unclear requirements of sql string building

### ISSUE THREAD

**Issue by prange** [tpolecat/doobie#45]
I have 
```scala
case class Email(value:String)
case class PlayerId(value:String)
case class Player(id:PlayerId, email:Email)
```

I am trying to construct an sql string using `sql`
```scala
def insertPlayer(p: Player): ConnectionIO[Int] = {
    sql"""
          INSERT INTO players
          VALUES ($p.id.value, $p.email.value)
    """.update.run
  }
```
The above requires an implicit Atom[Player] in scope, which as i understand, is a contradiction, since a Player is not an atom but a product of PlayerId and Email. 

Of course
```scala
def insertPlayer(p: Player): ConnectionIO[Int] = {
    val id = p.id.value
    val email = p.email.value
    sql"""
          INSERT INTO players
          VALUES ($id, $email)
    """.update.run
  }
```
runs fine.

Is my understanding fundamentally wrong? Or maybe i missed some documentation? Or might this jsut be a bit unclear for newbies on noobie?

**Comment by prange** [comment]
There is of course a bug in my first version of the function, putting curlies around the variables resolves the problem. But it would still be interesting to know more about the rationale of the design of the sql resolver.

**Comment by tpolecat** [comment]
The `sql` interpolator works like any other string interpolator in Scala. The interpolated values require an `Atom` instance, which means they can be mapped to a column value. The documentation in process for v0.2 will explain this in a bit more detail. Did you have a specific question?

**Comment by prange** [comment]
After some thinking it is pretty obvious to take in atom instances, that makes it nice and typesafe.
