### ISSUE TITLE
AnalysisSpec doesn't follow specs2 execution flow

### ISSUE THREAD

**Issue by nigredo-tori** [tpolecat/doobie#454]
`check` in `AnalysisSpec` seems to run its queries before it returns, only using the resulting `Fragments` for outputting results. This circumvents specs2 execution flow, meaning that some of its features don't work as expected. For example:

```scala
import doobie.imports._
import doobie.specs2.imports._
import doobie.h2.imports._
import org.specs2.mutable.Specification
import org.specs2.specification.BeforeAll

class Spec extends Specification with AnalysisSpec with BeforeAll {

  // Setup
  val initQ = sql"create table some_table (value varchar not null)".update
  val targetQ = sql"select * from some_table".query[String]

  val transactor: Transactor[IOLite] = H2Transactor[IOLite](
    "jdbc:h2:mem:",
    "sa",
    ""
  ).unsafePerformIO

  // The test itself
  check(targetQ)

  // A hook for database initialization
  def beforeAll() = initQ
    .run
    .transact(transactor)
    .unsafePerformIO
}
```

This fails, since `beforeAll` is executed _after_ the test query:
```
Table "SOME_TABLE" not found
```
An obvious workaround in this particular case is running `beforeAll` explicitly without relying on hooks.

A proper solution would probably have to deal with dynamically generating fragments. I'm not proficient enough in specs2 to find a way to add new fragments from an existing one, though.

Tested with doobie v0.4.0, specs2 v3.8.4

**Comment by tpolecat** [comment]
You could do the setup in your `transactor` definition. I guess this isn't uncommon and should be documented.

**Comment by ClementMalaingre** [comment]
Adding my two cents : a workaround is not to use BeforeAll as in specs 2 but to call the method beforeAll in the constructor. It's actually what specs2 tests do in their own code :
```
trait QueriesTypecheckSpec extends org.specs2.mutable.Specification with DoobieAnalysisSpec with RunningPostgres {

  // this needs to be started as soon as the specification class gets instantiated
  // because Doobie creates specification fragments *after* executing the test code
  beforeAll

  def tagged(name: String)(fs: =>Fragments): Fragments =
    section(name) ^ fs ^ section(name)

  lazy val transactor: Transactor[IOLite] =
    PostgreSQLDatabase.createUnsafe.transactor.transactorIOLite
}
```

@etorreborre mentionned that a not-well known feature of specs2 might help with this issue : [Online specs](https://etorreborre.github.io/specs2/guide/SPECS2-3.8.9/org.specs2.guide.CreateOnlineSpecifications.html)
