### ISSUE TITLE
Create pure only Transactor for testing

### ISSUE THREAD

**Issue by coltfred** [tpolecat/doobie#460]
When testing it would often be useful to inject an arbitrary value as the "result of a database call".

Consider the following:

```
def createUser(req: Request, transactor: Transactor[Task],  createUserInDb: ConnectionIO[User]): Task[Response] 
```

If you want to test this method you have to have a real transactor. One solution is to instead take `createUserInDb` as a Task[User] and use `Task.point`, which would work, but means "transacting" the ConnectionIO earlier and also makes all the APIs more Task focused.

Is there a better way inject pure values or refactor my API? Would a Transactor that won't talk to the DB be a reasonable solution to this problem?

Thanks!

**Comment by coltfred** [comment]
Something like this was proposed in gitter:
```
val noopXa = new Transactor[Task] {
    val doNothing = ().pure[ConnectionIO]
    override protected def before = doNothing
    override protected def after = doNothing
    override protected def always = doNothing
    override protected def connect: Task[Connection] = Task.now(null)
  }
```

Then I could pass in a pure value wrapped in a ConnectionIO and the noopXa in a test to "mock". Is this a good idea? Are there better ideas?

**Comment by tpolecat** [comment]
So, yeah if you have a no-op transactor like above and a `createUserInDb` that just points a user then it will work fine; as long as you don't actually do anything with the connection it can be null.

Of course at this point you're not testing much. Would it work to use an in-memory H2 database or something here?

**Comment by tpolecat** [comment]
FWIW in the 0.4.2 snapshot you can construct such a thing pretty easily. `Transactor` is now a case class with a `strategy` field for before, after, onError, and finally ops that you can void out; and there is a `Transactor` constructor that just wraps an existing connection.

```scala
scala> val s = doobie.util.transactor.Strategy(FC.unit, FC.unit, FC.unit, FC.unit)
s: doobie.util.transactor.Strategy = Strategy(Return(()),Return(()),Return(()),Return(()))

scala> val xa = Transactor.fromConnection[IOLite](null).copy(strategy = s)
xa: doobie.util.transactor.Transactor[doobie.imports.IOLite,java.sql.Connection] = Transactor(null,doobie.util.transactor$Transactor$$$Lambda$1325/1012960848@5bd69da0,doobie.free.KleisliInterpreter$$anon$10@3cbe20f0,Strategy(Return(()),Return(()),Return(()),Return(())))
```

**Comment by coltfred** [comment]
@tpolecat Well, it reality it can be quite helpful to be able to just return a pure value for testing to ensure the rest of the business logic in the Http4s route is correct. I can use H2 in plenty of cases, but I cannot use it when the queries have postgres specific features in them.

**Comment by ktonga** [comment]
@coltfred I use a few PG specific features too, such as JSONB fields everywhere so testing against H2 was a PITA. I decided to test all my database related logic against a dockerized Postgres and it works like a charm. I recommend this small testing library https://github.com/whisklabs/docker-it-scala
