### ISSUE TITLE
Different handling of NULL columns of primitive types

### ISSUE THREAD

**Issue by unoexperto** [tpolecat/doobie#462]
It's not bug per se but more discussion of what to do. I actually had similar issue when I (internally) maintained https://github.com/scalikejdbc/scalikejdbc

Say we have following `Meta`

```
implicit val metaPartialDate: Meta[PartialDate] = implicitly[Meta[Int]].xmap(
  dbv => PartialDate.fromInt,
  v => v.toInt)
```

If we use this meta when we deserialize class such as `case class Test(pdate: Option[PartialDate])` zero will be passed to `PartialDate.fromInt` for rows with NULL value causing exception (in my case).

As result we never reach `.wasNull` in https://github.com/tpolecat/doobie/blob/fs2/yax/core/src/main/scala/doobie/util/atom.scala#L65

Of course I can change metas to not to fail when I get zero for primitive types but it looks hacky, like leakage of JDBC-specific behavior to user's code. My rationale is that I use `Meta[Int]` to create my Meta. I assume JDBC business is already dealt with. Perhaps we can do one of following:

1. Call `ResultSet.getObject` in `Atom.fromScalaTypeOption` before calling `.wasNull` and `A.unsafeGet`. Will there be performance hit ? Don't know.
2. Keep reference to source `Meta` in `Meta` when we create new one with `xmap`. Use it to call `A.parent.unsafeGet` before calling `.wasNull`. Will there be performance hit ? Don't know either.
3. Add `def nmap[B: TypeTag](f: (A, Boolean) => B, g: B => A): Meta[B]` to `Meta` so we can handle NULL in user's code.

Thoughts ?

**Comment by tpolecat** [comment]
Yes the problem is that it performs the mapping before doing the null check. I have a new design that doesn't do this but for now we have to work with the existing setup. Note that this is only an issue if the zero value for the primitive type is invalid, as it is in your case, because you have to distinguish null (which is ok) from `0` (which is not) but they look the same from `Meta`'s point of view.

The solution in your case is to create two atoms. If you see a zero here it's because there is one in your database. You will never see "null zero".

```
implicit val FooAtom: Atom[Foo] = Atom[Int].xmap(...)
implicit val OptionFooAtom: Atom[Option[Foo]] = Atom[Option[Int]].xmap(...)
```

**Comment by tpolecat** [comment]
Leaving open to add as a doc issue.

**Comment by unoexperto** [comment]
Could you share your ideas on new design please ? Is it partially implemented in some branch already ?

**Comment by tpolecat** [comment]
@unoexperto in a handwavey way the current design for reading is `(ResultSet, Int) => A` and then when you `xmap` the read extension is just `andThen`'d onto the right side. So you build up a function that reads all the way to your final type, then you go back and ask `.wasNull` on the `ResultSet` as step two.

The new design instead is `Coyoneda[(ResultSet, Int) => ?, A]` which is `((ResultSet, Int) => I, I => A) forSome { type I }` which separates the low-level read from its translation, which lets you do the null check before applying transformations. So the mapping function never has to see `null`.

**Comment by unoexperto** [comment]
Excellent ! What's ETA for new initial version ?

**Comment by tpolecat** [comment]
It's what I'm using with [doobie-tsql](https://github.com/tpolecat/doobie-tsql) and something like it might make it back into the meta/atom/composite stack, or that might all go away. Not quite sure yet.
