### ISSUE TITLE
doobie-contrib-postgresql, doobie-contrib-specs2 latest versions

### ISSUE THREAD

**Issue by jinilover** [tpolecat/doobie#463]
I am using doobie-core 0.4.1 for fragment support.  But the doobie-contrib-postgresql, doobie-contrib-specs2 versions are still 0.3.0.  
There seems compatibility issue between doobie-contrib-specs2 and doobie-core.  
doobie-contrib-postgresql 0.3 looks fine with doobie-core 0.4.1.  Will there an new release for both of these extensions?
Thanks

**Comment by tpolecat** [comment]
Hi, see the [release notes for 0.4.0](https://github.com/tpolecat/doobie/blob/series/0.4.x/CHANGELOG.md#0.4.1) … these artifacts and their associated packages have been renamed.
