### ISSUE TITLE
Make `ConnectionIO` traversable

### ISSUE THREAD

**Issue by 13h3r** [tpolecat/doobie#465]
There are some cases when you need to have `ConnectionIO` traversable. Here it is an example from gitter:

```scala
  {
    HC.prepareStatement("insert into ...") {
      val r: ConnectionIO[PreparedStatementIO[Int]] = HC.prepareStatement("select ...") {
        HPS.executeQuery {
          HRS.get[String].map { str =>
            for {
              _ <- HPS.set(str)
              n <- HPS.executeUpdate
            } yield n
        }
      }
      //convert from ConnectionIO[PreparedStatementIO[Int]] to PreparedStatementIO[ConnectionIO[Int]]
    }
  }
```

**Comment by 13h3r** [comment]
I spent some time trying to figure out how we can implement this. I want to try to implement this, but can not find a way to do so.

What was I tried:

1. General `Traverse[ConnectionIO]`. 
2. `Traverse[ConnectionIO[Free[S, ?]]]` with `Traverse[S]` constraint.
3. `Traverse[Kleisli[M, Connection, ?]]` with `Traverse[S]` constraint.
4. Specific function to swap `ConnectionIO[PrepareStatementIO]]` which is based on knowledge of what is both `F` and `G`.

I failed all times :( Sure this is mostly because lack of experience with `Free` and related stuff, but working with two dbs looks complicated.

Could you advise appropriate way to implement this? May be not via general `Traverse`, but at least to solve initial issue?

**Comment by tpolecat** [comment]
These types are not traversable; `ConnectionIO[List[A]]` cannot possibly become a `List[ConnectionIO[A]]` because you would need to talk to the database to know how long the list would have to be, for instance.

The problem you're trying to solve (streaming from one database to another) is totally doable but this path is a dead-end. I'll try to make an example this weekend.

**Comment by 13h3r** [comment]
> The problem you're trying to solve (streaming from one database to another) is totally doable but this path is a dead-end. I'll try to make an example this weekend.

What is the way you can think this can be done? In case of lack of time to example could you please drop me a line about a direction to implement this :)

**Comment by tpolecat** [comment]
I think the way to do this is by creating a streams/fs2 `Sink` to perform the inserts on the other database, which provides resource safety so that a failure on either transaction will end up rolling back both. I didn't have a chance to work on it over the weekend, sorry.

**Comment by 13h3r** [comment]
Thanks! I will try it

**Comment by 13h3r** [comment]
Tried to implement this with `Sink`. Was confused with effect type of stream. I want to keep both effects outside the stream. This means that I should compose effects form each database into one complex effect type, but looks like it is impossible to build such monad. 

I can achieve this by applying transactor in `Sink`'s lifecycle, but I want to push both effects outside the stream.

What effect type you suppose to use in stream?

**Comment by 13h3r** [comment]
In case somebody interested I solved this.

The idea is to create `Free` program based on two separate `ConnectionOp`:
- introduce algebra that is `Coproduct` of two `ConnectionOp`s.
- lift stream of `ConnectionIO` to this algebra
- do `evalMap` in terms of algebra
- `run` stream and got `Free` program with new algebra
- write interpreter for algebra by composing two different interpreters
