### ISSUE TITLE
scala 2.12 not supported for specs2

### ISSUE THREAD

**Issue by andykais** [tpolecat/doobie#474]
the chart on the readme states that both `0.4.1` and `0.4.0` support scala `2.12` and
> doobie provides the following, which have the same version as doobie-core[-cats] and are released together.

however, I can only update in sbt with `doobie-core`, `doobie-postgres` and `doobie-scalatest`. This build.sbt will fail for both scalaz and cats versions and version `0.4.1`:
```scala
val doobieVersion = "0.4.0"
scalaVersion := "2.12.1"
// database dependencies
libraryDependencies ++= Seq(
  //"org.scalaz"    %% "scalaz-core"       % scalazVersion,
  //"org.scalaz"    %% "scalaz-concurrent" % scalazVersion,
  "org.tpolecat" %% "doobie-specs2"     % doobieVersion,
  "org.tpolecat" %% "doobie-core"       % doobieVersion,
  "org.tpolecat" %% "doobie-postgres"   % doobieVersion,
  "org.tpolecat" %% "doobie-scalatest"  % doobieVersion
)
```

**Comment by tpolecat** [comment]
Hell. It looks like I have Specs2 v3.8.4 in the POM but it's evicted in doobie's own build by 3.8.6. If you add

```
"org.specs2" %% "specs2-core" % "3.8.6"
```

to your dependencies everything resolves and should work. Give it a try.

Leaving open to fix in 0.4.2

**Comment by andykais** [comment]
that works now, thanks! You may also want to update the "Book of Doobie" since the introduction page says 0.4.0 does not support scala 2.12:
```scala
scalaVersion := "2.11.8" // no support for 2.10 or 2.12 at the moment

lazy val doobieVersion = "0.4.0"

libraryDependencies ++= Seq(
  "org.tpolecat" %% "doobie-core-cats"       % doobieVersion,
  "org.tpolecat" %% "doobie-postgres-cats"   % doobieVersion,
  "org.tpolecat" %% "doobie-specs2-cats"     % doobieVersion
)
```

**Comment by tpolecat** [comment]
Ah good catch. Re-opening for doc fix.
