### ISSUE TITLE
Cannot read a pgEnum column

### ISSUE THREAD

**Issue by etorreborre** [tpolecat/doobie#489]
Here is my example:
```
create table sps_sync (
    review_id  varchar      primary key,
    result           sps_result   not null,
    updated          timestamp    not null default now()
);
```
Then I declare
```
sealed trait SpsResult {
  def pending: Boolean  = this match { case Pending  => true; case _ => false }
  def failed: Boolean   = this match { case Failed   => true; case _ => false }
  def complete: Boolean = this match { case Complete => true; case _ => false }
}

case object Pending extends SpsResult {
  override def toString: String =
    "Pending"
}

case object Failed extends SpsResult {
  override def toString: String =
    "Failed"
}

case object Complete extends SpsResult {
  override def toString: String =
    "Complete"
}

object SpsResult {
  implicit def eq: Eq[SpsResult] = Eq.fromUniversalEquals[SpsResult]

  def stringValue(result: SpsResult): String =
    result match {
      case Pending  => "pending"
      case Failed   => "failed"
      case Complete => "complete"
    }

  def fromStringUnsafe(s: String): SpsResult =
    fromString(s).getOrElse(throw doobie.util.invariant.InvalidEnum[SpsResult](s))

  implicit val spsResultAtom: Atom[SpsResult] =
    pgEnumString("sps_result", SpsResult.fromStringUnsafe, SpsResult.stringValue)
}
```
Now if I try to check a simple SELECT query
```scala
 fr"""SELECT
           result
         FROM sps_sync
         WHERE review_id = $reviewId;""".query[SpsResult]
```
I get
```
 VARCHAR (sps_result) is not coercible to String according to the JDBC
  specification or any defined mapping. Fix this by changing the schema type to
  OTHER, or the Scala type to String or ... or ....
```
Since I have a proper implicit `Atom` definition in `SpsResult` I don't understand why the conversion from the PG enum cannot take place. Thanks.

**Comment by tpolecat** [comment]
@etorreborre which version are you using? This is fixed in 0.4.0 by #431. If you're stuck on an older version we can probably copy/paste a workaround.

**Comment by etorreborre** [comment]
I'm not stuck on anything, I'll try to upgrade thanks.

**Comment by etorreborre** [comment]
I'm using `0.4.1` already, should I try `0.4.2-SNAPSHOT`?

**Comment by tpolecat** [comment]
Hm, can you paste the entire checker output? It will probably work fine, it's almost certainly a problem in the checker's metadata. I'll take a look this morning.

**Comment by etorreborre** [comment]
I get this
![image](https://cloud.githubusercontent.com/assets/10988/24111160/d9f22fe6-0d95-11e7-9871-0eba9ab7133b.png)
Is that the output you need?

**Comment by tpolecat** [comment]
ya thx

**Comment by tpolecat** [comment]
Ok yeah so I fixed this for the write case but I'm an idiot so I didn't fix the read case. You can copy/paste the relevant code from the PR above. I'll make a new snapshot later today but there are a number of nontrivial changes relative to 0.4.1 so you may not want to use the snapshot.

**Comment by etorreborre** [comment]
I can wait for a proper `0.4.2` when it comes. Thanks for fixing this!

**Comment by tpolecat** [comment]
Re-opening to keep on radar until I get a test in that PR.
