### ISSUE TITLE
The last published version for Scala 2.10 is 0.3.0

### ISSUE THREAD

**Issue by gruggiero** [tpolecat/doobie#497]
Sonatype snapshot contains the last version, though.

**Comment by tpolecat** [comment]
It appears something isn't configured quite right. @fiadliel points me to https://github.com/sbt/sbt-doge#usage-from-sbt-release which is quite likely the culprit. Will investigate.

**Comment by tpolecat** [comment]
Very close to saying fuck it, no 2.10 release because I can't get it to work.

**Comment by tpolecat** [comment]
I give up. If someone wants to PR a fix be my guest.

**Comment by gruggiero** [comment]
I think the project that caused this issue is going to upgrade to a newer Scala version, so I suppose this is no more needed.
I don't work anymore on it so I'm not 100% sure, though.
Thank you anyway for the effort spent on it.

**Comment by tpolecat** [comment]
(2.10 is no longer supported)
