### ISSUE TITLE
How do I convert fs2.Stream[ConnectionIO, T] to akka's Source[T, NotUsed] ?

### ISSUE THREAD

**Issue by unoexperto** [tpolecat/doobie#500]
I'm using akka-http to implement API on my server. I see that doobie supports streaming results but I need it to be `akka.stream.scaladsl.Source[ByteString, NotUsed]` in order to return it to API client as chunked http.

How do I convert fs2.Stream[ConnectionIO, T] to akka's Source[T, NotUsed] ?

**Comment by tpolecat** [comment]
I think this is the best answer we're likely to get

https://github.com/krasserm/streamz
