### ISSUE TITLE
Investigate -Ymacro-expand:normal

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#508]
It has been reported that `-Ymacro-expand:normal` can improve the presentation compiler's accuracy wth doobie (and other libs that use similar tricks). This is of interest to Eclipse and ENSIME users. See https://github.com/scala/bug/issues/9716 for details ona the origin of this suggestion. Thanks @fanf for bringing this to our attention!

Data points thus far:
- @fanf - *For information, for people using Doobie with ScalaIDE, it is reported that adding "-Ymacro-expand:normal" in the compiler option helps with the spurious error messages. I'm not sure it did for me, but it helped for other spurious error messages, so it seems to be a win*
- @rkrzewski - *Adding -Ymacro-expand:normal to compiler options in Scala IDE helped me to get rid of phantom errors with missing Composite instances*

This issue is to solicit experience reports for people who have tried it. **Please give it a try and let us know what happens.** The ultimate goal is likely to just be an FAQ entry but it would be nice to be able to characterize what to expect.

**Comment by fanf** [comment]
I actually had a problem with eclipse configuration: dear ScalaIDE user, be careful that as soon as you use ```right click on a project -> Scala -> Set the Scala Installation```, then Eclipse enable per project setting and your global configuration line is not used. Moreover, the ```additionnal command line parameters``` in ```project -> properties -> scala compiler``` is set to ```-Ymacro-expand:none```. 

So when you actually change in all your project the dedicated setting (and yes, I hate Eclipse a little more every days), then you actually get NO MORE SPURIOUS RED LINE. At least for now, and with Scala-IDE 4.6 (just released - it's the same as 4.6-rc2). 

So this is a big win! I will report if problems occure or spurious red line show in some contexts.

**Comment by retronym** [comment]
FYI, this should become a non-problem in 2.12.3: https://github.com/scala/scala/pull/5929
