### ISSUE TITLE
Refined contrib package not in 0.4.2-SNAPSHOT yet?

### ISSUE THREAD

**Issue by ZizhengTai** [tpolecat/doobie#529]
It seems in the latest 0.4.2-SNAPSHOT there is no `doobie.refined` package. Adding it in could be really handy because we are making extensive use of Refined in our existing codebase.

**Comment by n4to4** [comment]
There seems to be...?
https://oss.sonatype.org/#nexus-search;gav~org.tpolecat~doobie-refined_2.12~~~~kw,versionexpand

I haven't used it but I could download the jar file in `~/.ivy2/cache/org.tpolecat/doobie-refined_2.12/jars/doobie-refined_2.12-0.4.2-SNAPSHOT.jar`

```
resolvers ++= Seq(
  Resolver.sonatypeRepo("snapshots")
)

val doobieVersion = "0.4.2-SNAPSHOT"

libraryDependencies ++= Seq(
  "org.tpolecat" %% "doobie-refined" % doobieVersion
)
```

**Comment by tpolecat** [comment]
This is out there, at https://oss.sonatype.org/content/repositories/snapshots/org/tpolecat/doobie-refined-cats_2.12/0.4.2-SNAPSHOT/
