### ISSUE TITLE
withGeneratedKeys & transaction statements missing from logs

### ISSUE THREAD

**Issue by Arcovion** [tpolecat/doobie#533]
On 0.4.2-SNAPSHOT inserts using `withUniqueGeneratedKeys` aren't being logged:
```scala
sql"INSERT INTO...".update.run
```
works, but this doesn't:
```scala
sql"INSERT INTO...".update.withUniqueGeneratedKeys[Long]("id")
```
I'm using an implicit `LogHandler`

Also, is there any way of logging the BEGIN/COMMIT/ROLLBACK statements? I think it's useful info, makes it easier to parse visually when examining multiple transactions. 
You have no way of knowing which statements have been rolled back otherwise, nor can you see the time it takes to perform a ROLLBACK/COMMIT like you can with other statements.

**Comment by tpolecat** [comment]
Current logging is limited, obviously. There will be good structured logging in an upcoming release.

**Comment by Kim-SeongCheol** [comment]
Is it still not solved?

**Comment by halfhp** [comment]
this would be great to have.  any update?

**Comment by dpevunov-cp** [comment]
Looks like this issue is still relevant and no logs are produced for this case

**Comment by jatcwang** [comment]
I'll close this since it's related to #1888 and can be fixed together
