### ISSUE TITLE
Update docs on how to run statements outside of a transaction

### ISSUE THREAD

**Issue by Arcovion** [tpolecat/doobie#534]
I've been using the [`withoutTransaction` function](https://tpolecat.github.io/doobie-cats-0.4.0/17-FAQ.html#how-do-i-run-something-outside-of-a-transaction) given in the docs, but this appears to be broken in 0.4.2-SNAPSHOT (`java.sql.SQLException: database in auto-commit mode`). 

The reason I'm doing this is to send pragmas to SQLite: the [sequel library for Ruby](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/shared/sqlite.rb#L343-L345)  automatically sends `PRAGMA foreign_keys = 1` on each new connection. This always has to be specified, outside of a transaction, to enable foreign keys. I'm simply composing the pragmas in front of my transaction right now `pragmas *> statements`.

**Comment by wedens** [comment]
I think you should run such `ConnectionIO` using `transactor.rawTrans`. It skips any transaction related logic.

**Comment by tpolecat** [comment]
You might want to set this in the `before` field of the `Strategy`, prior to the default behavior `setAutoCommit(false)`.

```scala
// New transactor with different `before` behavior,
val xa2 = Transactor.before.modify(xa, sql"PRAGMA foreign_keys = 1".update.run *> _)
```

**Comment by tpolecat** [comment]
Doc issue rolled into #506
