### ISSUE TITLE
Composite.apply returns null instead of compile error

### ISSUE THREAD

**Issue by pkoryzna** [tpolecat/doobie#536]
`Composite.apply[T]` for `T` that cannot be derived (e.g. because there's no instance for some fields in case class, etc.) returns `null` instead of compile error if the variable it's assigned to has a type annotation.

```
scala> import doobie.imports._, cats._, cats.data._, cats.implicits._, fs2.interop.cats._,  doobie.hikari.imports._, doobie.postgres.imports._

scala> case class ExampleRow(a: Int, b: Int, ts: java.time.ZonedDateTime)
defined class ExampleRow

scala> implicit val comp: Composite[ExampleRow] = Composite.apply[ExampleRow]
comp: doobie.imports.Composite[ExampleRow] = null

scala> implicit val comp: Composite[ExampleRow] = Composite[ExampleRow]
comp: doobie.imports.Composite[ExampleRow] = null

scala> Composite[Int]
res0: doobie.util.composite.Composite[Int] = doobie.util.composite$Composite$$anon$4@80a8f31

scala> val compInt: Composite[Int] = Composite[Int]
compInt: doobie.imports.Composite[Int] = doobie.util.composite$Composite$$anon$4@63b63389
```

*edit* also see this example for ZDT alone: when type annotation is added, null is returned. Without it, the same line fails to compile as expected.

```
scala> implicit val cmpZDT = Composite[java.time.ZonedDateTime]
<console>:36: error: Could not find or construct Composite[java.time.ZonedDateTime].
Ensure that this type has a Composite instance in scope; or is a Product type whose members have
Composite instances in scope; or is an atomic type with an Atom instance in scope. You can usually
diagnose this problem by trying to summon the Composite instance for each element in the REPL. See
the FAQ in the Book of Doobie for more hints.
       implicit val cmpZDT = Composite[java.time.ZonedDateTime]
                                      ^

scala> implicit val cmpZDT: Composite[java.time.ZonedDateTime] = Composite[java.time.ZonedDateTime]
cmpZDT: doobie.imports.Composite[java.time.ZonedDateTime] = null
```

**Comment by tpolecat** [comment]
This is not a doobie bug. You could argue that it's Scala bug. An implicit declaration with a return type annotation is implicit *within its own definition,* which in this case is a direct self-reference that results in an uninitialized value.

```scala
scala> implicit val a: String = implicitly[String]
a: String = null

scala> implicit val a: Int = implicitly[Int]
a: Int = 0
```

If you leave off the annotation then the implicit *isn't* available in the body.

```scala
scala> implicit val a = implicitly[String]
<console>:16: error: could not find implicit value for parameter e: String
       implicit val a = implicitly[String]
                                  ^
```

**Comment by tpolecat** [comment]
I should point out that the desire to do this is suspicious … what is your intent in summoning instances and making them implicit in scope (since they're already available)?

**Comment by pkoryzna** [comment]
Completely forgot that Scala does this, and I've got bitten by this once already... 

wrt second question: PEBKAC - I put the instance in the local scope in hopes of finding out which `Meta` instance I'm missing by following compiler errors (instead of just simply going through fields one-by-one as recommended in the book, AFAIK).
