### ISSUE TITLE
Parsing ranges by way of `Meta[PGobject]` fails...

### ISSUE THREAD

**Issue by solidsnack** [tpolecat/doobie#541]
Or it is at least difficult to figure out how to do it. The implicit is written as `Meta.other[PGobject]("daterange").nxmap[corporate.DateRange](...)`. The query is like this:

```scala
sql"SELECT '[today, tomorrow)'::daterange".query[corporate.DateRange].unique
```

When the query is run, there is an error thrown from `org.postgresql.jdbc.TimestampUtils.parseBackendTimestamp`: "Trailing junk on timestamp: '[2017-07-03,2017-07-04)'". This, despite the fact that in my current code no parsing occurs -- it just generates the empty `corporate.DateRange`. If the query is written as:

```scala
sql"SELECT '[today, tomorrow)'::daterange".query[String].unique
```

 there is no error.

There is some mention of `LowerPriortityComposite` in the stack trace.

**Comment by solidsnack** [comment]
Stack trace is:
```
org.postgresql.util.PSQLException: Bad value for type timestamp/date/time: {1}
  at org.postgresql.jdbc.TimestampUtils.parseBackendTimestamp
  at org.postgresql.jdbc.TimestampUtils.toTimestamp
  at org.postgresql.jdbc.TimestampUtils.toDate
  at org.postgresql.jdbc.PGResultSet.getDate
  at org.postgresql.jdbc.PGResultSet.getDate
  at doobie.util.meta$MetaInstances.$anonfun$DateMeta$1
  at doobie.util.meta$MetaInstances.$anonfun$DateMeta$1$adapted
  ...
```

(Here reproduced by hand.) One thing I can not figure out, is why it tries to parse a date at all.

**Comment by solidsnack** [comment]
Never mind. Code not being called -> Implicits not in scope in the interpreter.

All's well that ends well.

**Comment by ShahOdin** [comment]
I'm having trouble doing it: https://gist.github.com/ShahOdin/e1a87ccf67dafd378a9cbe1a7fbfc30f

any guesses what I am doing wrong?
