### ISSUE TITLE
Derivation strategies

### ISSUE THREAD

**Issue by wedens** [tpolecat/doobie#542]
It would be useful to be able to choose how to use (or not to use) derivation:
- auto derivation (currently by default)
- semi-auto derivation (`implicit val userComposite: Composite[User] = deriveComposite[User]`)
- no derivation (custom instances)

For example: circe [provides](https://circe.github.io/circe/codec.html) such choice for codec derivation.

Drawbacks of auto-derivation as the only choice:
- It's slow (at least compile-time). Instances are derived at call site.
- Every case class is assumed to be correspondable to a row in result set. It is not always the case and you may want to explicitly say "this type corresponds to a row" by having `Composite` instance.

**Comment by tpolecat** [comment]
Yes, I like this approach. We can look at it in the 0.5 series.

**Comment by lorandszakacs** [comment]
I'd honestly pick this up, but my shapeless-foo isn't quite the best. But maybe might be able to spin something up.

I'd really like to have this, as I've foot-gunned myself many times by automatic derivation basically in every library that supports it, and have moved completely to using some-kind of semi-auto derivation.

**Comment by tpolecat** [comment]
I will have a look at this. It may not be too bad.

**Comment by hamnis** [comment]
Would this be possible to revisit? Scala 3 has wonderful semiauto capabilities thanks to the `derives` keyword.

**Comment by jatcwang** [comment]
This can probably be done by moving the auto derivation `implicit def`s to a separate import, then use scalafix to add that import for all existing doobie codebases. And then going forward all auto-derivation will require the explicit import much like `io.circe.generic.auto._`

**Comment by jatcwang** [comment]
I think #1738 is the right way to go. Will resurrect it.

**Comment by jatcwang** [comment]
#1967 has been merged but we still need #1970 to not inconvenient users

Created #1976 for optimizing compile time.

**Comment by jatcwang** [comment]
#1970 is merged. Closing
