### ISSUE TITLE
Example for streaming rows from one database to another.

### ISSUE THREAD

**Issue by Wogan** [tpolecat/doobie#543]
As per [gitter](https://gitter.im/tpolecat/doobie?at=5960146c4bcd78af568a0255) conversation, I'm looking to stream rows from one database to another in an efficient fashion.

Ideally the book of doobie would have an example showing how to do this.

**Comment by wedens** [comment]
Completely untested code for fs2. Shouldn't be difficult to translate to scalaz-stream.
```scala
 def copyStreaming[F[_]: Catchable, A, B, C](
    select: Query0[A],
    xaFrom: Transactor[F, B],
    insert: Update[A],
    xaTo: Transactor[F, C]
  ): F[Unit] =
    xaTo.exec.apply {
      select
        .process
        .transact(xaFrom)
        .translate(λ[F UF1 Kleisli[F, Connection, ?]](a => Kleisli(_ => a)))
        .evalMap { a =>
          insert.run(a).foldMap(xaTo.interpret)
        }.run
    }
```

**Comment by tpolecat** [comment]
Ha I just saw your code @wedens! If it works I'll be embarrassed because mine is much more complicated. I'll try it ;-)

**Comment by tpolecat** [comment]
@wedens yours does work! Mine returns a stream though so I'm including both.

**Comment by alfonsonishikawa** [comment]
I don't find the `.process` in my `Query0[A]` object. Where can I find it?

**Comment by tpolecat** [comment]
That's an obsolete API. Look at the [`StreamingCopy.scala`](https://github.com/tpolecat/doobie/blob/series/1.0/modules/example/src/main/scala/example/StreamingCopy.scala). Switch it to `master` if you're not on CE3 yet.
