### ISSUE TITLE
Creating new postgres schema fails when using interpolation

### ISSUE THREAD

**Issue by valenterry** [tpolecat/doobie#554]
```
val schema: String = "testschema"
val createSchema: Update0 = sql"CREATE SCHEMA $schema".update
createSchema.run.transact(transactor).unsafePerformIO
```

Gives:

> [error] cannot create an instance for class ***.postgre.EmbeddedPgDbTest
> [error]   caused by org.postgresql.util.PSQLException: ERROR: syntax error at or near "$1"
> [error]   Position: 15

However, when I replace `CREATE SCHEMA $schema` with `CREATE SCHEMA testschema` it works as expected.

Tested with doobie 4.0.1 + Postgres 9.6

**Comment by tpolecat** [comment]
Prepared statements can have placeholders only in positions that the underlying database allows; Postgres doesn't allow one here. You can say

```scala
val createSchema: Update0 =
  (fr"CREATE SCHEMA" ++ Fragment.const(schema)).update 
```

but note that this is a direct string concatenation and is **vulnerable to injection attack**. Do not pass user-supplied text to `Fragment.const`.
