### ISSUE TITLE
Unclear how to migrate ConnectionIO.transK[M] calls in v0.4.2

### ISSUE THREAD

**Issue by hywelandrews** [tpolecat/doobie#565]
Previously we had access to transK methods in `doobie.free.connection` which would resolve a ConnectionIO[A] to Kleisli[M[_]: Catchable: Suspendable, Connection, A], which was useful when we already had a java.sql.Connection available: `connectionIo.transK[Task].run(connection).unsafeRun()`

As this has now been refactored in 0.4.2 and `transK` is no longer available (https://github.com/tpolecat/doobie/issues/282), the documented new approach does not appear to work as I expected

```
import cats.implicits._
import doobie.hi._
import doobie.hi.connection._
import doobie.imports._
```

`val prog = 42.pure[ConnectionIO] `
Creating an Kleisliinterpreter for some Catchable: Suspendable
 `val nat  = KleisliInterpreter[IOLite]`
Using the default ConnectionInterpreter:
 `val int = nat.ConnectionInterpreter`
And then foldMap over this ConnectionInterpreter
`val task: Kleisli[IOLite, Connection, Int] = prog.foldMap(int)`

`prog.foldMap(int)` will throw a build error:

```Error:(36, 21) no type parameters for method foldMap: (f: cats.arrow.FunctionK[doobie.free.connection.ConnectionOp,M])(implicit M: cats.Monad[M])M[Int] exist so that it can be applied to arguments (cats.~>[doobie.free.connection.ConnectionOp,[γ$9$]cats.data.Kleisli[doobie.imports.IOLite,java.sql.Connection,γ$9$]])
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : cats.~>[doobie.free.connection.ConnectionOp,[γ$9$]cats.data.Kleisli[doobie.imports.IOLite,java.sql.Connection,γ$9$]]
    (which expands to)  cats.arrow.FunctionK[doobie.free.connection.ConnectionOp,[γ$9$]cats.data.Kleisli[doobie.imports.IOLite,java.sql.Connection,γ$9$]]
 required: cats.arrow.FunctionK[doobie.free.connection.ConnectionOp,?M]
    val task = prog.foldMap(nat).run(conn).unsafePerformIO
```

Have I mis interpreted the proposed usage here: https://tpolecat.github.io/doobie-cats-0.4.2/14-Managing-Connections.html?

Thanks

Hywel

**Comment by wedens** [comment]
I think you made a typo here: ` val task: Kleisli[IOLite, Connection, Int] = prog.foldMap(nat)`. It should be `int`, not `nat` ;)

**Comment by hywelandrews** [comment]
@wedens Correct, there was a typo in the above comment, the error is actually thrown when I pass variable `int` into foldMap, updated the original post.

**Comment by wedens** [comment]
Can you paste full gist? It's unobvious how your code results in `cats.~>[doobie.free.connection.ConnectionOp,[γ$9$]cats.data.Kleisli[fs2.Task,java.sql.Connection,γ$9$]]`. Especially if you don't use `fs2.Task`.

**Comment by hywelandrews** [comment]
@wedens Apologies, my copy and paste skills leave a lot to be desired, the fs2.Task reference was from a seperate attempt, again corrected above. Here is a gist which causes the issue https://gist.github.com/hywelandrews/f086b493f52b2045263a1aef0f757b24

**Comment by hywelandrews** [comment]
OK, after some more experimentation I found that the above gist will compile when I include `addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.0.0")`, so when moving to `0.4.2` and re-implementing `ConnectionIO` -> `java.sql.Connection` transformations it appears to require `partial-unification` plugin for Scala `2.11.8`. This would also possibly prevent migrating from Scala versions 2.11.7 and below as `partial-unification` reported not supporting these versions. This could just be a documentation update?

**Comment by wedens** [comment]
There is `-Ypartial-unification` scalac flag in >= 2.11.9. It's just considered to be a requirement in any scala-FP project ;)

**Comment by hywelandrews** [comment]
@wedens Thanks for your help
