### ISSUE TITLE
Composition of Fragments by interpolation.

### ISSUE THREAD

**Issue by halvorgb** [tpolecat/doobie#610]
Is it possible to implement interpolation of fragments? I find that use fragments quite a lot, for example when defining which columns a resource I'm interested in has. Or when using `IN` queries, etc.

An example of how I'm currently composing fragments
```scala
import cats._
import cats.data._
import cats.implicits._
import doobie.imports._
import fs2.interop.cats._

case class Car(carId: Long, color: String, manufacturer: String, year: Int)

object CarQueries{
  def columns: Fragment = fr"cars.car_id, cars.color, cars.manufacturer, cars.year"
  def blueCarsByIdsQuery(carIds: NonEmptyList[Long]): Query0[Car] = (
    fr"SELECT" ++ CarQueries.columns ++
    fr"""FROM cars""" ++ 
    Fragments.whereAnd(Fragments.in(fr"car_id", carIds), fr"color = 'blue'"))
   ).query[Car]
}
```

What I'd love to do is write 
```scala
  def blueCarsByIdsQuery(carIds: NonEmptyList[Long]): Query0[Car] =
    fr"""SELECT ${CarQueries.columns}
          FROM cars
          ${Fragments.whereAnd(Fragments.in(fr"cars.car_id", carIds), fr"color = 'blue'")}""".query[Car]
```
Which in my opinion is quite a lot cleaner.

I took a stab at a sketch here: https://github.com/tpolecat/doobie/compare/series/0.5.x...halvorgb:fragment-interpolation-sketch

I'm convinced that my sketch is terrible, I don't need any help to convince me of that,  but how hard would it be to implement something like this? How would you send the parameters in the correct order to JDBC for "nested" fragments?

**Comment by tpolecat** [comment]
Yeah there are some limitations to the way it's implemented now that prevent this kind of embedded. I'll leave it open as a design problem. Should be doable but will require re-thinking some things.
