### ISSUE TITLE
WHERE IN multiple columns

### ISSUE THREAD

**Issue by valenterry** [tpolecat/doobie#626]
We have some table
```
CREATE TABLE pim.baloons (
	name text NOT NULL,
	amount int NOT NULL,
	PRIMARY KEY (name, amount)
)
```

and want to query:
```
SELECT name, amount
  FROM pim.baloons
  WHERE amount
  IN (1, 2, 3)
```

In doobie we do it like that:
```
(fr"""
    SELECT name, amount
    FROM baloons
    WHERE """ ++ Fragments.in(fr"amount", NonEmptyList.of(1, 2, 3))
  ).query[(String, Int)]
```

Works great!

But we can't query for multiple colums at the same time:

```
SELECT *
  FROM pim.baloons
  WHERE (name, amount)
  IN (('red', 1), ('red', 2), ('red', 5), ('blue', 4), ('red', 12))
```
Trying that in doobie (with less values for brevity):
```
(fr"""
    SELECT name, amount
    FROM baloons
    WHERE """ ++ Fragments.in(fr"(name, amount)", NonEmptyList.of(("red", 1), ("blue", 2)))
  ).query[(String, Int)]`
```

Gives us an error:
```
Could not find or construct Param[(String, Int)].
Ensure that this type is an atomic type with an Atom instance in scope, or is an HList whose members have Atom instances in scope. You can usually diagnose this problem by trying to summon the Atom instance for each element in the REPL. See the FAQ in the Book of Doobie for more hints.
          WHERE """ ++ Fragments.in(fr"(name, amount)", NonEmptyList.of(("red", 1), ("blue", 2)))
```

To work around this we created some method (with fancy shapeless stuff inside) so that we can write:
```
(fr"""
    SELECT name, amount
    FROM baloons
    WHERE (name, amount) """ ++ NonEmptyList.of(("red", 1), ("blue", 2)).reduceInFragments
  ).query[(String, Int)]`
```

Question: did we overlook some existing doobie functionality? If not, is something like that planned or should we contribute our method to doobie?

**Comment by tpolecat** [comment]
You can do this in terms of `Composite`, first with a thing that flattens a value into a SQL tuple:

```scala
/** Flattened `a` as a VALUES argument (...). */
def values[A](a: A)(implicit ev: Composite[A]): Fragment =
  Fragment(List.fill(ev.length)("?").mkString("(", ", ", ")"), a)
```

Then generalize the `in` combinator to `Composite`:

```scala
/** Returns `f IN (fs0, fs1, ...)`. */
def in[F[_]: Reducible, A: Composite](f: Fragment, fs: F[A]): Fragment =
  fs.toList.map(values(_)).foldSmash1(f ++ fr0"IN (", fr",", fr")")
```

And then we can say

```scala
scala> val stuff = NonEmptyList.of((1, "x"), (2, "y"))
stuff: cats.data.NonEmptyList[(Int, String)] = NonEmptyList((1,x), (2,y))

scala> in(fr"(foo, bar)", stuff)
res13: doobie.Fragment = Fragment("(foo, bar) IN ((?, ?), (?, ?)) ")
```

So this may be simpler than what you have. I can go ahead and push this back into `Fragments` if it looks like it solves your problem. What do you think?

**Comment by tpolecat** [comment]
In fact it might make sense to generalize fragment interpolation to do that tuple expansion in all cases and get rid of the `Param` typeclass. People have asked for this. Hmm.

**Comment by tpolecat** [comment]
Note that we will have to special-case the composite with size 1 so we don't get `(?)` ... paren handling will be tricky.

**Comment by Esardes** [comment]
Did you get a chance to make progress on this?

**Comment by caoilte** [comment]
@tpolecat posted an updated solution in response to @dimitarg question here,

https://gitter.im/tpolecat/doobie?at=5cded51f75d9a575a6fa597d

```
@ def in[F[_]: Reducible, A: Put, B: Put](f: Fragment, fs: F[(A,B)]): Fragment =
    fs.toList.map { case (a,b) => fr0"($a,$b)" }.foldSmash1(f ++ fr0"IN (", fr",", fr")") 
defined function in
```

```
@ in(fr"blah", NonEmptyList.of((1,true),(2,false))) 
res9: Fragment = Fragment("blah IN ((?,?), (?,?)) ")
```

```
@ in(fr"(year,month)", NonEmptyList.of((2019, 5), (2019, 6), (3030, 11))) 
res10: Fragment = Fragment("(year,month) IN ((?,?), (?,?), (?,?)) ")
```

**Comment by Jasper-M** [comment]
FYI for any arbitrary type `A` which has `Write[A]` you can do

```
fr"(c0, c1, c2) IN (${Fragments.values(listOfAs)})"
```
Which translates to `(c0, c1, c2) IN (VALUES (v0_0, v0_1, v0_2), (v1_0, v1_1, v1_2), ...)` and appears to be standard SQL syntax.

**Comment by jatcwang** [comment]
I think this is addressed now so I'll close it. Please reopen if not :)
