### ISSUE TITLE
Having a hard time understanding the code 

### ISSUE THREAD

**Issue by costabas** [tpolecat/doobie#637]
Hi:

I am having some hard time understanding this library - it's built on so many abstractions! There's got to be an easier way to implement it using simple OO paradigms and simpler FP concepts.

The earlier version used cats and some other library (I can't remember its name). That made it harder to decide, should I use cats or the other library? Which one has more features? Which one is more performant? I am glad to see you chose one of them and got rid of the other one.

I also have a problem with the name of the methods: unsafeRunSync. Why is it called unsafe? When I was reading this the first time my first reaction was, if it's unsafe, why should I use it? Is there a safe version? Why can't be called ExecuteSync or simply RunSync.

To me, the implementation of this library looks like an intellectual exercise. I admire it in a way. 

In the end what are we doing here? Ultimately we are moving data between a server and in-memory structures. There are quirks in the jdbc drivers and types specific to each RDBMS. It is indeed a huge endeavor to implement a generic library that works with all sorts of RDBMSes flavors. I think the major problem is getting the right conversion process between the RDBMS types and Scala/Java types. 

As an example, I was trying to use doobie to execute ad-hoc sql and convert it to json. I found a sample Dynamic.scala where you get the data from the server using getObject for each field. One of the fields was text search vector (PostgreSQL) and it doesn't convert to json right out-of-the-box (I am using using the fasterxml jackson - there is probably a way to define some abstraction for exporting to json) due to reference to objects that are not serializable to json. The question is how can I handle this field generically at runtime? I will have to spend time reading the code and finding the abstraction that allows me to override the handler for this type of fields whose type is known only at runtime. Good luck with that. 

I know, the FP at the level used in the library is hard. I am going to spend more time trying to understand the different pieces of the puzzle and I hope I will have an easier time figuring things out.

**Comment by tpolecat** [comment]
> I am having some hard time understanding this library - it's built on so many abstractions! There's got to be an easier way to implement it using simple OO paradigms and simpler FP concepts.

doobie is intended for people who are doing pure FP in Scala using cats. You may wish to look at another library like Slick or Quill or ScalikeJDBC, or just use JDBC directly.

> I also have a problem with the name of the methods: unsafeRunSync. Why is it called unsafe?

This is a method on `cats.effect.IO`. It's not a doobie thing. It's unsafe because it's not referentially transparent (i.e., it's a side-effect).

> I think the major problem is getting the right conversion process between the RDBMS types and Scala/Java types.

Indeed, and doobie has a lot of machinery to allow you to define precise type mappings statically.

> One of the fields was text search vector (PostgreSQL) and it doesn't convert to json right out-of-the-box (I am using using the fasterxml jackson - there is probably a way to define some abstraction for exporting to json) due to reference to objects that are not serializable to json. 

If you don't know the type at compile-time you will need to use the JDBC API to examine the column metadata and determine which `getXXX` method to call and which conversion to apply. This is a driver thing; doobie doesn't do anything at this level.

**Comment by costabas** [comment]
Thanks for your reply. I think I am part of the problem. When I program I still think in terms of imperative programming rather than FP. I will close this. You answered my question.
