### ISSUE TITLE
Add string interpolation like slick's #$stringInterpolate

### ISSUE THREAD

**Issue by Daenyth** [tpolecat/doobie#652]
Example usage:
```
val table = "foo"
val a = sql"select 1 from #$table"
```

**Comment by tpolecat** [comment]
The issue here is that it needs to be a macro because we can't otherwise know where the `#`s are at compile time, which we need in order to typecheck the interpolated value.

**Comment by ljwagerfield** [comment]
There's a [workaround](https://github.com/tpolecat/doobie/issues/156) which involves using `Fragment.const(...)`:

```scala
val table = "foo"
val a = fr"select 1 from " ++ Fragment.const(table)
```
