### ISSUE TITLE
0.4.x Book. Introduction DB setup returns 404 

### ISSUE THREAD

**Issue by LePont** [tpolecat/doobie#663]
In the current deployed book. The DB setup in introduction is returning a 404 for:

`$ curl -O https://raw.githubusercontent.com/tpolecat/doobie/master/world.sql`

No master branch. Very awkward comfort :)

Found when following path from 0.4.X branch README

**Comment by tpolecat** [comment]
Thanks, this is fixed on the 0.5.x branch.
