### ISSUE TITLE
Can't destructure tuple ConnectionIO in for comprehension

### ISSUE THREAD

**Issue by sdether** [tpolecat/doobie#684]
Trying to destructure a tuple in a for comprehension such as:
```
for {
  (a, b) <- (1, 3).pure[ConnectionIO]
} yield (b, a)
```
fails with:

> Error:(32, 30) value withFilter is not a member of doobie.ConnectionIO[(Int, Int)]
> (a, b) <- (1, 3).pure[ConnectionIO]

Can be expressed as:
```
for {
  x <- (1, 3).pure[ConnectionIO]
} yield (x._2, x._1)
```
Not sure if it can be fixed in Doobie. Might be blocked by [SI-1336: spec requires type checking of for-comprehension to consider refutability](https://issues.scala-lang.org/browse/SI-1336), i.e. might require a dummy filter on `Free`, as such is a bug against cats?

**Comment by wedens** [comment]
It's a bug in scalac that you linked, so it's issue in cats or doobie.

Workaround is to do:
```scala
for {
  x <- (1, 3).pure[ConnectionIO]
  (a, b) = x
} yield (b, a)
```

**Comment by sdether** [comment]
`(a,b) = x` is certainly preferable to `x._1`, etc.

Just opened this in case there was a fix that could be made at the Doobie end. Oh well.

**Comment by tpolecat** [comment]
@sdether yep, it's a consequence of the way `for`-comprehensions are desugared and there's no way to fix it without changing the compiler.
