### ISSUE TITLE
Stackoverflow tag

### ISSUE THREAD

**Issue by jn73** [tpolecat/doobie#687]
Sorry if this is out of scope for the issue-tracker but..

I just posted a question (https://stackoverflow.com/questions/48944446/compose-optional-queries-for-for-comprehension-in-doobie) and realised that there isn't any doobie tag there. My rep is too low to create new tag's.

Anyone here with 1500+ rep who can add 'doobie'? Would make it easier to share doobie-knowledge on stackoverflow.

**Comment by tpolecat** [comment]
I don't have any rep … I just don't have time to look at SO. But maybe someone else does. I usually just direct people to the Gitter channel for support, and add to the FAQ as necessary.

**Comment by tpolecat** [comment]
I'll ask on the Gitter channel.

**Comment by tpolecat** [comment]
@Daenyth did it for us, thanks!
