### ISSUE TITLE
Weird infographic letter spacing

### ISSUE THREAD

**Issue by kellen** [tpolecat/doobie#694]
Super minor, but the SVG has weird spacing issues (on OSX Firefox or Chrome), possibly caused by text blocks being broken up unnecessarily(?). 

Note the space between the `r` and the rest of `required`.  This happens in a few other places as well.

<img width="655" alt="screen shot 2018-03-16 at 09 23 37" src="https://user-images.githubusercontent.com/486691/37523076-3dda7a5e-28fc-11e8-94e7-f53e1c591b2c.png">

**Comment by tpolecat** [comment]
Yeah it's weird. Looks fine in PDF. I think it's a quirk of OmniGraffle's SVG converter.

**Comment by tpolecat** [comment]
Ok this is fixed (OmniGraffle bug was fixed). it will take a few days to show up on the CDN but the direct download works.
