### ISSUE TITLE
Add ability to cancel running queries

### ISSUE THREAD

**Issue by YulawOne** [tpolecat/doobie#699]
As far as cats.effect received api for cancel IO tasks we should consider ability to cancel running queries for doobie, probably through [Statement.cancel()](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#cancel()) api

**Comment by tpolecat** [comment]
It might be possible to hook into that machinery. Good idea, thanks!

**Comment by amorfis** [comment]
Is this going to be implemented anytime soon?

**Comment by mikkka** [comment]
I've created PR to solve this issue:
https://github.com/tpolecat/doobie/pull/1246

**Comment by mhammons-ledger** [comment]
This is supposedly fixed by https://github.com/tpolecat/doobie/pull/1357. If that's true, can you close the issue?

**Comment by jatcwang** [comment]
Thanks @mhammons-ledger  will do
