### ISSUE TITLE
Structured Logging

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#7]
Add exception-proof structured logging that can produce usable traces like [this](https://github.com/tpolecat/doobie/blob/master/log.png). Need to have sliding windows or something to prevent unbounded trace growth. This will require messing with the `Kleisli` interpreters or adding additional ones.

**Comment by tpolecat** [comment]
Consider the following.

```scala
trait Monitor {
  def gosub[F[_]: Monad: Capture: Catchable, A](fa: F[A])(target: Any): F[A]
  def call[F[_]: Monad: Capture: Catchable, A](fa: F[A])(method: String, args: Array[Any]): F[A]
}
```

and then primitive combinator

```scala
case class WithMonitor[A](fa: WoozleIO[A], m: Monitor) extends WoozleOp[A]
```

and syntax

```scala
prog.withMonitor(m)
```

This will require a second interpreter that handles monitoring, or a default no-op monitor, or an optional one. Fiddly.

**Comment by aloiscochard** [comment]
@tpolecat I'm surprised you need a `Capture` constrain if you already have `Monad`?

I suppose you don't want to capture effect using `return`/`pure`?

**Comment by tpolecat** [comment]
Right, that's the only reason `Capture` exists. We need a way to capture effects in any potential monad. A logger might want to know what time it is, or write to a file, etc.

**Comment by jatcwang** [comment]
LogHandler should support this
