### ISSUE TITLE
Replace runtime reflection with compiletime information

### ISSUE THREAD

**Issue by fommil** [tpolecat/doobie#705]
The `reflect` api is being used in several places, e.g.

https://github.com/tpolecat/doobie/blame/series/0.5.x/modules/core/src/main/scala/doobie/util/meta.scala#L100

This places several arbitrary constraints on the data types that can be used in this API, e.g. static annotations on the data types will blow up the depickler under proguarding.

Please change `TypeTag` to something compiletime. `shapeless.Typeable` probably does everything you want.

**Comment by fommil** [comment]
look like you're only using the `.toString`. You want this https://github.com/milessabin/shapeless/issues/750

**Comment by fommil** [comment]
btw, in my particular case, I was able to sidestep the issue by having my annotation extend `Annotation` instead of `StaticAnnotation`.

**Comment by fommil** [comment]
I might have something in the next few months. I want a good alternative for use in `scalaz-deriving` and `iotaz`...

In the meantime, swapping to `ClassTag` might be *slightly* better than `TypeTag`.

**Comment by fommil** [comment]
if you have a good set of types to use as tests, that would be useful.

**Comment by tpolecat** [comment]
`ClassTag` only gives you the erased type. I need the full type.

**Comment by tpolecat** [comment]
As for testing, it needs to work with any Scala type, so
- primitive types
- reference types
- parameterized types
- intersection types
- existential types
- arrays of the above

**Comment by fommil** [comment]
somebody just pointed me at http://www.lihaoyi.com/PPrint/#TPrint

**Comment by fommil** [comment]
I don't understand why `TypeTag` doesn't just take the information it has at compiletime and shove it into a `String`  so there is zero messing around at runtime with the runtime compiler...

**Comment by propensive** [comment]
I wondered the same thing, so I wrote my own macro to do that. But I think it's because the `TypeTag` can represent abstract types, which might all be called `T` but aren't the same. All being well, my macro should refuse to compile them, but I've not tested it thoroughly.

**Comment by dwijnand** [comment]
> I think it's because the `TypeTag` can represent abstract types

no, that's `WeakTypeTag`: https://docs.scala-lang.org/overviews/reflection/typetags-manifests.html#weaktypetags

**Comment by fommil** [comment]
@propensive which project is that?

**Comment by fommil** [comment]
https://github.com/propensive/totalitarian/blob/master/core/src/main/scala/totalitarian/disjunction.scala#L13
