### ISSUE TITLE
Compilation error when marking doobie as "provided"

### ISSUE THREAD

**Issue by mt40** [tpolecat/doobie#768]
I have a module named `server`. When I include `doobie` as a "provided" dependency like this:
```
"org.tpolecat" %% "doobie-core" % "0.5.2" % "provided"
```
compiling with `sbt server/compile` will produce this error:
```
[error] C:\Users\(...)\server\src\main\scala\main.scala:1:17: Symbol 'term <root>.doobie' is missing from the classpath.
[error] This symbol is required by 'method Repo.test'.
[error] Make sure that term doobie is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Repo.class' was compiled against an incompatible version of <root>.
[error] trait A extends Repo
[error]                 ^
[error] one error found
[error] (server / Compile / compileIncremental) Compilation failed
```

Full build file and sample project to reproduce is here: https://github.com/mt40/sbt_doobie

**Comment by tpolecat** [comment]
I believe this is because your `database` project says "users will provide this library" but the `server` project (which is a user of `database`) doesn't provide it.

**Comment by mt40** [comment]
@tpolecat do you know where I can read about that? I refer to [this Maven doc](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) but it says nothing about `users will provide this library`.
