### ISSUE TITLE
Missing map when constructing HikariTransactor from the example in docs

### ISSUE THREAD

**Issue by mirosval** [tpolecat/doobie#790]
I have roughly the following code:

```scala
    implicit val cs = cats.effect.IO.contextShift(global)
    for {
      cec <- ExecutionContexts.fixedThreadPool[IO](databaseConnectionPoolSize())
      tec <- ExecutionContexts.cachedThreadPool[IO]
      xa <- HikariTransactor.newHikariTransactor[IO](
        driverClassName = driver(),
        url = databaseUrl(),
        user = databaseUser(),
        pass = databasePass(),
        connectEC = cec,
        transactEC = tec
      )
    } yield xa
```

When I try to compile it I get the following error:
```
value map is not a member of cats.effect.Resource[cats.effect.IO,doobie.hikari.HikariTransactor[cats.effect.IO]]
xa <- HikariTransactor.newHikariTransactor[IO](
```

The last statement in a for comprehension calls `map` and `HikariTransactor.newHikariTransactor` returns a `cats.effect.Resource`. `cats.effect.Resource` has a `flatMap` and a `use`, but no map, so that makes sense. 

Question is, how come it works in your [example](https://tpolecat.github.io/doobie/docs/14-Managing-Connections.html#using-a-hikaricp-connection-pool)? I haven't found anything in Cats that would add a `map` operation to the `Resource`.

**Comment by entangled90** [comment]
Did you add import cats.implicits._ ?

**Comment by tpolecat** [comment]
Yeah you need `cats.implicits._` and will need `-Ypartial-unification` as a compiler option.

**Comment by mirosval** [comment]
Thank you both, `-Ypartial-unification` is what I was missing.
