### ISSUE TITLE
postgres: Special whitespace characters are ignored in string arrays

### ISSUE THREAD

**Issue by korlowski** [tpolecat/doobie#799]
If you try to read an array of strings, any "special" whitespace characters (`\u001c`, `\u001d`, `\u001e`, `\u001f`, `\u1680`, `\u2000`, `\u2001`, `\u2002`, `\u2003`, `\u2004`, `\u2005`, `\u2006`, `\u2008`, `\u2009`, `\u200a`, `\u2028`, `\u2029`, `\u205f`, `\u3000`) that appear in any value that doesn't also contain a "standard" whitespace character (`space`, `\t`, `\n`) are ignored.

To illustrate this, I wrote a simple Scalatest test:
```
import doobie._, doobie.implicits._, doobie.postgres.implicits._

def test(s: String) = {
  val input: Array[String] = Array(s)
  val output = sql"SELECT $input".query[Array[String]].unique.transact(tx).unsafeRunSync()

  output should contain theSameElementsAs input
}

"two standard spaces" in test(s"foo bar baz") // passes 
"one standard and one special whitespace character" in test(s"foo bar baz") // passes
"two special whitespace characters" in test(s"foo bar baz") // fails
// Array("foobarbaz") did not contain the same elements as  Array("foo bar baz")
```

As far as I can see, when there is no "standard" whitespace character, postgres represents the value without quotation marks (`{ foo bar baz }`). If you use at least one "standard" whitespace character, postgres surrounds it with quotation marks (`{ "foo bar baz" }`). It seems that the presence of whitespace characters in a value that's not surrounded by quotation marks creates some confusion and they're dropped. This only happens when using the array type.

**Comment by tpolecat** [comment]
Hmm … doobie doesn't touch the contents of arrays, they just go straight to the driver. So this is probably a driver or JDBC bug. I would try to reproduce this using straight JDBC and then go from there.

**Comment by korlowski** [comment]
I've found the corresponding issue on pgjdbc https://github.com/pgjdbc/pgjdbc/issues/1257:

**Comment by tpolecat** [comment]
Cool, thanks for following up. Hopefully it will get sorted on their end.
