### ISSUE TITLE
Add PostGIS support

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#82]
Should be easy, just need to add the dependency and mappings in `pgtypes.scala`.

/cc @aloiscochard

**Comment by aloiscochard** [comment]
Yay! We'll probably try to tackle it soon with @icassina :-)

**Comment by tpolecat** [comment]
Source mirror [here](https://github.com/postgis/postgis/tree/svn-trunk/java) ... looks not too terrible.

**Comment by aloiscochard** [comment]
Indeed, I had no idea that this extension exists!

Thanks a lot

**Comment by tpolecat** [comment]
I'll see if I can hack it up over the weekend. Now that I have the source I have some hope of making it work ... the documentation for postgis with JDBC is terrible.

**Comment by tpolecat** [comment]
Progress. Adding the `postgis-jdbc` dependency makes this work:

```scala
scala> implicit val PGgeometryType = Meta.other[PGgeometry]("geometry")
PGgeometryType: doobie.util.meta.AdvancedMeta[org.postgis.PGgeometry] = doobie.util.meta$Meta$$anon$2@9083e22

scala> val g = sql"select ST_GeomFromText('POINT(-126.4 45.32)', 312)".query[PGgeometry].unique.transact(xa).run
g: org.postgis.PGgeometry = SRID=312;POINT(-126.4 45.32)
```

**Comment by tpolecat** [comment]
Re-openening pending doc review.
