### ISSUE TITLE
doobie + postgres + hikaricp + finatra = locking issues?

### ISSUE THREAD

**Issue by nycjv321** [tpolecat/doobie#843]
I'm using doobie .5.x and I'm noticing weird behavior with Hikari when trying to `insert` as well as `upsert` multiple records to a single table. Hikari seems to lock up when trying to enter only 6 records using futures? They never seem to be able to inserted. The futures do start but never complete. And Upserts seem to only partially complete. 1 out of 6 transactions finish but only after the max duration of the queue time. 

It seems like the connection pool/doobie is locking up. I am using Hikari as a data source and using the standard Transactor _from data source_ initialization.

Is there anything special regarding the configuration using doobie/hikari and Postgres? I've noticed that the newer version of doobie have completely written how doobie hikari should be used. Why is that?

**Comment by tpolecat** [comment]
Can you provide a reproduction of the error you're seeing? It's hard to diagnose from the description.

**Comment by nycjv321** [comment]
Chatted with @tpolecat on gitter. This issue resolved on upgrading to [v.0.6.0](https://github.com/tpolecat/doobie/releases/tag/v0.6.0).
