### ISSUE TITLE
Better SQL literals syntax

### ISSUE THREAD

**Issue by augi** [tpolecat/doobie#844]
### Motivation
Slick: `sqlu"CREATE TABLE #$tableName (id integer PRIMARY KEY)"`
doobie: `(sql"CREATE TABLE" ++ Fragment.const(tableName) ++ fr"(id integer PRIMARY KEY)").update.run`

#### Slick-like
Use same syntax as Slick uses, so probably check [here](https://github.com/tpolecat/doobie/blob/series/0.7.x/modules/core/src/main/scala/doobie/syntax/string.scala#L20) for parts ending with `#`, and then don't create the parameter and append the raw value directly to the sql string.
#### Fragments injection
Allow to inject Fragments using interpolation, so final syntax would be: `sql"CREATE TABLE ${Fragment(tableName)} (id integer PRIMARY KEY)"`
This would require a lot of work IMHO, because Fragment can contains parameters...
#### Raw type
Introduce a new `Raw` type and handle it somehow in the `SqlInterpolator` class (simplified version of previous solution): `sql"CREATE TABLE ${Raw(tableName)} (id integer PRIMARY KEY)"`

Unfortunately, I'm not able to implement none of proposed solutions because I don't understand what't actually happening in the `SqlInterpolator` class :(

**Comment by tpolecat** [comment]
Yeah, I have a working version of this in [Skunk](https://github.com/tpolecat/skunk) and need to port it over. Thanks for the reminder!

**Comment by sideeffffect** [comment]
hello @tpolecat , were you able to make any progress with this?
thanks :)

**Comment by tpolecat** [comment]
No, there are other more pressing things driving 0.7 right now but it would be nice to get it in soonish.
