### ISSUE TITLE
Get arguments for a parameterized query

### ISSUE THREAD

**Issue by djordon** [tpolecat/doobie#849]
Is it possible to get the arguments of a query Fragment? Suppose I have a query like the following:
  ```scala
import doobie.implicits.toSqlInterpolator
import doobie.util.fragment.Fragment

val id: Int = 4
val query: Fragment = sql"""
    SELECT some_column
    FROM some_table
    WHERE id = $id
  """
```
Suppose all I have is the `query` object above. Is it possible for me to retrieve the `id` that will be substituted in and sent to the database? If it's possible, how would one go about retrieving the arguments passed with the prepared statement from the Fragment alone?

**Comment by tpolecat** [comment]
No, it's not possible right now. What do you intend to do with it? The best we could do with the current design would be to provide a `List[Any]` which isn't very useful but could be ok for logging, for instance.

I'm working on a new design for this stuff for [skunk](https://github.com/tpolecat/skunk) which might make it back into doobie at some point.

I'm also working on better logging. :-\

**Comment by djordon** [comment]
I want to be able to provide a string of the query that would be executed against the database. I could get by with the `java.sql.PreparedStatement` object that gets built, since the driver that I am using supports a `toString` method that will return a properly formatted query (assuming we've called the appropriate `setZZZ` methods on the `java.sql.PreparedStatement` object). Is it possible to get a prepared statement object?
