### ISSUE TITLE
Fragments constructors don't add parentheses

### ISSUE THREAD

**Issue by Katrix** [tpolecat/doobie#853]
```scala
Fragments.and(fr1, Fragments.or(fr2, fr3))
``` 
produce
```sql
fr1 AND fr2 OR fr3
```

I would expect something like this instead
```sql
(fr1) AND ((fr2) OR (fr3))
```

**Comment by tpolecat** [comment]
I think that makes sense. I'll take a PR to fix that if anyone wants to do it.

**Comment by m4dc4p** [comment]
I would advocate that the user be responsible for adding parentheses. A rule like this will lead to ugly generated SQL. HaskellDB used a rule like this and, while correct, it was pretty gross when used in the large.

**Comment by tpolecat** [comment]
It would be nice if generated SQL were maximally readable but it seems more important that the associativity matches the Scala code. If we had more structure we could eliminate unnecessary parens but we're just munging strings at this point so I don't think there's much we can do.
