### ISSUE TITLE
Fix compatibility with fs2 1.0.4

### ISSUE THREAD

**Issue by nigredo-tori** [tpolecat/doobie#856]
[fs2 1.0.4](https://github.com/functional-streams-for-scala/fs2/releases/tag/v1.0.4) relaxes the guarantees for order of finalizers. This, for one, means that in expressions like `a ++ b` we can't rely on `a` being finalized before `b` starts. This breaks our [streaming transaction logic](https://github.com/tpolecat/doobie/blob/v0.7.0-M3/modules/core/src/main/scala/doobie/util/transactor.scala#L227), among other things - reading a PostgreSQL large object now leads to an exception since the `BlobInputStream` is closed after the transaction is commited.

fs2 release mentions manually calling `.scope` on streams to provide stronger finalization guarantees - that might be a start.

**Comment by tpolecat** [comment]
Let's fix this for 0.7
