### ISSUE TITLE
rawTrans/rawTransP don't close the connection

### ISSUE THREAD

**Issue by nigredo-tori** [tpolecat/doobie#857]
After tracking down a connection leak in our project, we've found a culprit - a `Transactor.rawTrans` call. The whole purpose of `rawTrans` is to run without the transaction logic (setup/commit/rollback), which is useful in many cases. However, the current `rawTrans` implementation also skips `Strategy.always`. This means that the connection is not properly closed - which in our case resulted in it not being returned to the pool!

The root of the issue here is that `Connection.close` is not a part of the transaction logic, but rather a part of the connection lifetime logic. As such, it should be a part of the `Transactor` itself, and not of its `Strategy`. Ideally, I'd like for `Transaction.connect` to become an `A => Resource[M, Connection]`, so that there is less space to mess up connection handling in the future.

/cc @wedens

**Comment by wedens** [comment]
I'd expand this issue to converting all resource handling (`ResultSet`, `PreparedStatement`, `Connection`, etc) to `Resource` which'll make leaks less likely to occur.

**Comment by tpolecat** [comment]
Yeah if we're allocating the connection we should also close it.

**Comment by nigredo-tori** [comment]
Closing this since `Transactor` and `Strategy` now use `Resource` (#858). @wedens, "resourcifying" the algebras should be its own issue, IMO.
