### ISSUE TITLE
Example NOTIFY/LISTEN program blocks execution

### ISSUE THREAD

**Issue by m4dc4p** [tpolecat/doobie#861]
The example postgres listen/notify blocks the current thread of execution by sleeping while polling for notifications. This is by design, of course. However, I used the code w/o really understanding what it was doing which led to some nasty concurrency issues. 

I think it would make sense to update the example so polling happens on a dedicated thread pool.

**Comment by tpolecat** [comment]
Yeah it's an old example written before `Timer` existed. I'll take a PR to fix it.
