### ISSUE TITLE
Postgres json operators interpreted as parameter holes

### ISSUE THREAD

**Issue by jisantuc** [tpolecat/doobie#888]
## Problem Description

Using any of the postgres operators with `?`s in them seems to confuse doobie's parameter mapping. E.g., I have a table named `projects` where `extras` is a `jsonb` field, and:

```scala
fr"select 1 from projects where extras ? 'someKey' limit 1".query[Int].unique
```

leads to `org.postgresql.util.PSQLException: No value specified for parameter 1`

Similar problems happen with `?|` and `?&`, though I didn't see 

Postgres: 9.6
Doobie: 0.6.0

**Comment by tpolecat** [comment]
This is unspecified in JDBC but according to the Postgres driver doc you can use `??`.

https://jdbc.postgresql.org/documentation/head/statement.html

**Comment by jisantuc** [comment]
Ah, that's exactly what I needed :sunglasses:

**Comment by jisantuc** [comment]
Should I PR a note about this into the FAQ section of the book? It was sort of challenging to figure out who between postgres, jdbc, and doobie was responsible for the escaping behavior, so looking around for this solution was difficult
