### ISSUE TITLE
Transactor.fromDriverManager doesn't allow specifying blocking pool

### ISSUE THREAD

**Issue by Daenyth** [tpolecat/doobie#912]
I'd like to be able to use `fromDriverManager` with my own pool, for jmx instrumentation, etc

**Comment by tpolecat** [comment]
There are overloads (like [this one](https://github.com/tpolecat/doobie/blob/series/0.7.x/modules/core/src/main/scala/doobie/util/transactor.scala#L329-L334)) that take a blocking context … do you need something more than that?

**Comment by Daenyth** [comment]
Ah is that new in 0.7? That's why I didn't see it

**Comment by tpolecat** [comment]
I don't remember … maybe? ;-)
