### ISSUE TITLE
Memory leak in HikariCP connection pool

### ISSUE THREAD

**Issue by chuwy** [tpolecat/doobie#913]
I'm testing my RESTful service built on top of http4s and doobie and encountering cryptic (as always) OOM.

It _suspect_ it happens with any load, but below results are were produced with stress-testing via apache benchmark (`ab -n 1000000 -c 800` from the same host).

Memory dump, couple of minutes after launch:

<img width="923" alt="Screenshot 2019-06-10 at 19 44 06" src="https://user-images.githubusercontent.com/681171/59196292-6ff3c200-8bb8-11e9-80ec-cadd969f7114.png">

The `connectionEC` is the only object in memory that looks _slightly_ (yet) suspicious. Working queue has 778 elements.

I dump memory every 5 minutes and see more or less the same picture. `connectionEC` is always on the first line, but never significantly above 3M. Until ~1hr later I get the OOM and heap produced with `-XX:+HeapDumpOnOutOfMemoryError` shows following picture:

<img width="721" alt="Screenshot 2019-06-10 at 19 54 07" src="https://user-images.githubusercontent.com/681171/59196694-8c442e80-8bb9-11e9-902e-d4a4b9f6a1e5.png">

Basically it filled my heap with... something `doobie`ish inside something `IO`ish (sorry, not very faimiliar with cats-effect internals).

I think this particular setup was poorly configured: small 1CPU/2GB machine, 16 threads in connection pool, 5 `maximumPoolSize` (which looks too big), fairly heavy load and heavy DB response (~400Kb over the network), but other benchmarks have shown similar results.

I'm running this doobie 0.7.0 (same problem was with 0.6.0), http4s-blaze 0.20.1 NIO1. Here's the pool initialization code: https://github.com/snowplow-incubator/iglu-server/blob/release/0.6.0/src/main/scala/com/snowplowanalytics/iglu/server/storage/Storage.scala#L95-L116 (in case I miss somethiing very obvious).

This looks suspciciously similar to https://github.com/tpolecat/doobie/issues/824 / http4s/http4s-okhttp-client#3, except that I'm not using http4s client.

**Comment by chuwy** [comment]
Just in case - the message I'm getting along with OOM:

```
[iglu-hikaricp-pool housekeeper] WARN com.zaxxer.hikari.pool.HikariPool - iglu-hikaricp-pool - Thread starvation or clock leap detected (housekeeper delta=1m238ms398µs104ns).
java.lang.OutOfMemoryError: Java heap space
Dumping heap to /iglu/java_pid6.hprof ...
Heap dump file created [388489171 bytes in 10.352 secs]
Aborting due to java.lang.OutOfMemoryError: Java heap space
...
#  Internal Error (debug.cpp:321), pid=6, tid=72
#  fatal error: OutOfMemory encountered: Java heap space
...
Exception in thread "pool-3-thread-1"
```

**Comment by chuwy** [comment]
It seems the problem was in http4s `Timeout` middleware. The problem went away after we removed it.

I'm leaving the issue open as I don't know whether the issue is in http4s (unlikely as `Timeout` [implementation](https://github.com/http4s/http4s/blob/1ba15a29f93b15e4108ab5e0b64338ada3033ccf/server/src/main/scala/org/http4s/server/middleware/Timeout.scala#L24-L26) is so primitive that I cannot believe it can be wrong) in doobie (maybe something is not cancellable in fact?) or cats-effect.

**Comment by chuwy** [comment]
I think this PR into cats-effect might have fixed it: https://github.com/typelevel/cats-effect/pull/568. Will try to reproduce with both versions.

**Comment by dmydlarz** [comment]
@chuwy any updates on that?

**Comment by mdedetrich** [comment]
Was about to make an issue but I also managed to reproduce this here https://github.com/mdedetrich/task-doobie-memory-leak

**Comment by chuwy** [comment]
@darek1024, sorry for delay - not yet. My problem went away once I removed `Timeout` middleware in http4s code. I still didn't have a chance to write minimal project to reproduce and check if typelevel/cats-effect#568 really fixed it.

**Comment by chuwy** [comment]
@mdedetrich based on this (https://github.com/monix/monix/issues/912) Task also doesn't yet use `setRemoveOnCancelPolicy`, so it certainly can have same source.

**Comment by mdedetrich** [comment]
The leak happens even when you don't use `Task`

**Comment by chuwy** [comment]
Which implementation do you use? I assume that only IO from cats-effect-2.0.0 and ZIO don't suffer from it.

**Comment by mdedetrich** [comment]
In the repository which I linked to, I just used `IO` (well I ran `IO.unsafeToFuture`) without any task and the leak was still there.

**Comment by jatcwang** [comment]
Closing this as it's probably not an issue anymore. Please reopen if that's not true
