### ISSUE TITLE
ANY fragment

### ISSUE THREAD

**Issue by ShahOdin** [tpolecat/doobie#917]
I am trying to write an `Any` fragment but i am not quite there.

This is what I have: 

    import doobie.implicits._
    import cats.Reducible
    import cats.syntax.foldable._
    import cats.instances.list._
    def any[F[_]: Reducible, A: Put](fs: F[A]): Fragment = {
      fs
        .toList
        .map(a => fr0"$a")
        .foldSmash1(fr"any (array[", fr",", fr"])")
    }

and I am calling it like this: 

    any(
        NonEmptyList
                .of("ABC", "XYZ")
                .map(s => s"'%$s%'")
    )

to create patterns to use with a `LIKE` query. It compiles but it doesn't seem to work, while my string version does:

    implicit class stringListOps(val l: NonEmptyList[String]){
      def asPostgressArray: String = {
        import cats.instances.string._
        import cats.syntax.foldable._
        l.foldSmash("any (array[", ",", "])")
      }
    }

    def anyString(values: NonEmptyList[String]): Fragment = {
      Fragment.const(values.asPostgressArray)
    }

I understand I have an injection problem but i don't understand what I am doing differently from say the `in` fragment from the library.

**Comment by guymers** [comment]
Looking at the SQL that is run for `any`:
```
LOG:  execute <unnamed>: 
  SELECT name FROM test
  WHERE name LIKE any (array[ $1, $2]) 
DETAIL:  parameters: $1 = '''%ABC%''', $2 = '''%XYZ%'''
```

For `anyString`:
```
LOG:  execute <unnamed>: 
  SELECT name FROM test
  WHERE name LIKE any (array['%ABC%','%XYZ%'])
```

As `any` is using SQL parameterisation it does not need to be manually escaped. Calling `any` without adding the single quotes:
```
LOG:  execute <unnamed>: 
  SELECT name FROM test
  WHERE name LIKE any (array[ $1, $2]) 
DETAIL:  parameters: $1 = '%ABC%', $2 = '%XYZ%'
```
which should return same rows as `anyString`.

**Comment by jatcwang** [comment]
Seems like the questions is answered so I'm closing this issue. Feel free to reply if it isn't, or you can ask in https://gitter.im/tpolecat/doobie
