### ISSUE TITLE
book of doobie errata

### ISSUE THREAD

**Issue by icassina** [tpolecat/doobie#93]
In chapter 04 I believe there is an example which failed to be updated:

```
scala> (sql"select code, name, population, gnp from country"
     |    .query[(Code, Country)] // Query0[(Code, Country)]
     |    .process.take(5)        // Process[ConnectionIO, (Code, Country)]
     |    .list                   // ConnectionIO[List[(Code, Country)]]
     |    .map(_.toMap)           // ConnectionIO[Map[Code, Country]]
     |    .quick.run)
  Map(Code(ANT) -> Country(Netherlands Antilles,217000,Some(1941.0)), Code(DZA) -> Country(Algeria,31471000,Some(49982.0)), Code(ALB) -> Country(Albania,3401200,Some(3205.0)), Code(NLD) -> Country(Netherlands,15864000,Some(371362.0)), Code(AFG) -> Country(Afghanistan,22720000,Some(5976.0)))
```

i.e. Code(ANT) should refer to the Antilles Country, not the "Netherlands Antilles" one.

**Comment by icassina** [comment]
In chapter 10 / Setting up:

> ... The examples in this chapter require the contrib-postgresql add-on, as well as the argonaut JSON library, which you can **ADD** to your build thus: ...

**Comment by tpolecat** [comment]
Thanks! Please leave any other notes here and I will fix them up.

Looks like `ANT` ISO code is for Netherlands Antilles, so I think it is correct.

```sql
INSERT INTO country VALUES ('ANT', 'Netherlands Antilles', 'North America', 'Caribbean', 800, NULL, 217000, 74.699997, 1941.00, NULL, 'Nederlandse Antillen', 'Nonmetropolitan Territory of The Netherlands', 'Beatrix', 33, 'AN');
```

**Comment by icassina** [comment]
learning new things everyday!

**Comment by icassina** [comment]
`doobie-contrib-postgresql` vs "doobie-contrib-postgres":

### 1. Introduction:
…
Scala setup: the sbt snippet is correct (doobie-contrib-postgresql) but the text following it refers to it as "doobie-contrib-postgres".

### 9. SQL Arrays
first paragraph: "the code in this chapter requires doobie-contrib-postgres." (following code imports are correct)

### 12. Vendor Extensions
under "PostgreSQL Support", the package is referenced as "doobie-contrib-postgres" (wrong). The types package is in the wrong namespace as well.
