### ISSUE TITLE
Instrumentation of KleisliInterpreters?

### ISSUE THREAD

**Issue by Fristi** [tpolecat/doobie#930]
Would this be a good place for instrumenting queries?

With instrumentation I mean

- Metrics (histogram and counter per query)
- Tracing (via natchez?)

WDYT?

**Comment by Fristi** [comment]
No shared excitement for this feature and I don't have a need for it as well. It was just a wild idea, closing it for now.

**Comment by tpolecat** [comment]
I actually have a branch for this

**Comment by Fristi** [comment]
Cool, is the branch public somewhere for learnings :) ?

**Comment by Fristi** [comment]
I think https://github.com/tpolecat/doobie/pull/811 is the branch your talking about right? Can we extract out a tagless interface which can be implemented by the user ? Like http4s also does with metrics (https://github.com/http4s/http4s/blob/80df97e1fdb1d764059acafcd1f4331135964560/core/src/main/scala/org/http4s/metrics/MetricsOps.scala)

I think some users might want to plugin in https://github.com/tpolecat/natchez/ while others want just logging or use ZIO with a tracing implementation. 

WDYT?

**Comment by tpolecat** [comment]
Yeah, I was trying to avoid adding an extra bind to every primitive operation but that's probably premature optimization. I think tracing is probably what people actually want but nobody is using it right now. Hard to abstract over tracing ~ logging so I'm not sure what makes sense in the interim.

**Comment by Fristi** [comment]
At ovotech the seemed to have done an Traced interpreter based on nantchez: https://github.com/ovotech/effect-utils/blob/master/natchez-doobie/src/main/scala/com/ovoenergy/effect/natchez/TracedTransactor.scala

I've been using that, what do you think of it? If it's not wrong or can be left out of doobie we can close this issue
