### ISSUE TITLE
dynamically combining Fragments and getting `ExceptionInInitializerError`

### ISSUE THREAD

**Issue by ShahOdin** [tpolecat/doobie#941]
I am trying to introduce an abstraction over mapping an instance of a domain model to multiple database entries. I have: 

    private[postgres] abstract class PostgresKVStore[K, V]{
      def get(key: K): Query0[A]
      def insertColumns: Fragment
      def insertValues(item: V): Fragment
      def delete(key: K): Update0
    }

Where the insertColumns will be of the form: `sql"INSERT INTO myTable (x,y,z)"`
and insertValues will be of the form: `sql"Values (x1,y1,z1)"`.

I then have an adapter that expose this interface:

    trait KVStore[F[_], K, A]{
      def get(key: K): F[Either[FormatError, Option[A]]]
      def put(key: K, payload: A): F[Unit]
      def delete(key: K): F[Unit]
    }

and I create the put method like so: 

    def put(key: K, item: B): ConnectionIO[Unit] =
            toStoreEnteries(key, item)
              .map(pgStore.insertValues)
              .foldSmash1(pgStore.insertColumns, sql", ", Fragment.empty)
              .update
              .run
              .flatMap {
                case i if i > 0 =>
                  ().pure[ConnectionIO]
                case _ =>
                  new Exception(s"Failed to put the item: $item in the database").raiseError
              }

where `toStoreEnteries: (K, B) => List[A]` and `pgStore: PostgresKVStore[K, A]`

Sadly, I am getting a `ExceptionInInitializerError` on `insertValues`. Is there something wrong with what I plan on doing?

**Comment by tpolecat** [comment]
Do you have a stacktrace?

**Comment by ShahOdin** [comment]
haven't tried a minimal example of it yet, but here is what I am currently getting:


An exception or error caused a run to abort. 
> java.lang.ExceptionInInitializerError
	at [x.y.z].PostgresStore$$anon$1.insertValues(PostgresSStore.scala:32)
	at [x.y.z].PostgresStore$$anon$1.insertValues(PostgresStore.scala:26)
at [x.y.z].PostgresKVStore$PostgresKVStoreOps$$anon$1.$anonfun$put$1(PostgresKVStore.scala:35)

The line which fails is:       

    override def insertValues(item: SchedulePGEntry): Fragment =
        sql"VALUES (${item.id}, ${item.platform}, ${item.window})"

**Comment by tpolecat** [comment]
Can you post the full stacktrace? There has to be more information somewhere.

**Comment by ShahOdin** [comment]
found that error in the end. The ExceptionInInitializerError was due to a silly mistake by me of the form: 

    implicit val fooRead: Read[Foo] = Read[Foo] 

but yeah this works.
