### ISSUE TITLE
Publish doobie-quill for Scala 2.13

### ISSUE THREAD

**Issue by KadekM** [tpolecat/doobie#953]
It seems to be missing:
https://mvnrepository.com/artifact/org.tpolecat/doobie-quill

**Comment by stsatlantis** [comment]
Is there a reason why it is not published for 2.13? :)

**Comment by tpolecat** [comment]
Yes, Quill isn't available for 2.13 yet.

**Comment by aeons** [comment]
Quill 3.4.10 is out with 2.13 support.

**Comment by tpolecat** [comment]
Oh great! This will simplify the build. Probably no time today but I'll try to get to it over the weekend.

**Comment by tovbinm** [comment]
This would be great to have! Thank you.

**Comment by jatcwang** [comment]
https://mvnrepository.com/artifact/org.tpolecat/doobie-quill_2.13/0.9.0

Seems like this is addressed. Closing.
