### ISSUE TITLE
Quill Read nullable last column throws Nullpointer

### ISSUE THREAD

**Issue by amitmh** [tpolecat/doobie#960]
Given:
```sql
test_db=> \d person
                                   Table "public.person"
 Column |         Type          | Collation | Nullable |              Default
--------+-----------------------+-----------+----------+------------------------------------
 id     | integer               |           | not null | nextval('person_id_seq'::regclass)
 name   | character varying(56) |           | not null |
 age    | integer               |           |          |
Indexes:
    "person_pkey" PRIMARY KEY, btree (id)

test_db=> select * from person;
 id | name | age
----+------+-----
  1 | Joe  |
(1 row)

test_db=>
```
And Code
```scala
  val dc = new DoobieContext.Postgres(Literal) // Literal naming scheme
  import dc._
  
  def readPersonQuery: ConnectionIO[List[Person]] =
    run(
      quote(
        query[Person]
      )
    )
  def readPersonFragment: ConnectionIO[List[Person]] = {
    import doobie.implicits._
    sql"select id, name, age from person".query[Person].to[List]
  }
 //This works
val fragResult = readPersonFragment.transact(xa).unsafeRunSync()

//while this fails
readPersonQuery.transact(xa).unsafeRunSync()

```
Quill module fails to read Nullable column

**Comment by amitmh** [comment]
Example with minimal code is added over here: 
https://github.com/amitmh/doobie-quill-null/

Please let me know if you need any further details.

**Comment by amitmh** [comment]
```
java.lang.NullPointerException
	at cats.Show$$anon$2.show(Show.scala:43)
	at cats.Show$Shown$.mat(Show.scala:48)
	at doobie.util.invariant$NonNullableColumnRead.<init>(invariant.scala:60)
	at doobie.util.Get.unsafeGetNonNullable(get.scala:30)
	at doobie.util.Read$.$anonfun$fromGet$1(read.scala:75)
```

**Comment by matwojcik** [comment]
Hi i think I have the same issue - However I noticed it only happens when the nullable field is the last column in mapping and it is actually null. When it is either defined or not last column then it works.

**Comment by amitmh** [comment]
@matwojcik thanks for letting me know. Let me update the example.
with doobie 0.7.0 onwards it gives null pointer exception for show instances.

**Comment by amitmh** [comment]
I can confirm this happens only if optional column last and has null value. Thanks @matwojcik this will help me to remove handwritten queries.

**Comment by tpolecat** [comment]
Looks like the show thing is a bug. It's throwing when it's trying to construct that exception.

**Comment by amitmh** [comment]
@tpolecat Yes. I am not sure why it is identifying type as not nullable.
`	at doobie.util.Get.unsafeGetNonNullable(get.scala:30)`

**Comment by WilsonHo** [comment]
As I tested this issue, the last column from DB can be nullable but from the mapping case class, it should not be an optional field.

**Comment by amitmh** [comment]
> As I tested this issue, the last column from DB can be nullable but from the mapping case class, it should not be an optional field.

we are suppose to map nullable column to optional field in doobie.
