### ISSUE TITLE
Algebras and free monads thereof for Postgres driver extensions

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#97]
Need `free`-level algebras for:
- `PGConnecton`
- `CopyManager`
- `FastPath`
- `LargeObjectManager`

And `hi`-level combinators where sensible.

Assuming this works, hacking up a `Process[Task,PGNotification]` would be a really cool demo.

N.B. also need a `liftPGConnection : ConnectionIO[A]` implemented in terms of `unwrap`.

**Comment by justjoheinz** [comment]
+1 for PGNotification - this would be awesome.

**Comment by tpolecat** [comment]
Noted. Need to get 0.2.1 in the can (almost done) and then I'm eager to start hacking on it.

**Comment by tpolecat** [comment]
@justjoheinz fyi https://gist.github.com/tpolecat/b5ec288eca42140b6286 ... it can be better but it's a nice start
