### ISSUE TITLE
Support for query fragments

### ISSUE THREAD

**Issue by tpolecat** [tpolecat/doobie#99]
@wedens suggests concatenable query fragments that build up a set of parameters along with the sql string. Need `HList` support to make this convenient.

**Comment by wedens** [comment]
my proposed data structure is something like this:
```scala
case class QueryFragment[L <: HList: Composite](query: Cord, params: L) {
  def ++[P <: HList, POut <: HList](other: QueryFragment[P])
    (implicit p: Prepend.Aux[L, P, POut], mtout: Composite[POut]): QueryFragment[POut] =
      QueryFragment(query ++ other.query, params ++ other.params)
}
```

**Comment by tpolecat** [comment]
I like it.

**Comment by kryptt** [comment]
I've been running into some issues with this idea... specifically, I can't make a semigroup out of this, since what we want is precisely to be able to append arbitrary QueryFragments together...

**Comment by tpolecat** [comment]
It can never be a semigroup because the type argument changes, but it should definitely be possible to append fragments (that's the whole point). Sorry I haven't had time to focus on this; I'm working on some less interesting things.
