### ISSUE TITLE
multiple overloaded alternatives of method executeActionReturning

### ISSUE THREAD

**Issue by t3hnar** [tpolecat/doobie#992]
This is rather not an issue, but a request for help. 
I have the following code:

```
object SqlServerContext extends DoobieContext.SQLServer[Literal](Literal)
```

and it does not compile, error:

```
Error:(16, 8) in object SqlServerContext, multiple overloaded alternatives of method executeActionReturning define default arguments.
The members with defaults are defined in trait DoobieContextBase in package quill and trait JdbcContextBase in package jdbc.
object SqlServerContext extends DoobieContext.SQLServer[Literal](Literal)
```

@tpolecat maybe you could help me to figure out what I'm missing? I checked this project & plugins - so far with no lack.

PS: thx for open sourcing such a nice library

**Comment by tpolecat** [comment]
Hmm, I haven't seen this. Do you have an explicit Quill dependency by chance (rather than using the one pulled in by `doobie-quill`)?

**Comment by t3hnar** [comment]
scala: 2.12.9
```
"io.getquill" %% "quill-jdbc" % "3.4.3"
"org.tpolecat" %% "doobie-quill" % "0.7.0"
```

**Comment by tpolecat** [comment]
Hm, remove the explicit quill dependency and see what happens. You can update to doobie 0.8.0-RC1 if you want the latest Quill version, but let doobie pull it in for you.

**Comment by t3hnar** [comment]
@tpolecat indeed downgrade to `quill 3.1.0` helped, dangerous things.

Thanks for help.
